from __future__ import annotations
from ctypes import c_void_p, Structure, Union, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from win32more.base import ARCH, MissingType, c_char_p_no, c_wchar_p_no, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head
import win32more.Foundation
import win32more.Storage.IndexServer
import win32more.System.Com
import win32more.System.Com.StructuredStorage
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        if name in _arch_optional:
            return None
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
def __dir__():
    return __all__
CI_VERSION_WDS30: UInt32 = 258
CI_VERSION_WDS40: UInt32 = 265
CI_VERSION_WIN70: UInt32 = 1792
CINULLCATALOG: String = '::_noindex_::'
CIADMIN: String = '::_nodocstore_::'
LIFF_LOAD_DEFINED_FILTER: UInt32 = 1
LIFF_IMPLEMENT_TEXT_FILTER_FALLBACK_POLICY: UInt32 = 2
LIFF_FORCE_TEXT_FILTER_FALLBACK: UInt32 = 3
PID_FILENAME: UInt32 = 100
DBPROP_CI_CATALOG_NAME: UInt32 = 2
DBPROP_CI_INCLUDE_SCOPES: UInt32 = 3
DBPROP_CI_DEPTHS: UInt32 = 4
DBPROP_CI_SCOPE_FLAGS: UInt32 = 4
DBPROP_CI_EXCLUDE_SCOPES: UInt32 = 5
DBPROP_CI_SECURITY_ID: UInt32 = 6
DBPROP_CI_QUERY_TYPE: UInt32 = 7
DBPROP_CI_PROVIDER: UInt32 = 8
CI_PROVIDER_MSSEARCH: UInt32 = 1
CI_PROVIDER_INDEXING_SERVICE: UInt32 = 2
CI_PROVIDER_ALL: UInt32 = 4294967295
DBPROP_DEFAULT_EQUALS_BEHAVIOR: UInt32 = 2
DBPROP_USECONTENTINDEX: UInt32 = 2
DBPROP_DEFERNONINDEXEDTRIMMING: UInt32 = 3
DBPROP_USEEXTENDEDDBTYPES: UInt32 = 4
DBPROP_IGNORENOISEONLYCLAUSES: UInt32 = 5
DBPROP_GENERICOPTIONS_STRING: UInt32 = 6
DBPROP_FIRSTROWS: UInt32 = 7
DBPROP_DEFERCATALOGVERIFICATION: UInt32 = 8
DBPROP_CATALOGLISTID: UInt32 = 9
DBPROP_GENERATEPARSETREE: UInt32 = 10
DBPROP_APPLICATION_NAME: UInt32 = 11
DBPROP_FREETEXTANYTERM: UInt32 = 12
DBPROP_FREETEXTUSESTEMMING: UInt32 = 13
DBPROP_IGNORESBRI: UInt32 = 14
DBPROP_DONOTCOMPUTEEXPENSIVEPROPS: UInt32 = 15
DBPROP_ENABLEROWSETEVENTS: UInt32 = 16
DBPROP_MACHINE: UInt32 = 2
DBPROP_CLIENT_CLSID: UInt32 = 3
MSIDXSPROP_ROWSETQUERYSTATUS: UInt32 = 2
MSIDXSPROP_COMMAND_LOCALE_STRING: UInt32 = 3
MSIDXSPROP_QUERY_RESTRICTION: UInt32 = 4
MSIDXSPROP_PARSE_TREE: UInt32 = 5
MSIDXSPROP_MAX_RANK: UInt32 = 6
MSIDXSPROP_RESULTS_FOUND: UInt32 = 7
MSIDXSPROP_WHEREID: UInt32 = 8
MSIDXSPROP_SERVER_VERSION: UInt32 = 9
MSIDXSPROP_SERVER_WINVER_MAJOR: UInt32 = 10
MSIDXSPROP_SERVER_WINVER_MINOR: UInt32 = 11
MSIDXSPROP_SERVER_NLSVERSION: UInt32 = 12
MSIDXSPROP_SERVER_NLSVER_DEFINED: UInt32 = 13
MSIDXSPROP_SAME_SORTORDER_USED: UInt32 = 14
STAT_BUSY: UInt32 = 0
STAT_ERROR: UInt32 = 1
STAT_DONE: UInt32 = 2
STAT_REFRESH: UInt32 = 3
STAT_PARTIAL_SCOPE: UInt32 = 8
STAT_NOISE_WORDS: UInt32 = 16
STAT_CONTENT_OUT_OF_DATE: UInt32 = 32
STAT_REFRESH_INCOMPLETE: UInt32 = 64
STAT_CONTENT_QUERY_INCOMPLETE: UInt32 = 128
STAT_TIME_LIMIT_EXCEEDED: UInt32 = 256
STAT_SHARING_VIOLATION: UInt32 = 512
STAT_MISSING_RELDOC: UInt32 = 1024
STAT_MISSING_PROP_IN_RELDOC: UInt32 = 2048
STAT_RELDOC_ACCESS_DENIED: UInt32 = 4096
STAT_COALESCE_COMP_ALL_NOISE: UInt32 = 8192
QUERY_SHALLOW: UInt32 = 0
QUERY_DEEP: UInt32 = 1
QUERY_PHYSICAL_PATH: UInt32 = 0
QUERY_VIRTUAL_PATH: UInt32 = 2
PROPID_QUERY_WORKID: UInt32 = 5
PROPID_QUERY_UNFILTERED: UInt32 = 7
PROPID_QUERY_VIRTUALPATH: UInt32 = 9
PROPID_QUERY_LASTSEENTIME: UInt32 = 10
CICAT_STOPPED: UInt32 = 1
CICAT_READONLY: UInt32 = 2
CICAT_WRITABLE: UInt32 = 4
CICAT_NO_QUERY: UInt32 = 8
CICAT_GET_STATE: UInt32 = 16
CICAT_ALL_OPENED: UInt32 = 32
CI_STATE_SHADOW_MERGE: UInt32 = 1
CI_STATE_MASTER_MERGE: UInt32 = 2
CI_STATE_CONTENT_SCAN_REQUIRED: UInt32 = 4
CI_STATE_ANNEALING_MERGE: UInt32 = 8
CI_STATE_SCANNING: UInt32 = 16
CI_STATE_RECOVERING: UInt32 = 32
CI_STATE_INDEX_MIGRATION_MERGE: UInt32 = 64
CI_STATE_LOW_MEMORY: UInt32 = 128
CI_STATE_HIGH_IO: UInt32 = 256
CI_STATE_MASTER_MERGE_PAUSED: UInt32 = 512
CI_STATE_READ_ONLY: UInt32 = 1024
CI_STATE_BATTERY_POWER: UInt32 = 2048
CI_STATE_USER_ACTIVE: UInt32 = 4096
CI_STATE_STARTING: UInt32 = 8192
CI_STATE_READING_USNS: UInt32 = 16384
CI_STATE_DELETION_MERGE: UInt32 = 32768
CI_STATE_LOW_DISK: UInt32 = 65536
CI_STATE_HIGH_CPU: UInt32 = 131072
CI_STATE_BATTERY_POLICY: UInt32 = 262144
GENERATE_METHOD_EXACT: UInt32 = 0
GENERATE_METHOD_PREFIX: UInt32 = 1
GENERATE_METHOD_INFLECT: UInt32 = 2
SCOPE_FLAG_MASK: UInt32 = 255
SCOPE_FLAG_INCLUDE: UInt32 = 1
SCOPE_FLAG_DEEP: UInt32 = 2
SCOPE_TYPE_MASK: UInt32 = 4294967040
SCOPE_TYPE_WINPATH: UInt32 = 256
SCOPE_TYPE_VPATH: UInt32 = 512
PROPID_QUERY_RANKVECTOR: UInt32 = 2
PROPID_QUERY_RANK: UInt32 = 3
PROPID_QUERY_HITCOUNT: UInt32 = 4
PROPID_QUERY_ALL: UInt32 = 6
PROPID_STG_CONTENTS: UInt32 = 19
VECTOR_RANK_MIN: UInt32 = 0
VECTOR_RANK_MAX: UInt32 = 1
VECTOR_RANK_INNER: UInt32 = 2
VECTOR_RANK_DICE: UInt32 = 3
VECTOR_RANK_JACCARD: UInt32 = 4
DBSETFUNC_NONE: UInt32 = 0
DBSETFUNC_ALL: UInt32 = 1
DBSETFUNC_DISTINCT: UInt32 = 2
PROXIMITY_UNIT_WORD: UInt32 = 0
PROXIMITY_UNIT_SENTENCE: UInt32 = 1
PROXIMITY_UNIT_PARAGRAPH: UInt32 = 2
PROXIMITY_UNIT_CHAPTER: UInt32 = 3
NOT_AN_ERROR: win32more.Foundation.HRESULT = 524288
FILTER_E_END_OF_CHUNKS: win32more.Foundation.HRESULT = -2147215616
FILTER_E_NO_MORE_TEXT: win32more.Foundation.HRESULT = -2147215615
FILTER_E_NO_MORE_VALUES: win32more.Foundation.HRESULT = -2147215614
FILTER_E_ACCESS: win32more.Foundation.HRESULT = -2147215613
FILTER_W_MONIKER_CLIPPED: win32more.Foundation.HRESULT = 268036
FILTER_E_NO_TEXT: win32more.Foundation.HRESULT = -2147215611
FILTER_E_NO_VALUES: win32more.Foundation.HRESULT = -2147215610
FILTER_E_EMBEDDING_UNAVAILABLE: win32more.Foundation.HRESULT = -2147215609
FILTER_E_LINK_UNAVAILABLE: win32more.Foundation.HRESULT = -2147215608
FILTER_S_LAST_TEXT: win32more.Foundation.HRESULT = 268041
FILTER_S_LAST_VALUES: win32more.Foundation.HRESULT = 268042
FILTER_E_PASSWORD: win32more.Foundation.HRESULT = -2147215605
FILTER_E_UNKNOWNFORMAT: win32more.Foundation.HRESULT = -2147215604
@winfunctype('query.dll')
def LoadIFilter(pwcsPath: win32more.Foundation.PWSTR, pUnkOuter: win32more.System.Com.IUnknown_head, ppIUnk: POINTER(c_void_p)) -> win32more.Foundation.HRESULT: ...
@winfunctype('query.dll')
def LoadIFilterEx(pwcsPath: win32more.Foundation.PWSTR, dwFlags: UInt32, riid: POINTER(Guid), ppIUnk: POINTER(c_void_p)) -> win32more.Foundation.HRESULT: ...
@winfunctype('query.dll')
def BindIFilterFromStorage(pStg: win32more.System.Com.StructuredStorage.IStorage_head, pUnkOuter: win32more.System.Com.IUnknown_head, ppIUnk: POINTER(c_void_p)) -> win32more.Foundation.HRESULT: ...
@winfunctype('query.dll')
def BindIFilterFromStream(pStm: win32more.System.Com.IStream_head, pUnkOuter: win32more.System.Com.IUnknown_head, ppIUnk: POINTER(c_void_p)) -> win32more.Foundation.HRESULT: ...
CHUNK_BREAKTYPE = Int32
CHUNK_NO_BREAK: CHUNK_BREAKTYPE = 0
CHUNK_EOW: CHUNK_BREAKTYPE = 1
CHUNK_EOS: CHUNK_BREAKTYPE = 2
CHUNK_EOP: CHUNK_BREAKTYPE = 3
CHUNK_EOC: CHUNK_BREAKTYPE = 4
CHUNKSTATE = Int32
CHUNK_TEXT: CHUNKSTATE = 1
CHUNK_VALUE: CHUNKSTATE = 2
CHUNK_FILTER_OWNED_VALUE: CHUNKSTATE = 4
class CI_STATE(Structure):
    cbStruct: UInt32
    cWordList: UInt32
    cPersistentIndex: UInt32
    cQueries: UInt32
    cDocuments: UInt32
    cFreshTest: UInt32
    dwMergeProgress: UInt32
    eState: UInt32
    cFilteredDocuments: UInt32
    cTotalDocuments: UInt32
    cPendingScans: UInt32
    dwIndexSize: UInt32
    cUniqueKeys: UInt32
    cSecQDocuments: UInt32
    dwPropCacheSize: UInt32
if ARCH in 'X64,ARM64':
    class DBID(Structure):
        uGuid: _uGuid_e__Union
        eKind: UInt32
        uName: _uName_e__Union
        class _uGuid_e__Union(Union):
            guid: Guid
            pguid: POINTER(Guid)
        class _uName_e__Union(Union):
            pwszName: win32more.Foundation.PWSTR
            ulPropid: UInt32
if ARCH in 'X86':
    class DBID(Structure):
        uGuid: _uGuid_e__Union
        eKind: UInt32
        uName: _uName_e__Union
        _pack_ = 2
        class _uGuid_e__Union(Union):
            guid: Guid
            pguid: POINTER(Guid)
            _pack_ = 2
        class _uName_e__Union(Union):
            pwszName: win32more.Foundation.PWSTR
            ulPropid: UInt32
            _pack_ = 2
DBKINDENUM = Int32
DBKIND_GUID_NAME: DBKINDENUM = 0
DBKIND_GUID_PROPID: DBKINDENUM = 1
DBKIND_NAME: DBKINDENUM = 2
DBKIND_PGUID_NAME: DBKINDENUM = 3
DBKIND_PGUID_PROPID: DBKINDENUM = 4
DBKIND_PROPID: DBKINDENUM = 5
DBKIND_GUID: DBKINDENUM = 6
class FILTERREGION(Structure):
    idChunk: UInt32
    cwcStart: UInt32
    cwcExtent: UInt32
class FULLPROPSPEC(Structure):
    guidPropSet: Guid
    psProperty: win32more.System.Com.StructuredStorage.PROPSPEC
class IFilter(c_void_p):
    extends: win32more.System.Com.IUnknown
    Guid = Guid('89bcb740-6119-101a-bc-b7-00-dd-01-06-55-af')
    @commethod(3)
    def Init(grfFlags: UInt32, cAttributes: UInt32, aAttributes: POINTER(win32more.Storage.IndexServer.FULLPROPSPEC_head), pFlags: POINTER(UInt32)) -> Int32: ...
    @commethod(4)
    def GetChunk(pStat: POINTER(win32more.Storage.IndexServer.STAT_CHUNK_head)) -> Int32: ...
    @commethod(5)
    def GetText(pcwcBuffer: POINTER(UInt32), awcBuffer: win32more.Foundation.PWSTR) -> Int32: ...
    @commethod(6)
    def GetValue(ppPropValue: POINTER(POINTER(win32more.System.Com.StructuredStorage.PROPVARIANT_head))) -> Int32: ...
    @commethod(7)
    def BindRegion(origPos: win32more.Storage.IndexServer.FILTERREGION, riid: POINTER(Guid), ppunk: POINTER(c_void_p)) -> Int32: ...
IFILTER_FLAGS = Int32
IFILTER_FLAGS_OLE_PROPERTIES: IFILTER_FLAGS = 1
IFILTER_INIT = Int32
IFILTER_INIT_CANON_PARAGRAPHS: IFILTER_INIT = 1
IFILTER_INIT_HARD_LINE_BREAKS: IFILTER_INIT = 2
IFILTER_INIT_CANON_HYPHENS: IFILTER_INIT = 4
IFILTER_INIT_CANON_SPACES: IFILTER_INIT = 8
IFILTER_INIT_APPLY_INDEX_ATTRIBUTES: IFILTER_INIT = 16
IFILTER_INIT_APPLY_OTHER_ATTRIBUTES: IFILTER_INIT = 32
IFILTER_INIT_APPLY_CRAWL_ATTRIBUTES: IFILTER_INIT = 256
IFILTER_INIT_INDEXING_ONLY: IFILTER_INIT = 64
IFILTER_INIT_SEARCH_LINKS: IFILTER_INIT = 128
IFILTER_INIT_FILTER_OWNED_VALUE_OK: IFILTER_INIT = 512
IFILTER_INIT_FILTER_AGGRESSIVE_BREAK: IFILTER_INIT = 1024
IFILTER_INIT_DISABLE_EMBEDDED: IFILTER_INIT = 2048
IFILTER_INIT_EMIT_FORMATTING: IFILTER_INIT = 4096
class IPhraseSink(c_void_p):
    extends: win32more.System.Com.IUnknown
    Guid = Guid('cc906ff0-c058-101a-b5-54-08-00-2b-33-b0-e6')
    @commethod(3)
    def PutSmallPhrase(pwcNoun: win32more.Foundation.PWSTR, cwcNoun: UInt32, pwcModifier: win32more.Foundation.PWSTR, cwcModifier: UInt32, ulAttachmentType: UInt32) -> win32more.Foundation.HRESULT: ...
    @commethod(4)
    def PutPhrase(pwcPhrase: win32more.Foundation.PWSTR, cwcPhrase: UInt32) -> win32more.Foundation.HRESULT: ...
class STAT_CHUNK(Structure):
    idChunk: UInt32
    breakType: win32more.Storage.IndexServer.CHUNK_BREAKTYPE
    flags: win32more.Storage.IndexServer.CHUNKSTATE
    locale: UInt32
    attribute: win32more.Storage.IndexServer.FULLPROPSPEC
    idChunkSource: UInt32
    cwcStartSource: UInt32
    cwcLenSource: UInt32
WORDREP_BREAK_TYPE = Int32
WORDREP_BREAK_EOW: WORDREP_BREAK_TYPE = 0
WORDREP_BREAK_EOS: WORDREP_BREAK_TYPE = 1
WORDREP_BREAK_EOP: WORDREP_BREAK_TYPE = 2
WORDREP_BREAK_EOC: WORDREP_BREAK_TYPE = 3
make_head(_module, 'CI_STATE')
if ARCH in 'X64,ARM64':
    make_head(_module, 'DBID')
if ARCH in 'X86':
    make_head(_module, 'DBID')
make_head(_module, 'FILTERREGION')
make_head(_module, 'FULLPROPSPEC')
make_head(_module, 'IFilter')
make_head(_module, 'IPhraseSink')
make_head(_module, 'STAT_CHUNK')
__all__ = [
    "BindIFilterFromStorage",
    "BindIFilterFromStream",
    "CHUNKSTATE",
    "CHUNK_BREAKTYPE",
    "CHUNK_EOC",
    "CHUNK_EOP",
    "CHUNK_EOS",
    "CHUNK_EOW",
    "CHUNK_FILTER_OWNED_VALUE",
    "CHUNK_NO_BREAK",
    "CHUNK_TEXT",
    "CHUNK_VALUE",
    "CIADMIN",
    "CICAT_ALL_OPENED",
    "CICAT_GET_STATE",
    "CICAT_NO_QUERY",
    "CICAT_READONLY",
    "CICAT_STOPPED",
    "CICAT_WRITABLE",
    "CINULLCATALOG",
    "CI_PROVIDER_ALL",
    "CI_PROVIDER_INDEXING_SERVICE",
    "CI_PROVIDER_MSSEARCH",
    "CI_STATE",
    "CI_STATE_ANNEALING_MERGE",
    "CI_STATE_BATTERY_POLICY",
    "CI_STATE_BATTERY_POWER",
    "CI_STATE_CONTENT_SCAN_REQUIRED",
    "CI_STATE_DELETION_MERGE",
    "CI_STATE_HIGH_CPU",
    "CI_STATE_HIGH_IO",
    "CI_STATE_INDEX_MIGRATION_MERGE",
    "CI_STATE_LOW_DISK",
    "CI_STATE_LOW_MEMORY",
    "CI_STATE_MASTER_MERGE",
    "CI_STATE_MASTER_MERGE_PAUSED",
    "CI_STATE_READING_USNS",
    "CI_STATE_READ_ONLY",
    "CI_STATE_RECOVERING",
    "CI_STATE_SCANNING",
    "CI_STATE_SHADOW_MERGE",
    "CI_STATE_STARTING",
    "CI_STATE_USER_ACTIVE",
    "CI_VERSION_WDS30",
    "CI_VERSION_WDS40",
    "CI_VERSION_WIN70",
    "DBID",
    "DBKINDENUM",
    "DBKIND_GUID",
    "DBKIND_GUID_NAME",
    "DBKIND_GUID_PROPID",
    "DBKIND_NAME",
    "DBKIND_PGUID_NAME",
    "DBKIND_PGUID_PROPID",
    "DBKIND_PROPID",
    "DBPROP_APPLICATION_NAME",
    "DBPROP_CATALOGLISTID",
    "DBPROP_CI_CATALOG_NAME",
    "DBPROP_CI_DEPTHS",
    "DBPROP_CI_EXCLUDE_SCOPES",
    "DBPROP_CI_INCLUDE_SCOPES",
    "DBPROP_CI_PROVIDER",
    "DBPROP_CI_QUERY_TYPE",
    "DBPROP_CI_SCOPE_FLAGS",
    "DBPROP_CI_SECURITY_ID",
    "DBPROP_CLIENT_CLSID",
    "DBPROP_DEFAULT_EQUALS_BEHAVIOR",
    "DBPROP_DEFERCATALOGVERIFICATION",
    "DBPROP_DEFERNONINDEXEDTRIMMING",
    "DBPROP_DONOTCOMPUTEEXPENSIVEPROPS",
    "DBPROP_ENABLEROWSETEVENTS",
    "DBPROP_FIRSTROWS",
    "DBPROP_FREETEXTANYTERM",
    "DBPROP_FREETEXTUSESTEMMING",
    "DBPROP_GENERATEPARSETREE",
    "DBPROP_GENERICOPTIONS_STRING",
    "DBPROP_IGNORENOISEONLYCLAUSES",
    "DBPROP_IGNORESBRI",
    "DBPROP_MACHINE",
    "DBPROP_USECONTENTINDEX",
    "DBPROP_USEEXTENDEDDBTYPES",
    "DBSETFUNC_ALL",
    "DBSETFUNC_DISTINCT",
    "DBSETFUNC_NONE",
    "FILTERREGION",
    "FILTER_E_ACCESS",
    "FILTER_E_EMBEDDING_UNAVAILABLE",
    "FILTER_E_END_OF_CHUNKS",
    "FILTER_E_LINK_UNAVAILABLE",
    "FILTER_E_NO_MORE_TEXT",
    "FILTER_E_NO_MORE_VALUES",
    "FILTER_E_NO_TEXT",
    "FILTER_E_NO_VALUES",
    "FILTER_E_PASSWORD",
    "FILTER_E_UNKNOWNFORMAT",
    "FILTER_S_LAST_TEXT",
    "FILTER_S_LAST_VALUES",
    "FILTER_W_MONIKER_CLIPPED",
    "FULLPROPSPEC",
    "GENERATE_METHOD_EXACT",
    "GENERATE_METHOD_INFLECT",
    "GENERATE_METHOD_PREFIX",
    "IFILTER_FLAGS",
    "IFILTER_FLAGS_OLE_PROPERTIES",
    "IFILTER_INIT",
    "IFILTER_INIT_APPLY_CRAWL_ATTRIBUTES",
    "IFILTER_INIT_APPLY_INDEX_ATTRIBUTES",
    "IFILTER_INIT_APPLY_OTHER_ATTRIBUTES",
    "IFILTER_INIT_CANON_HYPHENS",
    "IFILTER_INIT_CANON_PARAGRAPHS",
    "IFILTER_INIT_CANON_SPACES",
    "IFILTER_INIT_DISABLE_EMBEDDED",
    "IFILTER_INIT_EMIT_FORMATTING",
    "IFILTER_INIT_FILTER_AGGRESSIVE_BREAK",
    "IFILTER_INIT_FILTER_OWNED_VALUE_OK",
    "IFILTER_INIT_HARD_LINE_BREAKS",
    "IFILTER_INIT_INDEXING_ONLY",
    "IFILTER_INIT_SEARCH_LINKS",
    "IFilter",
    "IPhraseSink",
    "LIFF_FORCE_TEXT_FILTER_FALLBACK",
    "LIFF_IMPLEMENT_TEXT_FILTER_FALLBACK_POLICY",
    "LIFF_LOAD_DEFINED_FILTER",
    "LoadIFilter",
    "LoadIFilterEx",
    "MSIDXSPROP_COMMAND_LOCALE_STRING",
    "MSIDXSPROP_MAX_RANK",
    "MSIDXSPROP_PARSE_TREE",
    "MSIDXSPROP_QUERY_RESTRICTION",
    "MSIDXSPROP_RESULTS_FOUND",
    "MSIDXSPROP_ROWSETQUERYSTATUS",
    "MSIDXSPROP_SAME_SORTORDER_USED",
    "MSIDXSPROP_SERVER_NLSVERSION",
    "MSIDXSPROP_SERVER_NLSVER_DEFINED",
    "MSIDXSPROP_SERVER_VERSION",
    "MSIDXSPROP_SERVER_WINVER_MAJOR",
    "MSIDXSPROP_SERVER_WINVER_MINOR",
    "MSIDXSPROP_WHEREID",
    "NOT_AN_ERROR",
    "PID_FILENAME",
    "PROPID_QUERY_ALL",
    "PROPID_QUERY_HITCOUNT",
    "PROPID_QUERY_LASTSEENTIME",
    "PROPID_QUERY_RANK",
    "PROPID_QUERY_RANKVECTOR",
    "PROPID_QUERY_UNFILTERED",
    "PROPID_QUERY_VIRTUALPATH",
    "PROPID_QUERY_WORKID",
    "PROPID_STG_CONTENTS",
    "PROXIMITY_UNIT_CHAPTER",
    "PROXIMITY_UNIT_PARAGRAPH",
    "PROXIMITY_UNIT_SENTENCE",
    "PROXIMITY_UNIT_WORD",
    "QUERY_DEEP",
    "QUERY_PHYSICAL_PATH",
    "QUERY_SHALLOW",
    "QUERY_VIRTUAL_PATH",
    "SCOPE_FLAG_DEEP",
    "SCOPE_FLAG_INCLUDE",
    "SCOPE_FLAG_MASK",
    "SCOPE_TYPE_MASK",
    "SCOPE_TYPE_VPATH",
    "SCOPE_TYPE_WINPATH",
    "STAT_BUSY",
    "STAT_CHUNK",
    "STAT_COALESCE_COMP_ALL_NOISE",
    "STAT_CONTENT_OUT_OF_DATE",
    "STAT_CONTENT_QUERY_INCOMPLETE",
    "STAT_DONE",
    "STAT_ERROR",
    "STAT_MISSING_PROP_IN_RELDOC",
    "STAT_MISSING_RELDOC",
    "STAT_NOISE_WORDS",
    "STAT_PARTIAL_SCOPE",
    "STAT_REFRESH",
    "STAT_REFRESH_INCOMPLETE",
    "STAT_RELDOC_ACCESS_DENIED",
    "STAT_SHARING_VIOLATION",
    "STAT_TIME_LIMIT_EXCEEDED",
    "VECTOR_RANK_DICE",
    "VECTOR_RANK_INNER",
    "VECTOR_RANK_JACCARD",
    "VECTOR_RANK_MAX",
    "VECTOR_RANK_MIN",
    "WORDREP_BREAK_EOC",
    "WORDREP_BREAK_EOP",
    "WORDREP_BREAK_EOS",
    "WORDREP_BREAK_EOW",
    "WORDREP_BREAK_TYPE",
]
_arch_optional = [
]
