from __future__ import annotations
from ctypes import c_void_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from typing import Generic, TypeVar
K = TypeVar('T')
T = TypeVar('T')
V = TypeVar('V')
TProgress = TypeVar('TProgress')
TResult = TypeVar('TResult')
TSender = TypeVar('TSender')
from Windows import ARCH, MissingType, c_char_p_no, c_wchar_p_no, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head, EasyCastStructure, EasyCastUnion, ComPtr
from Windows._winrt import WinRT_String, winrt_commethod, winrt_mixinmethod, winrt_classmethod, winrt_factorymethod, winrt_activatemethod
import Windows.Win32.System.WinRT
import Windows.UI
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
class Color(EasyCastStructure):
    A: Byte
    R: Byte
    G: Byte
    B: Byte
class ColorHelper(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.UI.ColorHelper'
    @winrt_classmethod
    def ToDisplayName(cls: Windows.UI.IColorHelperStatics2, color: Windows.UI.Color) -> WinRT_String: ...
    @winrt_classmethod
    def FromArgb(cls: Windows.UI.IColorHelperStatics, a: Byte, r: Byte, g: Byte, b: Byte) -> Windows.UI.Color: ...
class Colors(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.UI.Colors'
    @winrt_classmethod
    def get_AliceBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_AntiqueWhite(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Aqua(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Aquamarine(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Azure(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Beige(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Bisque(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Black(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_BlanchedAlmond(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Blue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_BlueViolet(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Brown(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_BurlyWood(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_CadetBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Chartreuse(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Chocolate(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Coral(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_CornflowerBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Cornsilk(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Crimson(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Cyan(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkCyan(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkGoldenrod(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkGray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkKhaki(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkMagenta(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkOliveGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkOrange(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkOrchid(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkRed(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkSalmon(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkSeaGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkSlateBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkSlateGray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkTurquoise(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DarkViolet(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DeepPink(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DeepSkyBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DimGray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_DodgerBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Firebrick(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_FloralWhite(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_ForestGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Fuchsia(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Gainsboro(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_GhostWhite(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Gold(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Goldenrod(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Gray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Green(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_GreenYellow(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Honeydew(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_HotPink(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_IndianRed(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Indigo(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Ivory(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Khaki(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Lavender(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LavenderBlush(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LawnGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LemonChiffon(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightCoral(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightCyan(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightGoldenrodYellow(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightGray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightPink(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightSalmon(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightSeaGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightSkyBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightSlateGray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightSteelBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LightYellow(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Lime(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_LimeGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Linen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Magenta(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Maroon(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumAquamarine(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumOrchid(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumPurple(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumSeaGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumSlateBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumSpringGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumTurquoise(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MediumVioletRed(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MidnightBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MintCream(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_MistyRose(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Moccasin(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_NavajoWhite(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Navy(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_OldLace(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Olive(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_OliveDrab(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Orange(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_OrangeRed(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Orchid(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PaleGoldenrod(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PaleGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PaleTurquoise(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PaleVioletRed(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PapayaWhip(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PeachPuff(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Peru(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Pink(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Plum(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_PowderBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Purple(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Red(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_RosyBrown(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_RoyalBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SaddleBrown(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Salmon(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SandyBrown(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SeaGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SeaShell(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Sienna(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Silver(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SkyBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SlateBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SlateGray(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Snow(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SpringGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_SteelBlue(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Tan(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Teal(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Thistle(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Tomato(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Transparent(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Turquoise(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Violet(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Wheat(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_White(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_WhiteSmoke(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_Yellow(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    @winrt_classmethod
    def get_YellowGreen(cls: Windows.UI.IColorsStatics) -> Windows.UI.Color: ...
    AliceBlue = property(get_AliceBlue, None)
    AntiqueWhite = property(get_AntiqueWhite, None)
    Aqua = property(get_Aqua, None)
    Aquamarine = property(get_Aquamarine, None)
    Azure = property(get_Azure, None)
    Beige = property(get_Beige, None)
    Bisque = property(get_Bisque, None)
    Black = property(get_Black, None)
    BlanchedAlmond = property(get_BlanchedAlmond, None)
    Blue = property(get_Blue, None)
    BlueViolet = property(get_BlueViolet, None)
    Brown = property(get_Brown, None)
    BurlyWood = property(get_BurlyWood, None)
    CadetBlue = property(get_CadetBlue, None)
    Chartreuse = property(get_Chartreuse, None)
    Chocolate = property(get_Chocolate, None)
    Coral = property(get_Coral, None)
    CornflowerBlue = property(get_CornflowerBlue, None)
    Cornsilk = property(get_Cornsilk, None)
    Crimson = property(get_Crimson, None)
    Cyan = property(get_Cyan, None)
    DarkBlue = property(get_DarkBlue, None)
    DarkCyan = property(get_DarkCyan, None)
    DarkGoldenrod = property(get_DarkGoldenrod, None)
    DarkGray = property(get_DarkGray, None)
    DarkGreen = property(get_DarkGreen, None)
    DarkKhaki = property(get_DarkKhaki, None)
    DarkMagenta = property(get_DarkMagenta, None)
    DarkOliveGreen = property(get_DarkOliveGreen, None)
    DarkOrange = property(get_DarkOrange, None)
    DarkOrchid = property(get_DarkOrchid, None)
    DarkRed = property(get_DarkRed, None)
    DarkSalmon = property(get_DarkSalmon, None)
    DarkSeaGreen = property(get_DarkSeaGreen, None)
    DarkSlateBlue = property(get_DarkSlateBlue, None)
    DarkSlateGray = property(get_DarkSlateGray, None)
    DarkTurquoise = property(get_DarkTurquoise, None)
    DarkViolet = property(get_DarkViolet, None)
    DeepPink = property(get_DeepPink, None)
    DeepSkyBlue = property(get_DeepSkyBlue, None)
    DimGray = property(get_DimGray, None)
    DodgerBlue = property(get_DodgerBlue, None)
    Firebrick = property(get_Firebrick, None)
    FloralWhite = property(get_FloralWhite, None)
    ForestGreen = property(get_ForestGreen, None)
    Fuchsia = property(get_Fuchsia, None)
    Gainsboro = property(get_Gainsboro, None)
    GhostWhite = property(get_GhostWhite, None)
    Gold = property(get_Gold, None)
    Goldenrod = property(get_Goldenrod, None)
    Gray = property(get_Gray, None)
    Green = property(get_Green, None)
    GreenYellow = property(get_GreenYellow, None)
    Honeydew = property(get_Honeydew, None)
    HotPink = property(get_HotPink, None)
    IndianRed = property(get_IndianRed, None)
    Indigo = property(get_Indigo, None)
    Ivory = property(get_Ivory, None)
    Khaki = property(get_Khaki, None)
    Lavender = property(get_Lavender, None)
    LavenderBlush = property(get_LavenderBlush, None)
    LawnGreen = property(get_LawnGreen, None)
    LemonChiffon = property(get_LemonChiffon, None)
    LightBlue = property(get_LightBlue, None)
    LightCoral = property(get_LightCoral, None)
    LightCyan = property(get_LightCyan, None)
    LightGoldenrodYellow = property(get_LightGoldenrodYellow, None)
    LightGreen = property(get_LightGreen, None)
    LightGray = property(get_LightGray, None)
    LightPink = property(get_LightPink, None)
    LightSalmon = property(get_LightSalmon, None)
    LightSeaGreen = property(get_LightSeaGreen, None)
    LightSkyBlue = property(get_LightSkyBlue, None)
    LightSlateGray = property(get_LightSlateGray, None)
    LightSteelBlue = property(get_LightSteelBlue, None)
    LightYellow = property(get_LightYellow, None)
    Lime = property(get_Lime, None)
    LimeGreen = property(get_LimeGreen, None)
    Linen = property(get_Linen, None)
    Magenta = property(get_Magenta, None)
    Maroon = property(get_Maroon, None)
    MediumAquamarine = property(get_MediumAquamarine, None)
    MediumBlue = property(get_MediumBlue, None)
    MediumOrchid = property(get_MediumOrchid, None)
    MediumPurple = property(get_MediumPurple, None)
    MediumSeaGreen = property(get_MediumSeaGreen, None)
    MediumSlateBlue = property(get_MediumSlateBlue, None)
    MediumSpringGreen = property(get_MediumSpringGreen, None)
    MediumTurquoise = property(get_MediumTurquoise, None)
    MediumVioletRed = property(get_MediumVioletRed, None)
    MidnightBlue = property(get_MidnightBlue, None)
    MintCream = property(get_MintCream, None)
    MistyRose = property(get_MistyRose, None)
    Moccasin = property(get_Moccasin, None)
    NavajoWhite = property(get_NavajoWhite, None)
    Navy = property(get_Navy, None)
    OldLace = property(get_OldLace, None)
    Olive = property(get_Olive, None)
    OliveDrab = property(get_OliveDrab, None)
    Orange = property(get_Orange, None)
    OrangeRed = property(get_OrangeRed, None)
    Orchid = property(get_Orchid, None)
    PaleGoldenrod = property(get_PaleGoldenrod, None)
    PaleGreen = property(get_PaleGreen, None)
    PaleTurquoise = property(get_PaleTurquoise, None)
    PaleVioletRed = property(get_PaleVioletRed, None)
    PapayaWhip = property(get_PapayaWhip, None)
    PeachPuff = property(get_PeachPuff, None)
    Peru = property(get_Peru, None)
    Pink = property(get_Pink, None)
    Plum = property(get_Plum, None)
    PowderBlue = property(get_PowderBlue, None)
    Purple = property(get_Purple, None)
    Red = property(get_Red, None)
    RosyBrown = property(get_RosyBrown, None)
    RoyalBlue = property(get_RoyalBlue, None)
    SaddleBrown = property(get_SaddleBrown, None)
    Salmon = property(get_Salmon, None)
    SandyBrown = property(get_SandyBrown, None)
    SeaGreen = property(get_SeaGreen, None)
    SeaShell = property(get_SeaShell, None)
    Sienna = property(get_Sienna, None)
    Silver = property(get_Silver, None)
    SkyBlue = property(get_SkyBlue, None)
    SlateBlue = property(get_SlateBlue, None)
    SlateGray = property(get_SlateGray, None)
    Snow = property(get_Snow, None)
    SpringGreen = property(get_SpringGreen, None)
    SteelBlue = property(get_SteelBlue, None)
    Tan = property(get_Tan, None)
    Teal = property(get_Teal, None)
    Thistle = property(get_Thistle, None)
    Tomato = property(get_Tomato, None)
    Transparent = property(get_Transparent, None)
    Turquoise = property(get_Turquoise, None)
    Violet = property(get_Violet, None)
    Wheat = property(get_Wheat, None)
    White = property(get_White, None)
    WhiteSmoke = property(get_WhiteSmoke, None)
    Yellow = property(get_Yellow, None)
    YellowGreen = property(get_YellowGreen, None)
class IColorHelper(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('193cfbe7-65c7-4540-ad-08-62-83-ba-76-87-9a')
class IColorHelperStatics(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('8504dbea-fb6a-4144-a6-c2-33-49-9c-92-84-f5')
    @winrt_commethod(6)
    def FromArgb(self, a: Byte, r: Byte, g: Byte, b: Byte) -> Windows.UI.Color: ...
class IColorHelperStatics2(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('24d9af02-6eb0-4b94-85-5c-fc-f0-81-8d-9a-16')
    @winrt_commethod(6)
    def ToDisplayName(self, color: Windows.UI.Color) -> WinRT_String: ...
class IColors(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('9b8c9326-4ca6-4ce5-89-94-9e-ff-65-ca-bd-cc')
class IColorsStatics(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('cff52e04-cca6-4614-a1-7e-75-49-10-c8-4a-99')
    @winrt_commethod(6)
    def get_AliceBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(7)
    def get_AntiqueWhite(self) -> Windows.UI.Color: ...
    @winrt_commethod(8)
    def get_Aqua(self) -> Windows.UI.Color: ...
    @winrt_commethod(9)
    def get_Aquamarine(self) -> Windows.UI.Color: ...
    @winrt_commethod(10)
    def get_Azure(self) -> Windows.UI.Color: ...
    @winrt_commethod(11)
    def get_Beige(self) -> Windows.UI.Color: ...
    @winrt_commethod(12)
    def get_Bisque(self) -> Windows.UI.Color: ...
    @winrt_commethod(13)
    def get_Black(self) -> Windows.UI.Color: ...
    @winrt_commethod(14)
    def get_BlanchedAlmond(self) -> Windows.UI.Color: ...
    @winrt_commethod(15)
    def get_Blue(self) -> Windows.UI.Color: ...
    @winrt_commethod(16)
    def get_BlueViolet(self) -> Windows.UI.Color: ...
    @winrt_commethod(17)
    def get_Brown(self) -> Windows.UI.Color: ...
    @winrt_commethod(18)
    def get_BurlyWood(self) -> Windows.UI.Color: ...
    @winrt_commethod(19)
    def get_CadetBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(20)
    def get_Chartreuse(self) -> Windows.UI.Color: ...
    @winrt_commethod(21)
    def get_Chocolate(self) -> Windows.UI.Color: ...
    @winrt_commethod(22)
    def get_Coral(self) -> Windows.UI.Color: ...
    @winrt_commethod(23)
    def get_CornflowerBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(24)
    def get_Cornsilk(self) -> Windows.UI.Color: ...
    @winrt_commethod(25)
    def get_Crimson(self) -> Windows.UI.Color: ...
    @winrt_commethod(26)
    def get_Cyan(self) -> Windows.UI.Color: ...
    @winrt_commethod(27)
    def get_DarkBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(28)
    def get_DarkCyan(self) -> Windows.UI.Color: ...
    @winrt_commethod(29)
    def get_DarkGoldenrod(self) -> Windows.UI.Color: ...
    @winrt_commethod(30)
    def get_DarkGray(self) -> Windows.UI.Color: ...
    @winrt_commethod(31)
    def get_DarkGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(32)
    def get_DarkKhaki(self) -> Windows.UI.Color: ...
    @winrt_commethod(33)
    def get_DarkMagenta(self) -> Windows.UI.Color: ...
    @winrt_commethod(34)
    def get_DarkOliveGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(35)
    def get_DarkOrange(self) -> Windows.UI.Color: ...
    @winrt_commethod(36)
    def get_DarkOrchid(self) -> Windows.UI.Color: ...
    @winrt_commethod(37)
    def get_DarkRed(self) -> Windows.UI.Color: ...
    @winrt_commethod(38)
    def get_DarkSalmon(self) -> Windows.UI.Color: ...
    @winrt_commethod(39)
    def get_DarkSeaGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(40)
    def get_DarkSlateBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(41)
    def get_DarkSlateGray(self) -> Windows.UI.Color: ...
    @winrt_commethod(42)
    def get_DarkTurquoise(self) -> Windows.UI.Color: ...
    @winrt_commethod(43)
    def get_DarkViolet(self) -> Windows.UI.Color: ...
    @winrt_commethod(44)
    def get_DeepPink(self) -> Windows.UI.Color: ...
    @winrt_commethod(45)
    def get_DeepSkyBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(46)
    def get_DimGray(self) -> Windows.UI.Color: ...
    @winrt_commethod(47)
    def get_DodgerBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(48)
    def get_Firebrick(self) -> Windows.UI.Color: ...
    @winrt_commethod(49)
    def get_FloralWhite(self) -> Windows.UI.Color: ...
    @winrt_commethod(50)
    def get_ForestGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(51)
    def get_Fuchsia(self) -> Windows.UI.Color: ...
    @winrt_commethod(52)
    def get_Gainsboro(self) -> Windows.UI.Color: ...
    @winrt_commethod(53)
    def get_GhostWhite(self) -> Windows.UI.Color: ...
    @winrt_commethod(54)
    def get_Gold(self) -> Windows.UI.Color: ...
    @winrt_commethod(55)
    def get_Goldenrod(self) -> Windows.UI.Color: ...
    @winrt_commethod(56)
    def get_Gray(self) -> Windows.UI.Color: ...
    @winrt_commethod(57)
    def get_Green(self) -> Windows.UI.Color: ...
    @winrt_commethod(58)
    def get_GreenYellow(self) -> Windows.UI.Color: ...
    @winrt_commethod(59)
    def get_Honeydew(self) -> Windows.UI.Color: ...
    @winrt_commethod(60)
    def get_HotPink(self) -> Windows.UI.Color: ...
    @winrt_commethod(61)
    def get_IndianRed(self) -> Windows.UI.Color: ...
    @winrt_commethod(62)
    def get_Indigo(self) -> Windows.UI.Color: ...
    @winrt_commethod(63)
    def get_Ivory(self) -> Windows.UI.Color: ...
    @winrt_commethod(64)
    def get_Khaki(self) -> Windows.UI.Color: ...
    @winrt_commethod(65)
    def get_Lavender(self) -> Windows.UI.Color: ...
    @winrt_commethod(66)
    def get_LavenderBlush(self) -> Windows.UI.Color: ...
    @winrt_commethod(67)
    def get_LawnGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(68)
    def get_LemonChiffon(self) -> Windows.UI.Color: ...
    @winrt_commethod(69)
    def get_LightBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(70)
    def get_LightCoral(self) -> Windows.UI.Color: ...
    @winrt_commethod(71)
    def get_LightCyan(self) -> Windows.UI.Color: ...
    @winrt_commethod(72)
    def get_LightGoldenrodYellow(self) -> Windows.UI.Color: ...
    @winrt_commethod(73)
    def get_LightGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(74)
    def get_LightGray(self) -> Windows.UI.Color: ...
    @winrt_commethod(75)
    def get_LightPink(self) -> Windows.UI.Color: ...
    @winrt_commethod(76)
    def get_LightSalmon(self) -> Windows.UI.Color: ...
    @winrt_commethod(77)
    def get_LightSeaGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(78)
    def get_LightSkyBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(79)
    def get_LightSlateGray(self) -> Windows.UI.Color: ...
    @winrt_commethod(80)
    def get_LightSteelBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(81)
    def get_LightYellow(self) -> Windows.UI.Color: ...
    @winrt_commethod(82)
    def get_Lime(self) -> Windows.UI.Color: ...
    @winrt_commethod(83)
    def get_LimeGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(84)
    def get_Linen(self) -> Windows.UI.Color: ...
    @winrt_commethod(85)
    def get_Magenta(self) -> Windows.UI.Color: ...
    @winrt_commethod(86)
    def get_Maroon(self) -> Windows.UI.Color: ...
    @winrt_commethod(87)
    def get_MediumAquamarine(self) -> Windows.UI.Color: ...
    @winrt_commethod(88)
    def get_MediumBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(89)
    def get_MediumOrchid(self) -> Windows.UI.Color: ...
    @winrt_commethod(90)
    def get_MediumPurple(self) -> Windows.UI.Color: ...
    @winrt_commethod(91)
    def get_MediumSeaGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(92)
    def get_MediumSlateBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(93)
    def get_MediumSpringGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(94)
    def get_MediumTurquoise(self) -> Windows.UI.Color: ...
    @winrt_commethod(95)
    def get_MediumVioletRed(self) -> Windows.UI.Color: ...
    @winrt_commethod(96)
    def get_MidnightBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(97)
    def get_MintCream(self) -> Windows.UI.Color: ...
    @winrt_commethod(98)
    def get_MistyRose(self) -> Windows.UI.Color: ...
    @winrt_commethod(99)
    def get_Moccasin(self) -> Windows.UI.Color: ...
    @winrt_commethod(100)
    def get_NavajoWhite(self) -> Windows.UI.Color: ...
    @winrt_commethod(101)
    def get_Navy(self) -> Windows.UI.Color: ...
    @winrt_commethod(102)
    def get_OldLace(self) -> Windows.UI.Color: ...
    @winrt_commethod(103)
    def get_Olive(self) -> Windows.UI.Color: ...
    @winrt_commethod(104)
    def get_OliveDrab(self) -> Windows.UI.Color: ...
    @winrt_commethod(105)
    def get_Orange(self) -> Windows.UI.Color: ...
    @winrt_commethod(106)
    def get_OrangeRed(self) -> Windows.UI.Color: ...
    @winrt_commethod(107)
    def get_Orchid(self) -> Windows.UI.Color: ...
    @winrt_commethod(108)
    def get_PaleGoldenrod(self) -> Windows.UI.Color: ...
    @winrt_commethod(109)
    def get_PaleGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(110)
    def get_PaleTurquoise(self) -> Windows.UI.Color: ...
    @winrt_commethod(111)
    def get_PaleVioletRed(self) -> Windows.UI.Color: ...
    @winrt_commethod(112)
    def get_PapayaWhip(self) -> Windows.UI.Color: ...
    @winrt_commethod(113)
    def get_PeachPuff(self) -> Windows.UI.Color: ...
    @winrt_commethod(114)
    def get_Peru(self) -> Windows.UI.Color: ...
    @winrt_commethod(115)
    def get_Pink(self) -> Windows.UI.Color: ...
    @winrt_commethod(116)
    def get_Plum(self) -> Windows.UI.Color: ...
    @winrt_commethod(117)
    def get_PowderBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(118)
    def get_Purple(self) -> Windows.UI.Color: ...
    @winrt_commethod(119)
    def get_Red(self) -> Windows.UI.Color: ...
    @winrt_commethod(120)
    def get_RosyBrown(self) -> Windows.UI.Color: ...
    @winrt_commethod(121)
    def get_RoyalBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(122)
    def get_SaddleBrown(self) -> Windows.UI.Color: ...
    @winrt_commethod(123)
    def get_Salmon(self) -> Windows.UI.Color: ...
    @winrt_commethod(124)
    def get_SandyBrown(self) -> Windows.UI.Color: ...
    @winrt_commethod(125)
    def get_SeaGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(126)
    def get_SeaShell(self) -> Windows.UI.Color: ...
    @winrt_commethod(127)
    def get_Sienna(self) -> Windows.UI.Color: ...
    @winrt_commethod(128)
    def get_Silver(self) -> Windows.UI.Color: ...
    @winrt_commethod(129)
    def get_SkyBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(130)
    def get_SlateBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(131)
    def get_SlateGray(self) -> Windows.UI.Color: ...
    @winrt_commethod(132)
    def get_Snow(self) -> Windows.UI.Color: ...
    @winrt_commethod(133)
    def get_SpringGreen(self) -> Windows.UI.Color: ...
    @winrt_commethod(134)
    def get_SteelBlue(self) -> Windows.UI.Color: ...
    @winrt_commethod(135)
    def get_Tan(self) -> Windows.UI.Color: ...
    @winrt_commethod(136)
    def get_Teal(self) -> Windows.UI.Color: ...
    @winrt_commethod(137)
    def get_Thistle(self) -> Windows.UI.Color: ...
    @winrt_commethod(138)
    def get_Tomato(self) -> Windows.UI.Color: ...
    @winrt_commethod(139)
    def get_Transparent(self) -> Windows.UI.Color: ...
    @winrt_commethod(140)
    def get_Turquoise(self) -> Windows.UI.Color: ...
    @winrt_commethod(141)
    def get_Violet(self) -> Windows.UI.Color: ...
    @winrt_commethod(142)
    def get_Wheat(self) -> Windows.UI.Color: ...
    @winrt_commethod(143)
    def get_White(self) -> Windows.UI.Color: ...
    @winrt_commethod(144)
    def get_WhiteSmoke(self) -> Windows.UI.Color: ...
    @winrt_commethod(145)
    def get_Yellow(self) -> Windows.UI.Color: ...
    @winrt_commethod(146)
    def get_YellowGreen(self) -> Windows.UI.Color: ...
    AliceBlue = property(get_AliceBlue, None)
    AntiqueWhite = property(get_AntiqueWhite, None)
    Aqua = property(get_Aqua, None)
    Aquamarine = property(get_Aquamarine, None)
    Azure = property(get_Azure, None)
    Beige = property(get_Beige, None)
    Bisque = property(get_Bisque, None)
    Black = property(get_Black, None)
    BlanchedAlmond = property(get_BlanchedAlmond, None)
    Blue = property(get_Blue, None)
    BlueViolet = property(get_BlueViolet, None)
    Brown = property(get_Brown, None)
    BurlyWood = property(get_BurlyWood, None)
    CadetBlue = property(get_CadetBlue, None)
    Chartreuse = property(get_Chartreuse, None)
    Chocolate = property(get_Chocolate, None)
    Coral = property(get_Coral, None)
    CornflowerBlue = property(get_CornflowerBlue, None)
    Cornsilk = property(get_Cornsilk, None)
    Crimson = property(get_Crimson, None)
    Cyan = property(get_Cyan, None)
    DarkBlue = property(get_DarkBlue, None)
    DarkCyan = property(get_DarkCyan, None)
    DarkGoldenrod = property(get_DarkGoldenrod, None)
    DarkGray = property(get_DarkGray, None)
    DarkGreen = property(get_DarkGreen, None)
    DarkKhaki = property(get_DarkKhaki, None)
    DarkMagenta = property(get_DarkMagenta, None)
    DarkOliveGreen = property(get_DarkOliveGreen, None)
    DarkOrange = property(get_DarkOrange, None)
    DarkOrchid = property(get_DarkOrchid, None)
    DarkRed = property(get_DarkRed, None)
    DarkSalmon = property(get_DarkSalmon, None)
    DarkSeaGreen = property(get_DarkSeaGreen, None)
    DarkSlateBlue = property(get_DarkSlateBlue, None)
    DarkSlateGray = property(get_DarkSlateGray, None)
    DarkTurquoise = property(get_DarkTurquoise, None)
    DarkViolet = property(get_DarkViolet, None)
    DeepPink = property(get_DeepPink, None)
    DeepSkyBlue = property(get_DeepSkyBlue, None)
    DimGray = property(get_DimGray, None)
    DodgerBlue = property(get_DodgerBlue, None)
    Firebrick = property(get_Firebrick, None)
    FloralWhite = property(get_FloralWhite, None)
    ForestGreen = property(get_ForestGreen, None)
    Fuchsia = property(get_Fuchsia, None)
    Gainsboro = property(get_Gainsboro, None)
    GhostWhite = property(get_GhostWhite, None)
    Gold = property(get_Gold, None)
    Goldenrod = property(get_Goldenrod, None)
    Gray = property(get_Gray, None)
    Green = property(get_Green, None)
    GreenYellow = property(get_GreenYellow, None)
    Honeydew = property(get_Honeydew, None)
    HotPink = property(get_HotPink, None)
    IndianRed = property(get_IndianRed, None)
    Indigo = property(get_Indigo, None)
    Ivory = property(get_Ivory, None)
    Khaki = property(get_Khaki, None)
    Lavender = property(get_Lavender, None)
    LavenderBlush = property(get_LavenderBlush, None)
    LawnGreen = property(get_LawnGreen, None)
    LemonChiffon = property(get_LemonChiffon, None)
    LightBlue = property(get_LightBlue, None)
    LightCoral = property(get_LightCoral, None)
    LightCyan = property(get_LightCyan, None)
    LightGoldenrodYellow = property(get_LightGoldenrodYellow, None)
    LightGreen = property(get_LightGreen, None)
    LightGray = property(get_LightGray, None)
    LightPink = property(get_LightPink, None)
    LightSalmon = property(get_LightSalmon, None)
    LightSeaGreen = property(get_LightSeaGreen, None)
    LightSkyBlue = property(get_LightSkyBlue, None)
    LightSlateGray = property(get_LightSlateGray, None)
    LightSteelBlue = property(get_LightSteelBlue, None)
    LightYellow = property(get_LightYellow, None)
    Lime = property(get_Lime, None)
    LimeGreen = property(get_LimeGreen, None)
    Linen = property(get_Linen, None)
    Magenta = property(get_Magenta, None)
    Maroon = property(get_Maroon, None)
    MediumAquamarine = property(get_MediumAquamarine, None)
    MediumBlue = property(get_MediumBlue, None)
    MediumOrchid = property(get_MediumOrchid, None)
    MediumPurple = property(get_MediumPurple, None)
    MediumSeaGreen = property(get_MediumSeaGreen, None)
    MediumSlateBlue = property(get_MediumSlateBlue, None)
    MediumSpringGreen = property(get_MediumSpringGreen, None)
    MediumTurquoise = property(get_MediumTurquoise, None)
    MediumVioletRed = property(get_MediumVioletRed, None)
    MidnightBlue = property(get_MidnightBlue, None)
    MintCream = property(get_MintCream, None)
    MistyRose = property(get_MistyRose, None)
    Moccasin = property(get_Moccasin, None)
    NavajoWhite = property(get_NavajoWhite, None)
    Navy = property(get_Navy, None)
    OldLace = property(get_OldLace, None)
    Olive = property(get_Olive, None)
    OliveDrab = property(get_OliveDrab, None)
    Orange = property(get_Orange, None)
    OrangeRed = property(get_OrangeRed, None)
    Orchid = property(get_Orchid, None)
    PaleGoldenrod = property(get_PaleGoldenrod, None)
    PaleGreen = property(get_PaleGreen, None)
    PaleTurquoise = property(get_PaleTurquoise, None)
    PaleVioletRed = property(get_PaleVioletRed, None)
    PapayaWhip = property(get_PapayaWhip, None)
    PeachPuff = property(get_PeachPuff, None)
    Peru = property(get_Peru, None)
    Pink = property(get_Pink, None)
    Plum = property(get_Plum, None)
    PowderBlue = property(get_PowderBlue, None)
    Purple = property(get_Purple, None)
    Red = property(get_Red, None)
    RosyBrown = property(get_RosyBrown, None)
    RoyalBlue = property(get_RoyalBlue, None)
    SaddleBrown = property(get_SaddleBrown, None)
    Salmon = property(get_Salmon, None)
    SandyBrown = property(get_SandyBrown, None)
    SeaGreen = property(get_SeaGreen, None)
    SeaShell = property(get_SeaShell, None)
    Sienna = property(get_Sienna, None)
    Silver = property(get_Silver, None)
    SkyBlue = property(get_SkyBlue, None)
    SlateBlue = property(get_SlateBlue, None)
    SlateGray = property(get_SlateGray, None)
    Snow = property(get_Snow, None)
    SpringGreen = property(get_SpringGreen, None)
    SteelBlue = property(get_SteelBlue, None)
    Tan = property(get_Tan, None)
    Teal = property(get_Teal, None)
    Thistle = property(get_Thistle, None)
    Tomato = property(get_Tomato, None)
    Transparent = property(get_Transparent, None)
    Turquoise = property(get_Turquoise, None)
    Violet = property(get_Violet, None)
    Wheat = property(get_Wheat, None)
    White = property(get_White, None)
    WhiteSmoke = property(get_WhiteSmoke, None)
    Yellow = property(get_Yellow, None)
    YellowGreen = property(get_YellowGreen, None)
class IUIContentRoot(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('1dfcbac6-b36b-5cb9-9b-c5-2b-7a-0e-dd-c3-78')
    @winrt_commethod(6)
    def get_UIContext(self) -> Windows.UI.UIContext: ...
    UIContext = property(get_UIContext, None)
class IUIContext(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _iid_ = Guid('bb5cfacd-5bd8-59d0-a5-9e-1c-17-a4-d6-d2-43')
class UIContentRoot(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.UI.UIContentRoot'
    @winrt_mixinmethod
    def get_UIContext(self: Windows.UI.IUIContentRoot) -> Windows.UI.UIContext: ...
    UIContext = property(get_UIContext, None)
class UIContext(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.UI.UIContext'
class WindowId(EasyCastStructure):
    Value: UInt64
make_head(_module, 'Color')
make_head(_module, 'ColorHelper')
make_head(_module, 'Colors')
make_head(_module, 'IColorHelper')
make_head(_module, 'IColorHelperStatics')
make_head(_module, 'IColorHelperStatics2')
make_head(_module, 'IColors')
make_head(_module, 'IColorsStatics')
make_head(_module, 'IUIContentRoot')
make_head(_module, 'IUIContext')
make_head(_module, 'UIContentRoot')
make_head(_module, 'UIContext')
make_head(_module, 'WindowId')
