from win32more import *
import win32more.Foundation
import win32more.Graphics.Direct3D
import win32more.System.Com

import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        f = globals()[f"_define_{name}"]
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, f())
    return getattr(_module, name)
def __dir__():
    return __all__
D3D_FL9_1_REQ_TEXTURE1D_U_DIMENSION = 2048
D3D_FL9_3_REQ_TEXTURE1D_U_DIMENSION = 4096
D3D_FL9_1_REQ_TEXTURE2D_U_OR_V_DIMENSION = 2048
D3D_FL9_3_REQ_TEXTURE2D_U_OR_V_DIMENSION = 4096
D3D_FL9_1_REQ_TEXTURECUBE_DIMENSION = 512
D3D_FL9_3_REQ_TEXTURECUBE_DIMENSION = 4096
D3D_FL9_1_REQ_TEXTURE3D_U_V_OR_W_DIMENSION = 256
D3D_FL9_1_DEFAULT_MAX_ANISOTROPY = 2
D3D_FL9_1_IA_PRIMITIVE_MAX_COUNT = 65535
D3D_FL9_2_IA_PRIMITIVE_MAX_COUNT = 1048575
D3D_FL9_1_SIMULTANEOUS_RENDER_TARGET_COUNT = 1
D3D_FL9_3_SIMULTANEOUS_RENDER_TARGET_COUNT = 4
D3D_FL9_1_MAX_TEXTURE_REPEAT = 128
D3D_FL9_2_MAX_TEXTURE_REPEAT = 2048
D3D_FL9_3_MAX_TEXTURE_REPEAT = 8192
D3D_SHADER_FEATURE_DOUBLES = 1
D3D_SHADER_FEATURE_COMPUTE_SHADERS_PLUS_RAW_AND_STRUCTURED_BUFFERS_VIA_SHADER_4_X = 2
D3D_SHADER_FEATURE_UAVS_AT_EVERY_STAGE = 4
D3D_SHADER_FEATURE_64_UAVS = 8
D3D_SHADER_FEATURE_MINIMUM_PRECISION = 16
D3D_SHADER_FEATURE_11_1_DOUBLE_EXTENSIONS = 32
D3D_SHADER_FEATURE_11_1_SHADER_EXTENSIONS = 64
D3D_SHADER_FEATURE_LEVEL_9_COMPARISON_FILTERING = 128
D3D_SHADER_FEATURE_TILED_RESOURCES = 256
D3D_SHADER_FEATURE_STENCIL_REF = 512
D3D_SHADER_FEATURE_INNER_COVERAGE = 1024
D3D_SHADER_FEATURE_TYPED_UAV_LOAD_ADDITIONAL_FORMATS = 2048
D3D_SHADER_FEATURE_ROVS = 4096
D3D_SHADER_FEATURE_VIEWPORT_AND_RT_ARRAY_INDEX_FROM_ANY_SHADER_FEEDING_RASTERIZER = 8192
D3D_SHADER_FEATURE_WAVE_OPS = 16384
D3D_SHADER_FEATURE_INT64_OPS = 32768
D3D_SHADER_FEATURE_VIEW_ID = 65536
D3D_SHADER_FEATURE_BARYCENTRICS = 131072
D3D_SHADER_FEATURE_NATIVE_16BIT_OPS = 262144
D3D_SHADER_FEATURE_SHADING_RATE = 524288
D3D_SHADER_FEATURE_RAYTRACING_TIER_1_1 = 1048576
D3D_SHADER_FEATURE_SAMPLER_FEEDBACK = 2097152
D3D_SHADER_FEATURE_ATOMIC_INT64_ON_TYPED_RESOURCE = 4194304
D3D_SHADER_FEATURE_ATOMIC_INT64_ON_GROUP_SHARED = 8388608
D3D_SHADER_FEATURE_DERIVATIVES_IN_MESH_AND_AMPLIFICATION_SHADERS = 16777216
D3D_SHADER_FEATURE_RESOURCE_DESCRIPTOR_HEAP_INDEXING = 33554432
D3D_SHADER_FEATURE_SAMPLER_DESCRIPTOR_HEAP_INDEXING = 67108864
D3D_SHADER_FEATURE_WAVE_MMA = 134217728
D3D_SHADER_FEATURE_ATOMIC_INT64_ON_DESCRIPTOR_HEAP_RESOURCE = 268435456
WKPDID_D3DDebugObjectName = '429b8c22-9188-4b0c-8742-acb0bf85c200'
WKPDID_D3DDebugObjectNameW = '4cca5fd8-921f-42c8-8566-70caf2a9b741'
WKPDID_CommentStringW = 'd0149dc0-90e8-4ec8-8144-e900ad266bb2'
WKPDID_D3D12UniqueObjectId = '1b39de15-ec04-4bae-ba4d-8cef79fc04c1'
D3D_COMPONENT_MASK_X = 1
D3D_COMPONENT_MASK_Y = 2
D3D_COMPONENT_MASK_Z = 4
D3D_COMPONENT_MASK_W = 8
D3D_TEXTURE_LAYOUT_ROW_MAJOR = 'b5dc234f-72bb-4bec-9705-8cf258df6b6c'
D3D_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE = '4c0f29e3-3f5f-4d35-84c9-bc0983b62c28'
D3D_DRIVER_TYPE = Int32
D3D_DRIVER_TYPE_UNKNOWN = 0
D3D_DRIVER_TYPE_HARDWARE = 1
D3D_DRIVER_TYPE_REFERENCE = 2
D3D_DRIVER_TYPE_NULL = 3
D3D_DRIVER_TYPE_SOFTWARE = 4
D3D_DRIVER_TYPE_WARP = 5
D3D_FEATURE_LEVEL = Int32
D3D_FEATURE_LEVEL_1_0_CORE = 4096
D3D_FEATURE_LEVEL_9_1 = 37120
D3D_FEATURE_LEVEL_9_2 = 37376
D3D_FEATURE_LEVEL_9_3 = 37632
D3D_FEATURE_LEVEL_10_0 = 40960
D3D_FEATURE_LEVEL_10_1 = 41216
D3D_FEATURE_LEVEL_11_0 = 45056
D3D_FEATURE_LEVEL_11_1 = 45312
D3D_FEATURE_LEVEL_12_0 = 49152
D3D_FEATURE_LEVEL_12_1 = 49408
D3D_FEATURE_LEVEL_12_2 = 49664
D3D_PRIMITIVE_TOPOLOGY = Int32
D3D_PRIMITIVE_TOPOLOGY_UNDEFINED = 0
D3D_PRIMITIVE_TOPOLOGY_POINTLIST = 1
D3D_PRIMITIVE_TOPOLOGY_LINELIST = 2
D3D_PRIMITIVE_TOPOLOGY_LINESTRIP = 3
D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4
D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5
D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10
D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11
D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12
D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13
D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = 33
D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = 34
D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = 35
D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = 36
D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = 37
D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = 38
D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = 39
D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = 40
D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = 41
D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42
D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43
D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44
D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45
D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46
D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47
D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48
D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49
D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50
D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51
D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52
D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53
D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54
D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55
D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56
D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57
D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58
D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59
D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60
D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61
D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62
D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63
D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64
D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED = 0
D3D10_PRIMITIVE_TOPOLOGY_POINTLIST = 1
D3D10_PRIMITIVE_TOPOLOGY_LINELIST = 2
D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP = 3
D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4
D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5
D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10
D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11
D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12
D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13
D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED = 0
D3D11_PRIMITIVE_TOPOLOGY_POINTLIST = 1
D3D11_PRIMITIVE_TOPOLOGY_LINELIST = 2
D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP = 3
D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4
D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5
D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10
D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11
D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12
D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13
D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST = 33
D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST = 34
D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST = 35
D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST = 36
D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST = 37
D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST = 38
D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST = 39
D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST = 40
D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST = 41
D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST = 42
D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST = 43
D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST = 44
D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST = 45
D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST = 46
D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST = 47
D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST = 48
D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST = 49
D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST = 50
D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST = 51
D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST = 52
D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST = 53
D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST = 54
D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST = 55
D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST = 56
D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST = 57
D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST = 58
D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST = 59
D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST = 60
D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST = 61
D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST = 62
D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST = 63
D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST = 64
D3D_PRIMITIVE = Int32
D3D_PRIMITIVE_UNDEFINED = 0
D3D_PRIMITIVE_POINT = 1
D3D_PRIMITIVE_LINE = 2
D3D_PRIMITIVE_TRIANGLE = 3
D3D_PRIMITIVE_LINE_ADJ = 6
D3D_PRIMITIVE_TRIANGLE_ADJ = 7
D3D_PRIMITIVE_1_CONTROL_POINT_PATCH = 8
D3D_PRIMITIVE_2_CONTROL_POINT_PATCH = 9
D3D_PRIMITIVE_3_CONTROL_POINT_PATCH = 10
D3D_PRIMITIVE_4_CONTROL_POINT_PATCH = 11
D3D_PRIMITIVE_5_CONTROL_POINT_PATCH = 12
D3D_PRIMITIVE_6_CONTROL_POINT_PATCH = 13
D3D_PRIMITIVE_7_CONTROL_POINT_PATCH = 14
D3D_PRIMITIVE_8_CONTROL_POINT_PATCH = 15
D3D_PRIMITIVE_9_CONTROL_POINT_PATCH = 16
D3D_PRIMITIVE_10_CONTROL_POINT_PATCH = 17
D3D_PRIMITIVE_11_CONTROL_POINT_PATCH = 18
D3D_PRIMITIVE_12_CONTROL_POINT_PATCH = 19
D3D_PRIMITIVE_13_CONTROL_POINT_PATCH = 20
D3D_PRIMITIVE_14_CONTROL_POINT_PATCH = 21
D3D_PRIMITIVE_15_CONTROL_POINT_PATCH = 22
D3D_PRIMITIVE_16_CONTROL_POINT_PATCH = 23
D3D_PRIMITIVE_17_CONTROL_POINT_PATCH = 24
D3D_PRIMITIVE_18_CONTROL_POINT_PATCH = 25
D3D_PRIMITIVE_19_CONTROL_POINT_PATCH = 26
D3D_PRIMITIVE_20_CONTROL_POINT_PATCH = 27
D3D_PRIMITIVE_21_CONTROL_POINT_PATCH = 28
D3D_PRIMITIVE_22_CONTROL_POINT_PATCH = 29
D3D_PRIMITIVE_23_CONTROL_POINT_PATCH = 30
D3D_PRIMITIVE_24_CONTROL_POINT_PATCH = 31
D3D_PRIMITIVE_25_CONTROL_POINT_PATCH = 32
D3D_PRIMITIVE_26_CONTROL_POINT_PATCH = 33
D3D_PRIMITIVE_27_CONTROL_POINT_PATCH = 34
D3D_PRIMITIVE_28_CONTROL_POINT_PATCH = 35
D3D_PRIMITIVE_29_CONTROL_POINT_PATCH = 36
D3D_PRIMITIVE_30_CONTROL_POINT_PATCH = 37
D3D_PRIMITIVE_31_CONTROL_POINT_PATCH = 38
D3D_PRIMITIVE_32_CONTROL_POINT_PATCH = 39
D3D10_PRIMITIVE_UNDEFINED = 0
D3D10_PRIMITIVE_POINT = 1
D3D10_PRIMITIVE_LINE = 2
D3D10_PRIMITIVE_TRIANGLE = 3
D3D10_PRIMITIVE_LINE_ADJ = 6
D3D10_PRIMITIVE_TRIANGLE_ADJ = 7
D3D11_PRIMITIVE_UNDEFINED = 0
D3D11_PRIMITIVE_POINT = 1
D3D11_PRIMITIVE_LINE = 2
D3D11_PRIMITIVE_TRIANGLE = 3
D3D11_PRIMITIVE_LINE_ADJ = 6
D3D11_PRIMITIVE_TRIANGLE_ADJ = 7
D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH = 8
D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH = 9
D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH = 10
D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH = 11
D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH = 12
D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH = 13
D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH = 14
D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH = 15
D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH = 16
D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH = 17
D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH = 18
D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH = 19
D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH = 20
D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH = 21
D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH = 22
D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH = 23
D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH = 24
D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH = 25
D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH = 26
D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH = 27
D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH = 28
D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH = 29
D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH = 30
D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH = 31
D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH = 32
D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH = 33
D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH = 34
D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH = 35
D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH = 36
D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH = 37
D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH = 38
D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH = 39
D3D_SRV_DIMENSION = Int32
D3D_SRV_DIMENSION_UNKNOWN = 0
D3D_SRV_DIMENSION_BUFFER = 1
D3D_SRV_DIMENSION_TEXTURE1D = 2
D3D_SRV_DIMENSION_TEXTURE1DARRAY = 3
D3D_SRV_DIMENSION_TEXTURE2D = 4
D3D_SRV_DIMENSION_TEXTURE2DARRAY = 5
D3D_SRV_DIMENSION_TEXTURE2DMS = 6
D3D_SRV_DIMENSION_TEXTURE2DMSARRAY = 7
D3D_SRV_DIMENSION_TEXTURE3D = 8
D3D_SRV_DIMENSION_TEXTURECUBE = 9
D3D_SRV_DIMENSION_TEXTURECUBEARRAY = 10
D3D_SRV_DIMENSION_BUFFEREX = 11
D3D10_SRV_DIMENSION_UNKNOWN = 0
D3D10_SRV_DIMENSION_BUFFER = 1
D3D10_SRV_DIMENSION_TEXTURE1D = 2
D3D10_SRV_DIMENSION_TEXTURE1DARRAY = 3
D3D10_SRV_DIMENSION_TEXTURE2D = 4
D3D10_SRV_DIMENSION_TEXTURE2DARRAY = 5
D3D10_SRV_DIMENSION_TEXTURE2DMS = 6
D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY = 7
D3D10_SRV_DIMENSION_TEXTURE3D = 8
D3D10_SRV_DIMENSION_TEXTURECUBE = 9
D3D10_1_SRV_DIMENSION_UNKNOWN = 0
D3D10_1_SRV_DIMENSION_BUFFER = 1
D3D10_1_SRV_DIMENSION_TEXTURE1D = 2
D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY = 3
D3D10_1_SRV_DIMENSION_TEXTURE2D = 4
D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY = 5
D3D10_1_SRV_DIMENSION_TEXTURE2DMS = 6
D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY = 7
D3D10_1_SRV_DIMENSION_TEXTURE3D = 8
D3D10_1_SRV_DIMENSION_TEXTURECUBE = 9
D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY = 10
D3D11_SRV_DIMENSION_UNKNOWN = 0
D3D11_SRV_DIMENSION_BUFFER = 1
D3D11_SRV_DIMENSION_TEXTURE1D = 2
D3D11_SRV_DIMENSION_TEXTURE1DARRAY = 3
D3D11_SRV_DIMENSION_TEXTURE2D = 4
D3D11_SRV_DIMENSION_TEXTURE2DARRAY = 5
D3D11_SRV_DIMENSION_TEXTURE2DMS = 6
D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY = 7
D3D11_SRV_DIMENSION_TEXTURE3D = 8
D3D11_SRV_DIMENSION_TEXTURECUBE = 9
D3D11_SRV_DIMENSION_TEXTURECUBEARRAY = 10
D3D11_SRV_DIMENSION_BUFFEREX = 11
def _define_D3D_SHADER_MACRO_head():
    class D3D_SHADER_MACRO(Structure):
        pass
    return D3D_SHADER_MACRO
def _define_D3D_SHADER_MACRO():
    D3D_SHADER_MACRO = win32more.Graphics.Direct3D.D3D_SHADER_MACRO_head
    D3D_SHADER_MACRO._fields_ = [
        ("Name", win32more.Foundation.PSTR),
        ("Definition", win32more.Foundation.PSTR),
    ]
    return D3D_SHADER_MACRO
def _define_ID3DBlob_head():
    class ID3DBlob(win32more.System.Com.IUnknown_head):
        Guid = Guid('8ba5fb08-5195-40e2-ac58-0d989c3a0102')
    return ID3DBlob
def _define_ID3DBlob():
    ID3DBlob = win32more.Graphics.Direct3D.ID3DBlob_head
    ID3DBlob.GetBufferPointer = COMMETHOD(WINFUNCTYPE(c_void_p, use_last_error=False)(3, 'GetBufferPointer', ()))
    ID3DBlob.GetBufferSize = COMMETHOD(WINFUNCTYPE(UIntPtr, use_last_error=False)(4, 'GetBufferSize', ()))
    win32more.System.Com.IUnknown
    return ID3DBlob
def _define_PFN_DESTRUCTION_CALLBACK():
    return CFUNCTYPE(Void,c_void_p, use_last_error=False)
def _define_ID3DDestructionNotifier_head():
    class ID3DDestructionNotifier(win32more.System.Com.IUnknown_head):
        Guid = Guid('a06eb39a-50da-425b-8c31-4eecd6c270f3')
    return ID3DDestructionNotifier
def _define_ID3DDestructionNotifier():
    ID3DDestructionNotifier = win32more.Graphics.Direct3D.ID3DDestructionNotifier_head
    ID3DDestructionNotifier.RegisterDestructionCallback = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.Graphics.Direct3D.PFN_DESTRUCTION_CALLBACK,c_void_p,POINTER(UInt32), use_last_error=False)(3, 'RegisterDestructionCallback', ((1, 'callbackFn'),(1, 'pData'),(1, 'pCallbackID'),)))
    ID3DDestructionNotifier.UnregisterDestructionCallback = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,UInt32, use_last_error=False)(4, 'UnregisterDestructionCallback', ((1, 'callbackID'),)))
    win32more.System.Com.IUnknown
    return ID3DDestructionNotifier
D3D_INCLUDE_TYPE = Int32
D3D_INCLUDE_LOCAL = 0
D3D_INCLUDE_SYSTEM = 1
D3D10_INCLUDE_LOCAL = 0
D3D10_INCLUDE_SYSTEM = 1
D3D_INCLUDE_FORCE_DWORD = 2147483647
def _define_ID3DInclude_head():
    class ID3DInclude(c_void_p):
        Guid = Guid(None)
    return ID3DInclude
def _define_ID3DInclude():
    ID3DInclude = win32more.Graphics.Direct3D.ID3DInclude_head
    ID3DInclude.Open = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.Graphics.Direct3D.D3D_INCLUDE_TYPE,win32more.Foundation.PSTR,c_void_p,POINTER(c_void_p),POINTER(UInt32), use_last_error=False)(0, 'Open', ((1, 'IncludeType'),(1, 'pFileName'),(1, 'pParentData'),(1, 'ppData'),(1, 'pBytes'),)))
    ID3DInclude.Close = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,c_void_p, use_last_error=False)(1, 'Close', ((1, 'pData'),)))
    return ID3DInclude
D3D_SHADER_VARIABLE_CLASS = Int32
D3D_SVC_SCALAR = 0
D3D_SVC_VECTOR = 1
D3D_SVC_MATRIX_ROWS = 2
D3D_SVC_MATRIX_COLUMNS = 3
D3D_SVC_OBJECT = 4
D3D_SVC_STRUCT = 5
D3D_SVC_INTERFACE_CLASS = 6
D3D_SVC_INTERFACE_POINTER = 7
D3D10_SVC_SCALAR = 0
D3D10_SVC_VECTOR = 1
D3D10_SVC_MATRIX_ROWS = 2
D3D10_SVC_MATRIX_COLUMNS = 3
D3D10_SVC_OBJECT = 4
D3D10_SVC_STRUCT = 5
D3D11_SVC_INTERFACE_CLASS = 6
D3D11_SVC_INTERFACE_POINTER = 7
D3D_SVC_FORCE_DWORD = 2147483647
D3D_SHADER_VARIABLE_FLAGS = Int32
D3D_SVF_USERPACKED = 1
D3D_SVF_USED = 2
D3D_SVF_INTERFACE_POINTER = 4
D3D_SVF_INTERFACE_PARAMETER = 8
D3D10_SVF_USERPACKED = 1
D3D10_SVF_USED = 2
D3D11_SVF_INTERFACE_POINTER = 4
D3D11_SVF_INTERFACE_PARAMETER = 8
D3D_SVF_FORCE_DWORD = 2147483647
D3D_SHADER_VARIABLE_TYPE = Int32
D3D_SVT_VOID = 0
D3D_SVT_BOOL = 1
D3D_SVT_INT = 2
D3D_SVT_FLOAT = 3
D3D_SVT_STRING = 4
D3D_SVT_TEXTURE = 5
D3D_SVT_TEXTURE1D = 6
D3D_SVT_TEXTURE2D = 7
D3D_SVT_TEXTURE3D = 8
D3D_SVT_TEXTURECUBE = 9
D3D_SVT_SAMPLER = 10
D3D_SVT_SAMPLER1D = 11
D3D_SVT_SAMPLER2D = 12
D3D_SVT_SAMPLER3D = 13
D3D_SVT_SAMPLERCUBE = 14
D3D_SVT_PIXELSHADER = 15
D3D_SVT_VERTEXSHADER = 16
D3D_SVT_PIXELFRAGMENT = 17
D3D_SVT_VERTEXFRAGMENT = 18
D3D_SVT_UINT = 19
D3D_SVT_UINT8 = 20
D3D_SVT_GEOMETRYSHADER = 21
D3D_SVT_RASTERIZER = 22
D3D_SVT_DEPTHSTENCIL = 23
D3D_SVT_BLEND = 24
D3D_SVT_BUFFER = 25
D3D_SVT_CBUFFER = 26
D3D_SVT_TBUFFER = 27
D3D_SVT_TEXTURE1DARRAY = 28
D3D_SVT_TEXTURE2DARRAY = 29
D3D_SVT_RENDERTARGETVIEW = 30
D3D_SVT_DEPTHSTENCILVIEW = 31
D3D_SVT_TEXTURE2DMS = 32
D3D_SVT_TEXTURE2DMSARRAY = 33
D3D_SVT_TEXTURECUBEARRAY = 34
D3D_SVT_HULLSHADER = 35
D3D_SVT_DOMAINSHADER = 36
D3D_SVT_INTERFACE_POINTER = 37
D3D_SVT_COMPUTESHADER = 38
D3D_SVT_DOUBLE = 39
D3D_SVT_RWTEXTURE1D = 40
D3D_SVT_RWTEXTURE1DARRAY = 41
D3D_SVT_RWTEXTURE2D = 42
D3D_SVT_RWTEXTURE2DARRAY = 43
D3D_SVT_RWTEXTURE3D = 44
D3D_SVT_RWBUFFER = 45
D3D_SVT_BYTEADDRESS_BUFFER = 46
D3D_SVT_RWBYTEADDRESS_BUFFER = 47
D3D_SVT_STRUCTURED_BUFFER = 48
D3D_SVT_RWSTRUCTURED_BUFFER = 49
D3D_SVT_APPEND_STRUCTURED_BUFFER = 50
D3D_SVT_CONSUME_STRUCTURED_BUFFER = 51
D3D_SVT_MIN8FLOAT = 52
D3D_SVT_MIN10FLOAT = 53
D3D_SVT_MIN16FLOAT = 54
D3D_SVT_MIN12INT = 55
D3D_SVT_MIN16INT = 56
D3D_SVT_MIN16UINT = 57
D3D_SVT_INT16 = 58
D3D_SVT_UINT16 = 59
D3D_SVT_FLOAT16 = 60
D3D_SVT_INT64 = 61
D3D_SVT_UINT64 = 62
D3D10_SVT_VOID = 0
D3D10_SVT_BOOL = 1
D3D10_SVT_INT = 2
D3D10_SVT_FLOAT = 3
D3D10_SVT_STRING = 4
D3D10_SVT_TEXTURE = 5
D3D10_SVT_TEXTURE1D = 6
D3D10_SVT_TEXTURE2D = 7
D3D10_SVT_TEXTURE3D = 8
D3D10_SVT_TEXTURECUBE = 9
D3D10_SVT_SAMPLER = 10
D3D10_SVT_SAMPLER1D = 11
D3D10_SVT_SAMPLER2D = 12
D3D10_SVT_SAMPLER3D = 13
D3D10_SVT_SAMPLERCUBE = 14
D3D10_SVT_PIXELSHADER = 15
D3D10_SVT_VERTEXSHADER = 16
D3D10_SVT_PIXELFRAGMENT = 17
D3D10_SVT_VERTEXFRAGMENT = 18
D3D10_SVT_UINT = 19
D3D10_SVT_UINT8 = 20
D3D10_SVT_GEOMETRYSHADER = 21
D3D10_SVT_RASTERIZER = 22
D3D10_SVT_DEPTHSTENCIL = 23
D3D10_SVT_BLEND = 24
D3D10_SVT_BUFFER = 25
D3D10_SVT_CBUFFER = 26
D3D10_SVT_TBUFFER = 27
D3D10_SVT_TEXTURE1DARRAY = 28
D3D10_SVT_TEXTURE2DARRAY = 29
D3D10_SVT_RENDERTARGETVIEW = 30
D3D10_SVT_DEPTHSTENCILVIEW = 31
D3D10_SVT_TEXTURE2DMS = 32
D3D10_SVT_TEXTURE2DMSARRAY = 33
D3D10_SVT_TEXTURECUBEARRAY = 34
D3D11_SVT_HULLSHADER = 35
D3D11_SVT_DOMAINSHADER = 36
D3D11_SVT_INTERFACE_POINTER = 37
D3D11_SVT_COMPUTESHADER = 38
D3D11_SVT_DOUBLE = 39
D3D11_SVT_RWTEXTURE1D = 40
D3D11_SVT_RWTEXTURE1DARRAY = 41
D3D11_SVT_RWTEXTURE2D = 42
D3D11_SVT_RWTEXTURE2DARRAY = 43
D3D11_SVT_RWTEXTURE3D = 44
D3D11_SVT_RWBUFFER = 45
D3D11_SVT_BYTEADDRESS_BUFFER = 46
D3D11_SVT_RWBYTEADDRESS_BUFFER = 47
D3D11_SVT_STRUCTURED_BUFFER = 48
D3D11_SVT_RWSTRUCTURED_BUFFER = 49
D3D11_SVT_APPEND_STRUCTURED_BUFFER = 50
D3D11_SVT_CONSUME_STRUCTURED_BUFFER = 51
D3D_SVT_FORCE_DWORD = 2147483647
D3D_SHADER_INPUT_FLAGS = Int32
D3D_SIF_USERPACKED = 1
D3D_SIF_COMPARISON_SAMPLER = 2
D3D_SIF_TEXTURE_COMPONENT_0 = 4
D3D_SIF_TEXTURE_COMPONENT_1 = 8
D3D_SIF_TEXTURE_COMPONENTS = 12
D3D_SIF_UNUSED = 16
D3D10_SIF_USERPACKED = 1
D3D10_SIF_COMPARISON_SAMPLER = 2
D3D10_SIF_TEXTURE_COMPONENT_0 = 4
D3D10_SIF_TEXTURE_COMPONENT_1 = 8
D3D10_SIF_TEXTURE_COMPONENTS = 12
D3D_SIF_FORCE_DWORD = 2147483647
D3D_SHADER_INPUT_TYPE = Int32
D3D_SIT_CBUFFER = 0
D3D_SIT_TBUFFER = 1
D3D_SIT_TEXTURE = 2
D3D_SIT_SAMPLER = 3
D3D_SIT_UAV_RWTYPED = 4
D3D_SIT_STRUCTURED = 5
D3D_SIT_UAV_RWSTRUCTURED = 6
D3D_SIT_BYTEADDRESS = 7
D3D_SIT_UAV_RWBYTEADDRESS = 8
D3D_SIT_UAV_APPEND_STRUCTURED = 9
D3D_SIT_UAV_CONSUME_STRUCTURED = 10
D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER = 11
D3D_SIT_RTACCELERATIONSTRUCTURE = 12
D3D_SIT_UAV_FEEDBACKTEXTURE = 13
D3D10_SIT_CBUFFER = 0
D3D10_SIT_TBUFFER = 1
D3D10_SIT_TEXTURE = 2
D3D10_SIT_SAMPLER = 3
D3D11_SIT_UAV_RWTYPED = 4
D3D11_SIT_STRUCTURED = 5
D3D11_SIT_UAV_RWSTRUCTURED = 6
D3D11_SIT_BYTEADDRESS = 7
D3D11_SIT_UAV_RWBYTEADDRESS = 8
D3D11_SIT_UAV_APPEND_STRUCTURED = 9
D3D11_SIT_UAV_CONSUME_STRUCTURED = 10
D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER = 11
D3D_SHADER_CBUFFER_FLAGS = Int32
D3D_CBF_USERPACKED = 1
D3D10_CBF_USERPACKED = 1
D3D_CBF_FORCE_DWORD = 2147483647
D3D_CBUFFER_TYPE = Int32
D3D_CT_CBUFFER = 0
D3D_CT_TBUFFER = 1
D3D_CT_INTERFACE_POINTERS = 2
D3D_CT_RESOURCE_BIND_INFO = 3
D3D10_CT_CBUFFER = 0
D3D10_CT_TBUFFER = 1
D3D11_CT_CBUFFER = 0
D3D11_CT_TBUFFER = 1
D3D11_CT_INTERFACE_POINTERS = 2
D3D11_CT_RESOURCE_BIND_INFO = 3
D3D_NAME = Int32
D3D_NAME_UNDEFINED = 0
D3D_NAME_POSITION = 1
D3D_NAME_CLIP_DISTANCE = 2
D3D_NAME_CULL_DISTANCE = 3
D3D_NAME_RENDER_TARGET_ARRAY_INDEX = 4
D3D_NAME_VIEWPORT_ARRAY_INDEX = 5
D3D_NAME_VERTEX_ID = 6
D3D_NAME_PRIMITIVE_ID = 7
D3D_NAME_INSTANCE_ID = 8
D3D_NAME_IS_FRONT_FACE = 9
D3D_NAME_SAMPLE_INDEX = 10
D3D_NAME_FINAL_QUAD_EDGE_TESSFACTOR = 11
D3D_NAME_FINAL_QUAD_INSIDE_TESSFACTOR = 12
D3D_NAME_FINAL_TRI_EDGE_TESSFACTOR = 13
D3D_NAME_FINAL_TRI_INSIDE_TESSFACTOR = 14
D3D_NAME_FINAL_LINE_DETAIL_TESSFACTOR = 15
D3D_NAME_FINAL_LINE_DENSITY_TESSFACTOR = 16
D3D_NAME_BARYCENTRICS = 23
D3D_NAME_SHADINGRATE = 24
D3D_NAME_CULLPRIMITIVE = 25
D3D_NAME_TARGET = 64
D3D_NAME_DEPTH = 65
D3D_NAME_COVERAGE = 66
D3D_NAME_DEPTH_GREATER_EQUAL = 67
D3D_NAME_DEPTH_LESS_EQUAL = 68
D3D_NAME_STENCIL_REF = 69
D3D_NAME_INNER_COVERAGE = 70
D3D10_NAME_UNDEFINED = 0
D3D10_NAME_POSITION = 1
D3D10_NAME_CLIP_DISTANCE = 2
D3D10_NAME_CULL_DISTANCE = 3
D3D10_NAME_RENDER_TARGET_ARRAY_INDEX = 4
D3D10_NAME_VIEWPORT_ARRAY_INDEX = 5
D3D10_NAME_VERTEX_ID = 6
D3D10_NAME_PRIMITIVE_ID = 7
D3D10_NAME_INSTANCE_ID = 8
D3D10_NAME_IS_FRONT_FACE = 9
D3D10_NAME_SAMPLE_INDEX = 10
D3D10_NAME_TARGET = 64
D3D10_NAME_DEPTH = 65
D3D10_NAME_COVERAGE = 66
D3D11_NAME_FINAL_QUAD_EDGE_TESSFACTOR = 11
D3D11_NAME_FINAL_QUAD_INSIDE_TESSFACTOR = 12
D3D11_NAME_FINAL_TRI_EDGE_TESSFACTOR = 13
D3D11_NAME_FINAL_TRI_INSIDE_TESSFACTOR = 14
D3D11_NAME_FINAL_LINE_DETAIL_TESSFACTOR = 15
D3D11_NAME_FINAL_LINE_DENSITY_TESSFACTOR = 16
D3D11_NAME_DEPTH_GREATER_EQUAL = 67
D3D11_NAME_DEPTH_LESS_EQUAL = 68
D3D11_NAME_STENCIL_REF = 69
D3D11_NAME_INNER_COVERAGE = 70
D3D12_NAME_BARYCENTRICS = 23
D3D12_NAME_SHADINGRATE = 24
D3D12_NAME_CULLPRIMITIVE = 25
D3D_RESOURCE_RETURN_TYPE = Int32
D3D_RETURN_TYPE_UNORM = 1
D3D_RETURN_TYPE_SNORM = 2
D3D_RETURN_TYPE_SINT = 3
D3D_RETURN_TYPE_UINT = 4
D3D_RETURN_TYPE_FLOAT = 5
D3D_RETURN_TYPE_MIXED = 6
D3D_RETURN_TYPE_DOUBLE = 7
D3D_RETURN_TYPE_CONTINUED = 8
D3D10_RETURN_TYPE_UNORM = 1
D3D10_RETURN_TYPE_SNORM = 2
D3D10_RETURN_TYPE_SINT = 3
D3D10_RETURN_TYPE_UINT = 4
D3D10_RETURN_TYPE_FLOAT = 5
D3D10_RETURN_TYPE_MIXED = 6
D3D11_RETURN_TYPE_UNORM = 1
D3D11_RETURN_TYPE_SNORM = 2
D3D11_RETURN_TYPE_SINT = 3
D3D11_RETURN_TYPE_UINT = 4
D3D11_RETURN_TYPE_FLOAT = 5
D3D11_RETURN_TYPE_MIXED = 6
D3D11_RETURN_TYPE_DOUBLE = 7
D3D11_RETURN_TYPE_CONTINUED = 8
D3D_REGISTER_COMPONENT_TYPE = Int32
D3D_REGISTER_COMPONENT_UNKNOWN = 0
D3D_REGISTER_COMPONENT_UINT32 = 1
D3D_REGISTER_COMPONENT_SINT32 = 2
D3D_REGISTER_COMPONENT_FLOAT32 = 3
D3D10_REGISTER_COMPONENT_UNKNOWN = 0
D3D10_REGISTER_COMPONENT_UINT32 = 1
D3D10_REGISTER_COMPONENT_SINT32 = 2
D3D10_REGISTER_COMPONENT_FLOAT32 = 3
D3D_TESSELLATOR_DOMAIN = Int32
D3D_TESSELLATOR_DOMAIN_UNDEFINED = 0
D3D_TESSELLATOR_DOMAIN_ISOLINE = 1
D3D_TESSELLATOR_DOMAIN_TRI = 2
D3D_TESSELLATOR_DOMAIN_QUAD = 3
D3D11_TESSELLATOR_DOMAIN_UNDEFINED = 0
D3D11_TESSELLATOR_DOMAIN_ISOLINE = 1
D3D11_TESSELLATOR_DOMAIN_TRI = 2
D3D11_TESSELLATOR_DOMAIN_QUAD = 3
D3D_TESSELLATOR_PARTITIONING = Int32
D3D_TESSELLATOR_PARTITIONING_UNDEFINED = 0
D3D_TESSELLATOR_PARTITIONING_INTEGER = 1
D3D_TESSELLATOR_PARTITIONING_POW2 = 2
D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD = 3
D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN = 4
D3D11_TESSELLATOR_PARTITIONING_UNDEFINED = 0
D3D11_TESSELLATOR_PARTITIONING_INTEGER = 1
D3D11_TESSELLATOR_PARTITIONING_POW2 = 2
D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD = 3
D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN = 4
D3D_TESSELLATOR_OUTPUT_PRIMITIVE = Int32
D3D_TESSELLATOR_OUTPUT_UNDEFINED = 0
D3D_TESSELLATOR_OUTPUT_POINT = 1
D3D_TESSELLATOR_OUTPUT_LINE = 2
D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW = 3
D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW = 4
D3D11_TESSELLATOR_OUTPUT_UNDEFINED = 0
D3D11_TESSELLATOR_OUTPUT_POINT = 1
D3D11_TESSELLATOR_OUTPUT_LINE = 2
D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW = 3
D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW = 4
D3D_MIN_PRECISION = Int32
D3D_MIN_PRECISION_DEFAULT = 0
D3D_MIN_PRECISION_FLOAT_16 = 1
D3D_MIN_PRECISION_FLOAT_2_8 = 2
D3D_MIN_PRECISION_RESERVED = 3
D3D_MIN_PRECISION_SINT_16 = 4
D3D_MIN_PRECISION_UINT_16 = 5
D3D_MIN_PRECISION_ANY_16 = 240
D3D_MIN_PRECISION_ANY_10 = 241
D3D_INTERPOLATION_MODE = Int32
D3D_INTERPOLATION_UNDEFINED = 0
D3D_INTERPOLATION_CONSTANT = 1
D3D_INTERPOLATION_LINEAR = 2
D3D_INTERPOLATION_LINEAR_CENTROID = 3
D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE = 4
D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID = 5
D3D_INTERPOLATION_LINEAR_SAMPLE = 6
D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE = 7
D3D_PARAMETER_FLAGS = Int32
D3D_PF_NONE = 0
D3D_PF_IN = 1
D3D_PF_OUT = 2
D3D_PF_FORCE_DWORD = 2147483647
def _define_D3DVECTOR_head():
    class D3DVECTOR(Structure):
        pass
    return D3DVECTOR
def _define_D3DVECTOR():
    D3DVECTOR = win32more.Graphics.Direct3D.D3DVECTOR_head
    D3DVECTOR._fields_ = [
        ("x", Single),
        ("y", Single),
        ("z", Single),
    ]
    return D3DVECTOR
def _define_D3DMATRIX_head():
    class D3DMATRIX(Structure):
        pass
    return D3DMATRIX
def _define_D3DMATRIX():
    D3DMATRIX = win32more.Graphics.Direct3D.D3DMATRIX_head
    class D3DMATRIX__Anonymous_e__Union(Union):
        pass
    class D3DMATRIX__Anonymous_e__Union__Anonymous_e__Struct(Structure):
        pass
    D3DMATRIX__Anonymous_e__Union__Anonymous_e__Struct._fields_ = [
        ("_11", Single),
        ("_12", Single),
        ("_13", Single),
        ("_14", Single),
        ("_21", Single),
        ("_22", Single),
        ("_23", Single),
        ("_24", Single),
        ("_31", Single),
        ("_32", Single),
        ("_33", Single),
        ("_34", Single),
        ("_41", Single),
        ("_42", Single),
        ("_43", Single),
        ("_44", Single),
    ]
    D3DMATRIX__Anonymous_e__Union._anonymous_ = [
        'Anonymous',
    ]
    D3DMATRIX__Anonymous_e__Union._fields_ = [
        ("Anonymous", D3DMATRIX__Anonymous_e__Union__Anonymous_e__Struct),
        ("m", Single * 16),
    ]
    D3DMATRIX._anonymous_ = [
        'Anonymous',
    ]
    D3DMATRIX._fields_ = [
        ("Anonymous", D3DMATRIX__Anonymous_e__Union),
    ]
    return D3DMATRIX
__all__ = [
    "D3D_FL9_1_REQ_TEXTURE1D_U_DIMENSION",
    "D3D_FL9_3_REQ_TEXTURE1D_U_DIMENSION",
    "D3D_FL9_1_REQ_TEXTURE2D_U_OR_V_DIMENSION",
    "D3D_FL9_3_REQ_TEXTURE2D_U_OR_V_DIMENSION",
    "D3D_FL9_1_REQ_TEXTURECUBE_DIMENSION",
    "D3D_FL9_3_REQ_TEXTURECUBE_DIMENSION",
    "D3D_FL9_1_REQ_TEXTURE3D_U_V_OR_W_DIMENSION",
    "D3D_FL9_1_DEFAULT_MAX_ANISOTROPY",
    "D3D_FL9_1_IA_PRIMITIVE_MAX_COUNT",
    "D3D_FL9_2_IA_PRIMITIVE_MAX_COUNT",
    "D3D_FL9_1_SIMULTANEOUS_RENDER_TARGET_COUNT",
    "D3D_FL9_3_SIMULTANEOUS_RENDER_TARGET_COUNT",
    "D3D_FL9_1_MAX_TEXTURE_REPEAT",
    "D3D_FL9_2_MAX_TEXTURE_REPEAT",
    "D3D_FL9_3_MAX_TEXTURE_REPEAT",
    "D3D_SHADER_FEATURE_DOUBLES",
    "D3D_SHADER_FEATURE_COMPUTE_SHADERS_PLUS_RAW_AND_STRUCTURED_BUFFERS_VIA_SHADER_4_X",
    "D3D_SHADER_FEATURE_UAVS_AT_EVERY_STAGE",
    "D3D_SHADER_FEATURE_64_UAVS",
    "D3D_SHADER_FEATURE_MINIMUM_PRECISION",
    "D3D_SHADER_FEATURE_11_1_DOUBLE_EXTENSIONS",
    "D3D_SHADER_FEATURE_11_1_SHADER_EXTENSIONS",
    "D3D_SHADER_FEATURE_LEVEL_9_COMPARISON_FILTERING",
    "D3D_SHADER_FEATURE_TILED_RESOURCES",
    "D3D_SHADER_FEATURE_STENCIL_REF",
    "D3D_SHADER_FEATURE_INNER_COVERAGE",
    "D3D_SHADER_FEATURE_TYPED_UAV_LOAD_ADDITIONAL_FORMATS",
    "D3D_SHADER_FEATURE_ROVS",
    "D3D_SHADER_FEATURE_VIEWPORT_AND_RT_ARRAY_INDEX_FROM_ANY_SHADER_FEEDING_RASTERIZER",
    "D3D_SHADER_FEATURE_WAVE_OPS",
    "D3D_SHADER_FEATURE_INT64_OPS",
    "D3D_SHADER_FEATURE_VIEW_ID",
    "D3D_SHADER_FEATURE_BARYCENTRICS",
    "D3D_SHADER_FEATURE_NATIVE_16BIT_OPS",
    "D3D_SHADER_FEATURE_SHADING_RATE",
    "D3D_SHADER_FEATURE_RAYTRACING_TIER_1_1",
    "D3D_SHADER_FEATURE_SAMPLER_FEEDBACK",
    "D3D_SHADER_FEATURE_ATOMIC_INT64_ON_TYPED_RESOURCE",
    "D3D_SHADER_FEATURE_ATOMIC_INT64_ON_GROUP_SHARED",
    "D3D_SHADER_FEATURE_DERIVATIVES_IN_MESH_AND_AMPLIFICATION_SHADERS",
    "D3D_SHADER_FEATURE_RESOURCE_DESCRIPTOR_HEAP_INDEXING",
    "D3D_SHADER_FEATURE_SAMPLER_DESCRIPTOR_HEAP_INDEXING",
    "D3D_SHADER_FEATURE_WAVE_MMA",
    "D3D_SHADER_FEATURE_ATOMIC_INT64_ON_DESCRIPTOR_HEAP_RESOURCE",
    "WKPDID_D3DDebugObjectName",
    "WKPDID_D3DDebugObjectNameW",
    "WKPDID_CommentStringW",
    "WKPDID_D3D12UniqueObjectId",
    "D3D_COMPONENT_MASK_X",
    "D3D_COMPONENT_MASK_Y",
    "D3D_COMPONENT_MASK_Z",
    "D3D_COMPONENT_MASK_W",
    "D3D_TEXTURE_LAYOUT_ROW_MAJOR",
    "D3D_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE",
    "D3D_DRIVER_TYPE",
    "D3D_DRIVER_TYPE_UNKNOWN",
    "D3D_DRIVER_TYPE_HARDWARE",
    "D3D_DRIVER_TYPE_REFERENCE",
    "D3D_DRIVER_TYPE_NULL",
    "D3D_DRIVER_TYPE_SOFTWARE",
    "D3D_DRIVER_TYPE_WARP",
    "D3D_FEATURE_LEVEL",
    "D3D_FEATURE_LEVEL_1_0_CORE",
    "D3D_FEATURE_LEVEL_9_1",
    "D3D_FEATURE_LEVEL_9_2",
    "D3D_FEATURE_LEVEL_9_3",
    "D3D_FEATURE_LEVEL_10_0",
    "D3D_FEATURE_LEVEL_10_1",
    "D3D_FEATURE_LEVEL_11_0",
    "D3D_FEATURE_LEVEL_11_1",
    "D3D_FEATURE_LEVEL_12_0",
    "D3D_FEATURE_LEVEL_12_1",
    "D3D_FEATURE_LEVEL_12_2",
    "D3D_PRIMITIVE_TOPOLOGY",
    "D3D_PRIMITIVE_TOPOLOGY_UNDEFINED",
    "D3D_PRIMITIVE_TOPOLOGY_POINTLIST",
    "D3D_PRIMITIVE_TOPOLOGY_LINELIST",
    "D3D_PRIMITIVE_TOPOLOGY_LINESTRIP",
    "D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST",
    "D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP",
    "D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ",
    "D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ",
    "D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ",
    "D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ",
    "D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST",
    "D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED",
    "D3D10_PRIMITIVE_TOPOLOGY_POINTLIST",
    "D3D10_PRIMITIVE_TOPOLOGY_LINELIST",
    "D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP",
    "D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST",
    "D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP",
    "D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ",
    "D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ",
    "D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ",
    "D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ",
    "D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED",
    "D3D11_PRIMITIVE_TOPOLOGY_POINTLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_LINELIST",
    "D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP",
    "D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST",
    "D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP",
    "D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ",
    "D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ",
    "D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ",
    "D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ",
    "D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST",
    "D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST",
    "D3D_PRIMITIVE",
    "D3D_PRIMITIVE_UNDEFINED",
    "D3D_PRIMITIVE_POINT",
    "D3D_PRIMITIVE_LINE",
    "D3D_PRIMITIVE_TRIANGLE",
    "D3D_PRIMITIVE_LINE_ADJ",
    "D3D_PRIMITIVE_TRIANGLE_ADJ",
    "D3D_PRIMITIVE_1_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_2_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_3_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_4_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_5_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_6_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_7_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_8_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_9_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_10_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_11_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_12_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_13_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_14_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_15_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_16_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_17_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_18_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_19_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_20_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_21_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_22_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_23_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_24_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_25_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_26_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_27_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_28_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_29_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_30_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_31_CONTROL_POINT_PATCH",
    "D3D_PRIMITIVE_32_CONTROL_POINT_PATCH",
    "D3D10_PRIMITIVE_UNDEFINED",
    "D3D10_PRIMITIVE_POINT",
    "D3D10_PRIMITIVE_LINE",
    "D3D10_PRIMITIVE_TRIANGLE",
    "D3D10_PRIMITIVE_LINE_ADJ",
    "D3D10_PRIMITIVE_TRIANGLE_ADJ",
    "D3D11_PRIMITIVE_UNDEFINED",
    "D3D11_PRIMITIVE_POINT",
    "D3D11_PRIMITIVE_LINE",
    "D3D11_PRIMITIVE_TRIANGLE",
    "D3D11_PRIMITIVE_LINE_ADJ",
    "D3D11_PRIMITIVE_TRIANGLE_ADJ",
    "D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH",
    "D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH",
    "D3D_SRV_DIMENSION",
    "D3D_SRV_DIMENSION_UNKNOWN",
    "D3D_SRV_DIMENSION_BUFFER",
    "D3D_SRV_DIMENSION_TEXTURE1D",
    "D3D_SRV_DIMENSION_TEXTURE1DARRAY",
    "D3D_SRV_DIMENSION_TEXTURE2D",
    "D3D_SRV_DIMENSION_TEXTURE2DARRAY",
    "D3D_SRV_DIMENSION_TEXTURE2DMS",
    "D3D_SRV_DIMENSION_TEXTURE2DMSARRAY",
    "D3D_SRV_DIMENSION_TEXTURE3D",
    "D3D_SRV_DIMENSION_TEXTURECUBE",
    "D3D_SRV_DIMENSION_TEXTURECUBEARRAY",
    "D3D_SRV_DIMENSION_BUFFEREX",
    "D3D10_SRV_DIMENSION_UNKNOWN",
    "D3D10_SRV_DIMENSION_BUFFER",
    "D3D10_SRV_DIMENSION_TEXTURE1D",
    "D3D10_SRV_DIMENSION_TEXTURE1DARRAY",
    "D3D10_SRV_DIMENSION_TEXTURE2D",
    "D3D10_SRV_DIMENSION_TEXTURE2DARRAY",
    "D3D10_SRV_DIMENSION_TEXTURE2DMS",
    "D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY",
    "D3D10_SRV_DIMENSION_TEXTURE3D",
    "D3D10_SRV_DIMENSION_TEXTURECUBE",
    "D3D10_1_SRV_DIMENSION_UNKNOWN",
    "D3D10_1_SRV_DIMENSION_BUFFER",
    "D3D10_1_SRV_DIMENSION_TEXTURE1D",
    "D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY",
    "D3D10_1_SRV_DIMENSION_TEXTURE2D",
    "D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY",
    "D3D10_1_SRV_DIMENSION_TEXTURE2DMS",
    "D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY",
    "D3D10_1_SRV_DIMENSION_TEXTURE3D",
    "D3D10_1_SRV_DIMENSION_TEXTURECUBE",
    "D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY",
    "D3D11_SRV_DIMENSION_UNKNOWN",
    "D3D11_SRV_DIMENSION_BUFFER",
    "D3D11_SRV_DIMENSION_TEXTURE1D",
    "D3D11_SRV_DIMENSION_TEXTURE1DARRAY",
    "D3D11_SRV_DIMENSION_TEXTURE2D",
    "D3D11_SRV_DIMENSION_TEXTURE2DARRAY",
    "D3D11_SRV_DIMENSION_TEXTURE2DMS",
    "D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY",
    "D3D11_SRV_DIMENSION_TEXTURE3D",
    "D3D11_SRV_DIMENSION_TEXTURECUBE",
    "D3D11_SRV_DIMENSION_TEXTURECUBEARRAY",
    "D3D11_SRV_DIMENSION_BUFFEREX",
    "D3D_SHADER_MACRO",
    "ID3DBlob",
    "PFN_DESTRUCTION_CALLBACK",
    "ID3DDestructionNotifier",
    "D3D_INCLUDE_TYPE",
    "D3D_INCLUDE_LOCAL",
    "D3D_INCLUDE_SYSTEM",
    "D3D10_INCLUDE_LOCAL",
    "D3D10_INCLUDE_SYSTEM",
    "D3D_INCLUDE_FORCE_DWORD",
    "ID3DInclude",
    "D3D_SHADER_VARIABLE_CLASS",
    "D3D_SVC_SCALAR",
    "D3D_SVC_VECTOR",
    "D3D_SVC_MATRIX_ROWS",
    "D3D_SVC_MATRIX_COLUMNS",
    "D3D_SVC_OBJECT",
    "D3D_SVC_STRUCT",
    "D3D_SVC_INTERFACE_CLASS",
    "D3D_SVC_INTERFACE_POINTER",
    "D3D10_SVC_SCALAR",
    "D3D10_SVC_VECTOR",
    "D3D10_SVC_MATRIX_ROWS",
    "D3D10_SVC_MATRIX_COLUMNS",
    "D3D10_SVC_OBJECT",
    "D3D10_SVC_STRUCT",
    "D3D11_SVC_INTERFACE_CLASS",
    "D3D11_SVC_INTERFACE_POINTER",
    "D3D_SVC_FORCE_DWORD",
    "D3D_SHADER_VARIABLE_FLAGS",
    "D3D_SVF_USERPACKED",
    "D3D_SVF_USED",
    "D3D_SVF_INTERFACE_POINTER",
    "D3D_SVF_INTERFACE_PARAMETER",
    "D3D10_SVF_USERPACKED",
    "D3D10_SVF_USED",
    "D3D11_SVF_INTERFACE_POINTER",
    "D3D11_SVF_INTERFACE_PARAMETER",
    "D3D_SVF_FORCE_DWORD",
    "D3D_SHADER_VARIABLE_TYPE",
    "D3D_SVT_VOID",
    "D3D_SVT_BOOL",
    "D3D_SVT_INT",
    "D3D_SVT_FLOAT",
    "D3D_SVT_STRING",
    "D3D_SVT_TEXTURE",
    "D3D_SVT_TEXTURE1D",
    "D3D_SVT_TEXTURE2D",
    "D3D_SVT_TEXTURE3D",
    "D3D_SVT_TEXTURECUBE",
    "D3D_SVT_SAMPLER",
    "D3D_SVT_SAMPLER1D",
    "D3D_SVT_SAMPLER2D",
    "D3D_SVT_SAMPLER3D",
    "D3D_SVT_SAMPLERCUBE",
    "D3D_SVT_PIXELSHADER",
    "D3D_SVT_VERTEXSHADER",
    "D3D_SVT_PIXELFRAGMENT",
    "D3D_SVT_VERTEXFRAGMENT",
    "D3D_SVT_UINT",
    "D3D_SVT_UINT8",
    "D3D_SVT_GEOMETRYSHADER",
    "D3D_SVT_RASTERIZER",
    "D3D_SVT_DEPTHSTENCIL",
    "D3D_SVT_BLEND",
    "D3D_SVT_BUFFER",
    "D3D_SVT_CBUFFER",
    "D3D_SVT_TBUFFER",
    "D3D_SVT_TEXTURE1DARRAY",
    "D3D_SVT_TEXTURE2DARRAY",
    "D3D_SVT_RENDERTARGETVIEW",
    "D3D_SVT_DEPTHSTENCILVIEW",
    "D3D_SVT_TEXTURE2DMS",
    "D3D_SVT_TEXTURE2DMSARRAY",
    "D3D_SVT_TEXTURECUBEARRAY",
    "D3D_SVT_HULLSHADER",
    "D3D_SVT_DOMAINSHADER",
    "D3D_SVT_INTERFACE_POINTER",
    "D3D_SVT_COMPUTESHADER",
    "D3D_SVT_DOUBLE",
    "D3D_SVT_RWTEXTURE1D",
    "D3D_SVT_RWTEXTURE1DARRAY",
    "D3D_SVT_RWTEXTURE2D",
    "D3D_SVT_RWTEXTURE2DARRAY",
    "D3D_SVT_RWTEXTURE3D",
    "D3D_SVT_RWBUFFER",
    "D3D_SVT_BYTEADDRESS_BUFFER",
    "D3D_SVT_RWBYTEADDRESS_BUFFER",
    "D3D_SVT_STRUCTURED_BUFFER",
    "D3D_SVT_RWSTRUCTURED_BUFFER",
    "D3D_SVT_APPEND_STRUCTURED_BUFFER",
    "D3D_SVT_CONSUME_STRUCTURED_BUFFER",
    "D3D_SVT_MIN8FLOAT",
    "D3D_SVT_MIN10FLOAT",
    "D3D_SVT_MIN16FLOAT",
    "D3D_SVT_MIN12INT",
    "D3D_SVT_MIN16INT",
    "D3D_SVT_MIN16UINT",
    "D3D_SVT_INT16",
    "D3D_SVT_UINT16",
    "D3D_SVT_FLOAT16",
    "D3D_SVT_INT64",
    "D3D_SVT_UINT64",
    "D3D10_SVT_VOID",
    "D3D10_SVT_BOOL",
    "D3D10_SVT_INT",
    "D3D10_SVT_FLOAT",
    "D3D10_SVT_STRING",
    "D3D10_SVT_TEXTURE",
    "D3D10_SVT_TEXTURE1D",
    "D3D10_SVT_TEXTURE2D",
    "D3D10_SVT_TEXTURE3D",
    "D3D10_SVT_TEXTURECUBE",
    "D3D10_SVT_SAMPLER",
    "D3D10_SVT_SAMPLER1D",
    "D3D10_SVT_SAMPLER2D",
    "D3D10_SVT_SAMPLER3D",
    "D3D10_SVT_SAMPLERCUBE",
    "D3D10_SVT_PIXELSHADER",
    "D3D10_SVT_VERTEXSHADER",
    "D3D10_SVT_PIXELFRAGMENT",
    "D3D10_SVT_VERTEXFRAGMENT",
    "D3D10_SVT_UINT",
    "D3D10_SVT_UINT8",
    "D3D10_SVT_GEOMETRYSHADER",
    "D3D10_SVT_RASTERIZER",
    "D3D10_SVT_DEPTHSTENCIL",
    "D3D10_SVT_BLEND",
    "D3D10_SVT_BUFFER",
    "D3D10_SVT_CBUFFER",
    "D3D10_SVT_TBUFFER",
    "D3D10_SVT_TEXTURE1DARRAY",
    "D3D10_SVT_TEXTURE2DARRAY",
    "D3D10_SVT_RENDERTARGETVIEW",
    "D3D10_SVT_DEPTHSTENCILVIEW",
    "D3D10_SVT_TEXTURE2DMS",
    "D3D10_SVT_TEXTURE2DMSARRAY",
    "D3D10_SVT_TEXTURECUBEARRAY",
    "D3D11_SVT_HULLSHADER",
    "D3D11_SVT_DOMAINSHADER",
    "D3D11_SVT_INTERFACE_POINTER",
    "D3D11_SVT_COMPUTESHADER",
    "D3D11_SVT_DOUBLE",
    "D3D11_SVT_RWTEXTURE1D",
    "D3D11_SVT_RWTEXTURE1DARRAY",
    "D3D11_SVT_RWTEXTURE2D",
    "D3D11_SVT_RWTEXTURE2DARRAY",
    "D3D11_SVT_RWTEXTURE3D",
    "D3D11_SVT_RWBUFFER",
    "D3D11_SVT_BYTEADDRESS_BUFFER",
    "D3D11_SVT_RWBYTEADDRESS_BUFFER",
    "D3D11_SVT_STRUCTURED_BUFFER",
    "D3D11_SVT_RWSTRUCTURED_BUFFER",
    "D3D11_SVT_APPEND_STRUCTURED_BUFFER",
    "D3D11_SVT_CONSUME_STRUCTURED_BUFFER",
    "D3D_SVT_FORCE_DWORD",
    "D3D_SHADER_INPUT_FLAGS",
    "D3D_SIF_USERPACKED",
    "D3D_SIF_COMPARISON_SAMPLER",
    "D3D_SIF_TEXTURE_COMPONENT_0",
    "D3D_SIF_TEXTURE_COMPONENT_1",
    "D3D_SIF_TEXTURE_COMPONENTS",
    "D3D_SIF_UNUSED",
    "D3D10_SIF_USERPACKED",
    "D3D10_SIF_COMPARISON_SAMPLER",
    "D3D10_SIF_TEXTURE_COMPONENT_0",
    "D3D10_SIF_TEXTURE_COMPONENT_1",
    "D3D10_SIF_TEXTURE_COMPONENTS",
    "D3D_SIF_FORCE_DWORD",
    "D3D_SHADER_INPUT_TYPE",
    "D3D_SIT_CBUFFER",
    "D3D_SIT_TBUFFER",
    "D3D_SIT_TEXTURE",
    "D3D_SIT_SAMPLER",
    "D3D_SIT_UAV_RWTYPED",
    "D3D_SIT_STRUCTURED",
    "D3D_SIT_UAV_RWSTRUCTURED",
    "D3D_SIT_BYTEADDRESS",
    "D3D_SIT_UAV_RWBYTEADDRESS",
    "D3D_SIT_UAV_APPEND_STRUCTURED",
    "D3D_SIT_UAV_CONSUME_STRUCTURED",
    "D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER",
    "D3D_SIT_RTACCELERATIONSTRUCTURE",
    "D3D_SIT_UAV_FEEDBACKTEXTURE",
    "D3D10_SIT_CBUFFER",
    "D3D10_SIT_TBUFFER",
    "D3D10_SIT_TEXTURE",
    "D3D10_SIT_SAMPLER",
    "D3D11_SIT_UAV_RWTYPED",
    "D3D11_SIT_STRUCTURED",
    "D3D11_SIT_UAV_RWSTRUCTURED",
    "D3D11_SIT_BYTEADDRESS",
    "D3D11_SIT_UAV_RWBYTEADDRESS",
    "D3D11_SIT_UAV_APPEND_STRUCTURED",
    "D3D11_SIT_UAV_CONSUME_STRUCTURED",
    "D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER",
    "D3D_SHADER_CBUFFER_FLAGS",
    "D3D_CBF_USERPACKED",
    "D3D10_CBF_USERPACKED",
    "D3D_CBF_FORCE_DWORD",
    "D3D_CBUFFER_TYPE",
    "D3D_CT_CBUFFER",
    "D3D_CT_TBUFFER",
    "D3D_CT_INTERFACE_POINTERS",
    "D3D_CT_RESOURCE_BIND_INFO",
    "D3D10_CT_CBUFFER",
    "D3D10_CT_TBUFFER",
    "D3D11_CT_CBUFFER",
    "D3D11_CT_TBUFFER",
    "D3D11_CT_INTERFACE_POINTERS",
    "D3D11_CT_RESOURCE_BIND_INFO",
    "D3D_NAME",
    "D3D_NAME_UNDEFINED",
    "D3D_NAME_POSITION",
    "D3D_NAME_CLIP_DISTANCE",
    "D3D_NAME_CULL_DISTANCE",
    "D3D_NAME_RENDER_TARGET_ARRAY_INDEX",
    "D3D_NAME_VIEWPORT_ARRAY_INDEX",
    "D3D_NAME_VERTEX_ID",
    "D3D_NAME_PRIMITIVE_ID",
    "D3D_NAME_INSTANCE_ID",
    "D3D_NAME_IS_FRONT_FACE",
    "D3D_NAME_SAMPLE_INDEX",
    "D3D_NAME_FINAL_QUAD_EDGE_TESSFACTOR",
    "D3D_NAME_FINAL_QUAD_INSIDE_TESSFACTOR",
    "D3D_NAME_FINAL_TRI_EDGE_TESSFACTOR",
    "D3D_NAME_FINAL_TRI_INSIDE_TESSFACTOR",
    "D3D_NAME_FINAL_LINE_DETAIL_TESSFACTOR",
    "D3D_NAME_FINAL_LINE_DENSITY_TESSFACTOR",
    "D3D_NAME_BARYCENTRICS",
    "D3D_NAME_SHADINGRATE",
    "D3D_NAME_CULLPRIMITIVE",
    "D3D_NAME_TARGET",
    "D3D_NAME_DEPTH",
    "D3D_NAME_COVERAGE",
    "D3D_NAME_DEPTH_GREATER_EQUAL",
    "D3D_NAME_DEPTH_LESS_EQUAL",
    "D3D_NAME_STENCIL_REF",
    "D3D_NAME_INNER_COVERAGE",
    "D3D10_NAME_UNDEFINED",
    "D3D10_NAME_POSITION",
    "D3D10_NAME_CLIP_DISTANCE",
    "D3D10_NAME_CULL_DISTANCE",
    "D3D10_NAME_RENDER_TARGET_ARRAY_INDEX",
    "D3D10_NAME_VIEWPORT_ARRAY_INDEX",
    "D3D10_NAME_VERTEX_ID",
    "D3D10_NAME_PRIMITIVE_ID",
    "D3D10_NAME_INSTANCE_ID",
    "D3D10_NAME_IS_FRONT_FACE",
    "D3D10_NAME_SAMPLE_INDEX",
    "D3D10_NAME_TARGET",
    "D3D10_NAME_DEPTH",
    "D3D10_NAME_COVERAGE",
    "D3D11_NAME_FINAL_QUAD_EDGE_TESSFACTOR",
    "D3D11_NAME_FINAL_QUAD_INSIDE_TESSFACTOR",
    "D3D11_NAME_FINAL_TRI_EDGE_TESSFACTOR",
    "D3D11_NAME_FINAL_TRI_INSIDE_TESSFACTOR",
    "D3D11_NAME_FINAL_LINE_DETAIL_TESSFACTOR",
    "D3D11_NAME_FINAL_LINE_DENSITY_TESSFACTOR",
    "D3D11_NAME_DEPTH_GREATER_EQUAL",
    "D3D11_NAME_DEPTH_LESS_EQUAL",
    "D3D11_NAME_STENCIL_REF",
    "D3D11_NAME_INNER_COVERAGE",
    "D3D12_NAME_BARYCENTRICS",
    "D3D12_NAME_SHADINGRATE",
    "D3D12_NAME_CULLPRIMITIVE",
    "D3D_RESOURCE_RETURN_TYPE",
    "D3D_RETURN_TYPE_UNORM",
    "D3D_RETURN_TYPE_SNORM",
    "D3D_RETURN_TYPE_SINT",
    "D3D_RETURN_TYPE_UINT",
    "D3D_RETURN_TYPE_FLOAT",
    "D3D_RETURN_TYPE_MIXED",
    "D3D_RETURN_TYPE_DOUBLE",
    "D3D_RETURN_TYPE_CONTINUED",
    "D3D10_RETURN_TYPE_UNORM",
    "D3D10_RETURN_TYPE_SNORM",
    "D3D10_RETURN_TYPE_SINT",
    "D3D10_RETURN_TYPE_UINT",
    "D3D10_RETURN_TYPE_FLOAT",
    "D3D10_RETURN_TYPE_MIXED",
    "D3D11_RETURN_TYPE_UNORM",
    "D3D11_RETURN_TYPE_SNORM",
    "D3D11_RETURN_TYPE_SINT",
    "D3D11_RETURN_TYPE_UINT",
    "D3D11_RETURN_TYPE_FLOAT",
    "D3D11_RETURN_TYPE_MIXED",
    "D3D11_RETURN_TYPE_DOUBLE",
    "D3D11_RETURN_TYPE_CONTINUED",
    "D3D_REGISTER_COMPONENT_TYPE",
    "D3D_REGISTER_COMPONENT_UNKNOWN",
    "D3D_REGISTER_COMPONENT_UINT32",
    "D3D_REGISTER_COMPONENT_SINT32",
    "D3D_REGISTER_COMPONENT_FLOAT32",
    "D3D10_REGISTER_COMPONENT_UNKNOWN",
    "D3D10_REGISTER_COMPONENT_UINT32",
    "D3D10_REGISTER_COMPONENT_SINT32",
    "D3D10_REGISTER_COMPONENT_FLOAT32",
    "D3D_TESSELLATOR_DOMAIN",
    "D3D_TESSELLATOR_DOMAIN_UNDEFINED",
    "D3D_TESSELLATOR_DOMAIN_ISOLINE",
    "D3D_TESSELLATOR_DOMAIN_TRI",
    "D3D_TESSELLATOR_DOMAIN_QUAD",
    "D3D11_TESSELLATOR_DOMAIN_UNDEFINED",
    "D3D11_TESSELLATOR_DOMAIN_ISOLINE",
    "D3D11_TESSELLATOR_DOMAIN_TRI",
    "D3D11_TESSELLATOR_DOMAIN_QUAD",
    "D3D_TESSELLATOR_PARTITIONING",
    "D3D_TESSELLATOR_PARTITIONING_UNDEFINED",
    "D3D_TESSELLATOR_PARTITIONING_INTEGER",
    "D3D_TESSELLATOR_PARTITIONING_POW2",
    "D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD",
    "D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN",
    "D3D11_TESSELLATOR_PARTITIONING_UNDEFINED",
    "D3D11_TESSELLATOR_PARTITIONING_INTEGER",
    "D3D11_TESSELLATOR_PARTITIONING_POW2",
    "D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD",
    "D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN",
    "D3D_TESSELLATOR_OUTPUT_PRIMITIVE",
    "D3D_TESSELLATOR_OUTPUT_UNDEFINED",
    "D3D_TESSELLATOR_OUTPUT_POINT",
    "D3D_TESSELLATOR_OUTPUT_LINE",
    "D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW",
    "D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW",
    "D3D11_TESSELLATOR_OUTPUT_UNDEFINED",
    "D3D11_TESSELLATOR_OUTPUT_POINT",
    "D3D11_TESSELLATOR_OUTPUT_LINE",
    "D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW",
    "D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW",
    "D3D_MIN_PRECISION",
    "D3D_MIN_PRECISION_DEFAULT",
    "D3D_MIN_PRECISION_FLOAT_16",
    "D3D_MIN_PRECISION_FLOAT_2_8",
    "D3D_MIN_PRECISION_RESERVED",
    "D3D_MIN_PRECISION_SINT_16",
    "D3D_MIN_PRECISION_UINT_16",
    "D3D_MIN_PRECISION_ANY_16",
    "D3D_MIN_PRECISION_ANY_10",
    "D3D_INTERPOLATION_MODE",
    "D3D_INTERPOLATION_UNDEFINED",
    "D3D_INTERPOLATION_CONSTANT",
    "D3D_INTERPOLATION_LINEAR",
    "D3D_INTERPOLATION_LINEAR_CENTROID",
    "D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE",
    "D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID",
    "D3D_INTERPOLATION_LINEAR_SAMPLE",
    "D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE",
    "D3D_PARAMETER_FLAGS",
    "D3D_PF_NONE",
    "D3D_PF_IN",
    "D3D_PF_OUT",
    "D3D_PF_FORCE_DWORD",
    "D3DVECTOR",
    "D3DMATRIX",
]
