from __future__ import annotations
from ctypes import c_void_p, c_char_p, c_wchar_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from Windows import ARCH, MissingType, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head, EasyCastStructure, EasyCastUnion
import Windows.Win32.Foundation
import Windows.Win32.UI.Input.XboxController
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
XINPUT_DLL_A: String = 'xinput1_4.dll'
XINPUT_DLL_W: String = 'xinput1_4.dll'
XINPUT_DLL: String = 'xinput1_4.dll'
XUSER_MAX_COUNT: UInt32 = 4
XUSER_INDEX_ANY: UInt32 = 255
@winfunctype('xinput1_4.dll')
def XInputGetState(dwUserIndex: UInt32, pState: POINTER(Windows.Win32.UI.Input.XboxController.XINPUT_STATE_head)) -> UInt32: ...
@winfunctype('xinput1_4.dll')
def XInputSetState(dwUserIndex: UInt32, pVibration: POINTER(Windows.Win32.UI.Input.XboxController.XINPUT_VIBRATION_head)) -> UInt32: ...
@winfunctype('xinput1_4.dll')
def XInputGetCapabilities(dwUserIndex: UInt32, dwFlags: Windows.Win32.UI.Input.XboxController.XINPUT_FLAG, pCapabilities: POINTER(Windows.Win32.UI.Input.XboxController.XINPUT_CAPABILITIES_head)) -> UInt32: ...
@winfunctype('xinput1_4.dll')
def XInputEnable(enable: Windows.Win32.Foundation.BOOL) -> Void: ...
@winfunctype('xinput1_4.dll')
def XInputGetAudioDeviceIds(dwUserIndex: UInt32, pRenderDeviceId: Windows.Win32.Foundation.PWSTR, pRenderCount: POINTER(UInt32), pCaptureDeviceId: Windows.Win32.Foundation.PWSTR, pCaptureCount: POINTER(UInt32)) -> UInt32: ...
@winfunctype('xinput1_4.dll')
def XInputGetBatteryInformation(dwUserIndex: UInt32, devType: Windows.Win32.UI.Input.XboxController.BATTERY_DEVTYPE, pBatteryInformation: POINTER(Windows.Win32.UI.Input.XboxController.XINPUT_BATTERY_INFORMATION_head)) -> UInt32: ...
@winfunctype('xinput1_4.dll')
def XInputGetKeystroke(dwUserIndex: UInt32, dwReserved: UInt32, pKeystroke: POINTER(Windows.Win32.UI.Input.XboxController.XINPUT_KEYSTROKE_head)) -> UInt32: ...
BATTERY_DEVTYPE = Byte
BATTERY_DEVTYPE_GAMEPAD: BATTERY_DEVTYPE = 0
BATTERY_DEVTYPE_HEADSET: BATTERY_DEVTYPE = 1
BATTERY_LEVEL = Byte
BATTERY_LEVEL_EMPTY: BATTERY_LEVEL = 0
BATTERY_LEVEL_LOW: BATTERY_LEVEL = 1
BATTERY_LEVEL_MEDIUM: BATTERY_LEVEL = 2
BATTERY_LEVEL_FULL: BATTERY_LEVEL = 3
BATTERY_TYPE = Byte
BATTERY_TYPE_DISCONNECTED: BATTERY_TYPE = 0
BATTERY_TYPE_WIRED: BATTERY_TYPE = 1
BATTERY_TYPE_ALKALINE: BATTERY_TYPE = 2
BATTERY_TYPE_NIMH: BATTERY_TYPE = 3
BATTERY_TYPE_UNKNOWN: BATTERY_TYPE = 255
class XINPUT_BATTERY_INFORMATION(EasyCastStructure):
    BatteryType: Windows.Win32.UI.Input.XboxController.BATTERY_TYPE
    BatteryLevel: Windows.Win32.UI.Input.XboxController.BATTERY_LEVEL
class XINPUT_CAPABILITIES(EasyCastStructure):
    Type: Windows.Win32.UI.Input.XboxController.XINPUT_DEVTYPE
    SubType: Windows.Win32.UI.Input.XboxController.XINPUT_DEVSUBTYPE
    Flags: Windows.Win32.UI.Input.XboxController.XINPUT_CAPABILITIES_FLAGS
    Gamepad: Windows.Win32.UI.Input.XboxController.XINPUT_GAMEPAD
    Vibration: Windows.Win32.UI.Input.XboxController.XINPUT_VIBRATION
XINPUT_CAPABILITIES_FLAGS = UInt16
XINPUT_CAPS_VOICE_SUPPORTED: XINPUT_CAPABILITIES_FLAGS = 4
XINPUT_CAPS_FFB_SUPPORTED: XINPUT_CAPABILITIES_FLAGS = 1
XINPUT_CAPS_WIRELESS: XINPUT_CAPABILITIES_FLAGS = 2
XINPUT_CAPS_PMD_SUPPORTED: XINPUT_CAPABILITIES_FLAGS = 8
XINPUT_CAPS_NO_NAVIGATION: XINPUT_CAPABILITIES_FLAGS = 16
XINPUT_DEVSUBTYPE = Byte
XINPUT_DEVSUBTYPE_GAMEPAD: XINPUT_DEVSUBTYPE = 1
XINPUT_DEVSUBTYPE_UNKNOWN: XINPUT_DEVSUBTYPE = 0
XINPUT_DEVSUBTYPE_WHEEL: XINPUT_DEVSUBTYPE = 2
XINPUT_DEVSUBTYPE_ARCADE_STICK: XINPUT_DEVSUBTYPE = 3
XINPUT_DEVSUBTYPE_FLIGHT_STICK: XINPUT_DEVSUBTYPE = 4
XINPUT_DEVSUBTYPE_DANCE_PAD: XINPUT_DEVSUBTYPE = 5
XINPUT_DEVSUBTYPE_GUITAR: XINPUT_DEVSUBTYPE = 6
XINPUT_DEVSUBTYPE_GUITAR_ALTERNATE: XINPUT_DEVSUBTYPE = 7
XINPUT_DEVSUBTYPE_DRUM_KIT: XINPUT_DEVSUBTYPE = 8
XINPUT_DEVSUBTYPE_GUITAR_BASS: XINPUT_DEVSUBTYPE = 11
XINPUT_DEVSUBTYPE_ARCADE_PAD: XINPUT_DEVSUBTYPE = 19
XINPUT_DEVTYPE = Byte
XINPUT_DEVTYPE_GAMEPAD: XINPUT_DEVTYPE = 1
XINPUT_FLAG = UInt32
XINPUT_FLAG_ALL: XINPUT_FLAG = 0
XINPUT_FLAG_GAMEPAD: XINPUT_FLAG = 1
class XINPUT_GAMEPAD(EasyCastStructure):
    wButtons: Windows.Win32.UI.Input.XboxController.XINPUT_GAMEPAD_BUTTON_FLAGS
    bLeftTrigger: Byte
    bRightTrigger: Byte
    sThumbLX: Int16
    sThumbLY: Int16
    sThumbRX: Int16
    sThumbRY: Int16
XINPUT_GAMEPAD_BUTTON_FLAGS = UInt16
XINPUT_GAMEPAD_DPAD_UP: XINPUT_GAMEPAD_BUTTON_FLAGS = 1
XINPUT_GAMEPAD_DPAD_DOWN: XINPUT_GAMEPAD_BUTTON_FLAGS = 2
XINPUT_GAMEPAD_DPAD_LEFT: XINPUT_GAMEPAD_BUTTON_FLAGS = 4
XINPUT_GAMEPAD_DPAD_RIGHT: XINPUT_GAMEPAD_BUTTON_FLAGS = 8
XINPUT_GAMEPAD_START: XINPUT_GAMEPAD_BUTTON_FLAGS = 16
XINPUT_GAMEPAD_BACK: XINPUT_GAMEPAD_BUTTON_FLAGS = 32
XINPUT_GAMEPAD_LEFT_THUMB: XINPUT_GAMEPAD_BUTTON_FLAGS = 64
XINPUT_GAMEPAD_RIGHT_THUMB: XINPUT_GAMEPAD_BUTTON_FLAGS = 128
XINPUT_GAMEPAD_LEFT_SHOULDER: XINPUT_GAMEPAD_BUTTON_FLAGS = 256
XINPUT_GAMEPAD_RIGHT_SHOULDER: XINPUT_GAMEPAD_BUTTON_FLAGS = 512
XINPUT_GAMEPAD_A: XINPUT_GAMEPAD_BUTTON_FLAGS = 4096
XINPUT_GAMEPAD_B: XINPUT_GAMEPAD_BUTTON_FLAGS = 8192
XINPUT_GAMEPAD_X: XINPUT_GAMEPAD_BUTTON_FLAGS = 16384
XINPUT_GAMEPAD_Y: XINPUT_GAMEPAD_BUTTON_FLAGS = 32768
XINPUT_GAMEPAD_LEFT_THUMB_DEADZONE: XINPUT_GAMEPAD_BUTTON_FLAGS = 7849
XINPUT_GAMEPAD_RIGHT_THUMB_DEADZONE: XINPUT_GAMEPAD_BUTTON_FLAGS = 8689
XINPUT_GAMEPAD_TRIGGER_THRESHOLD: XINPUT_GAMEPAD_BUTTON_FLAGS = 30
class XINPUT_KEYSTROKE(EasyCastStructure):
    VirtualKey: Windows.Win32.UI.Input.XboxController.XINPUT_VIRTUAL_KEY
    Unicode: Char
    Flags: Windows.Win32.UI.Input.XboxController.XINPUT_KEYSTROKE_FLAGS
    UserIndex: Byte
    HidCode: Byte
XINPUT_KEYSTROKE_FLAGS = UInt16
XINPUT_KEYSTROKE_KEYDOWN: XINPUT_KEYSTROKE_FLAGS = 1
XINPUT_KEYSTROKE_KEYUP: XINPUT_KEYSTROKE_FLAGS = 2
XINPUT_KEYSTROKE_REPEAT: XINPUT_KEYSTROKE_FLAGS = 4
class XINPUT_STATE(EasyCastStructure):
    dwPacketNumber: UInt32
    Gamepad: Windows.Win32.UI.Input.XboxController.XINPUT_GAMEPAD
class XINPUT_VIBRATION(EasyCastStructure):
    wLeftMotorSpeed: UInt16
    wRightMotorSpeed: UInt16
XINPUT_VIRTUAL_KEY = UInt16
VK_PAD_A: XINPUT_VIRTUAL_KEY = 22528
VK_PAD_B: XINPUT_VIRTUAL_KEY = 22529
VK_PAD_X: XINPUT_VIRTUAL_KEY = 22530
VK_PAD_Y: XINPUT_VIRTUAL_KEY = 22531
VK_PAD_RSHOULDER: XINPUT_VIRTUAL_KEY = 22532
VK_PAD_LSHOULDER: XINPUT_VIRTUAL_KEY = 22533
VK_PAD_LTRIGGER: XINPUT_VIRTUAL_KEY = 22534
VK_PAD_RTRIGGER: XINPUT_VIRTUAL_KEY = 22535
VK_PAD_DPAD_UP: XINPUT_VIRTUAL_KEY = 22544
VK_PAD_DPAD_DOWN: XINPUT_VIRTUAL_KEY = 22545
VK_PAD_DPAD_LEFT: XINPUT_VIRTUAL_KEY = 22546
VK_PAD_DPAD_RIGHT: XINPUT_VIRTUAL_KEY = 22547
VK_PAD_START: XINPUT_VIRTUAL_KEY = 22548
VK_PAD_BACK: XINPUT_VIRTUAL_KEY = 22549
VK_PAD_LTHUMB_PRESS: XINPUT_VIRTUAL_KEY = 22550
VK_PAD_RTHUMB_PRESS: XINPUT_VIRTUAL_KEY = 22551
VK_PAD_LTHUMB_UP: XINPUT_VIRTUAL_KEY = 22560
VK_PAD_LTHUMB_DOWN: XINPUT_VIRTUAL_KEY = 22561
VK_PAD_LTHUMB_RIGHT: XINPUT_VIRTUAL_KEY = 22562
VK_PAD_LTHUMB_LEFT: XINPUT_VIRTUAL_KEY = 22563
VK_PAD_LTHUMB_UPLEFT: XINPUT_VIRTUAL_KEY = 22564
VK_PAD_LTHUMB_UPRIGHT: XINPUT_VIRTUAL_KEY = 22565
VK_PAD_LTHUMB_DOWNRIGHT: XINPUT_VIRTUAL_KEY = 22566
VK_PAD_LTHUMB_DOWNLEFT: XINPUT_VIRTUAL_KEY = 22567
VK_PAD_RTHUMB_UP: XINPUT_VIRTUAL_KEY = 22576
VK_PAD_RTHUMB_DOWN: XINPUT_VIRTUAL_KEY = 22577
VK_PAD_RTHUMB_RIGHT: XINPUT_VIRTUAL_KEY = 22578
VK_PAD_RTHUMB_LEFT: XINPUT_VIRTUAL_KEY = 22579
VK_PAD_RTHUMB_UPLEFT: XINPUT_VIRTUAL_KEY = 22580
VK_PAD_RTHUMB_UPRIGHT: XINPUT_VIRTUAL_KEY = 22581
VK_PAD_RTHUMB_DOWNRIGHT: XINPUT_VIRTUAL_KEY = 22582
VK_PAD_RTHUMB_DOWNLEFT: XINPUT_VIRTUAL_KEY = 22583
make_head(_module, 'XINPUT_BATTERY_INFORMATION')
make_head(_module, 'XINPUT_CAPABILITIES')
make_head(_module, 'XINPUT_GAMEPAD')
make_head(_module, 'XINPUT_KEYSTROKE')
make_head(_module, 'XINPUT_STATE')
make_head(_module, 'XINPUT_VIBRATION')
