from __future__ import annotations
from ctypes import c_void_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
import sys
from typing import Generic, TypeVar
if sys.version_info < (3, 9):
    from typing_extensions import Annotated
else:
    from typing import Annotated
K = TypeVar('K')
T = TypeVar('T')
V = TypeVar('V')
TProgress = TypeVar('TProgress')
TResult = TypeVar('TResult')
TSender = TypeVar('TSender')
from win32more import ARCH, MissingType, c_char_p_no, c_wchar_p_no, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, EasyCastStructure, EasyCastUnion, ComPtr, make_ready
from win32more._winrt import SZArray, WinRT_String, winrt_commethod, winrt_mixinmethod, winrt_classmethod, winrt_factorymethod, winrt_activatemethod, winrt_overload, MulticastDelegate
import win32more.Windows.Win32.System.WinRT
import win32more.Microsoft.Windows.AppNotifications
import win32more.Microsoft.Windows.AppNotifications.Builder
import win32more.Windows.Foundation
import win32more.Windows.Foundation.Collections
AppNotificationAudioLooping = Int32
AppNotificationAudioLooping_None: AppNotificationAudioLooping = 0
AppNotificationAudioLooping_Loop: AppNotificationAudioLooping = 1
class AppNotificationBuilder(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    default_interface: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder'
    def __new__(cls, *args, **kwargs):
        if kwargs:
            return super().__new__(cls, **kwargs)
        elif len(args) == 0:
            return win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder.CreateInstance(*args)
        else:
            raise ValueError('no matched constructor')
    @winrt_activatemethod
    def CreateInstance(cls) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddArgument(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, key: WinRT_String, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetTimeStamp(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, value: win32more.Windows.Foundation.DateTime) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetDuration(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, duration: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationDuration) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetScenario(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationScenario) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddText(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, text: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddText2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, text: WinRT_String, properties: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAttributionText(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, text: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAttributionText2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, text: WinRT_String, language: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetInlineImage(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetInlineImage2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri, imageCrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetInlineImage3(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri, imagecrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop, alternateText: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAppLogoOverride(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAppLogoOverride2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri, imageCrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAppLogoOverride3(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri, imageCrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop, alternateText: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetHeroImage(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetHeroImage2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, imageUri: win32more.Windows.Foundation.Uri, alternateText: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAudioUri(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, audioUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAudioUri2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, audioUri: win32more.Windows.Foundation.Uri, loop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationAudioLooping) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAudioEvent(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, appNotificationSoundEvent: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationSoundEvent) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetAudioEvent2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, appNotificationSoundEvent: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationSoundEvent, loop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationAudioLooping) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def MuteAudio(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddTextBox(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, id: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddTextBox2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, id: WinRT_String, placeHolderText: WinRT_String, title: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddButton(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddComboBox(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def AddProgressBar(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def BuildNotification(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder) -> win32more.Microsoft.Windows.AppNotifications.AppNotification: ...
    @winrt_mixinmethod
    def SetTag(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_mixinmethod
    def SetGroup(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder, group: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_classmethod
    def IsUrgentScenarioSupported(cls: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilderStatics) -> Boolean: ...
AppNotificationBuilderContract: UInt32 = 65536
class AppNotificationButton(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    default_interface: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.AppNotificationButton'
    def __new__(cls, *args, **kwargs):
        if kwargs:
            return super().__new__(cls, **kwargs)
        elif len(args) == 0:
            return win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton.CreateInstance(*args)
        elif len(args) == 1:
            return win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton.CreateInstance(*args)
        else:
            raise ValueError('no matched constructor')
    @winrt_overload
    @winrt_activatemethod
    def CreateInstance(cls) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @CreateInstance.register
    @winrt_factorymethod
    def CreateInstance(cls: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButtonFactory, content: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def get_Content(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Content(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Arguments(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]: ...
    @winrt_mixinmethod
    def put_Arguments(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]) -> Void: ...
    @winrt_mixinmethod
    def get_Icon(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> win32more.Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_Icon(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: win32more.Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_ToolTip(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_ToolTip(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_ContextMenuPlacement(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> Boolean: ...
    @winrt_mixinmethod
    def put_ContextMenuPlacement(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: Boolean) -> Void: ...
    @winrt_mixinmethod
    def get_ButtonStyle(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButtonStyle: ...
    @winrt_mixinmethod
    def put_ButtonStyle(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButtonStyle) -> Void: ...
    @winrt_mixinmethod
    def get_InputId(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_InputId(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_InvokeUri(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> win32more.Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_InvokeUri(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: win32more.Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_TargetAppId(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_TargetAppId(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def AddArgument(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, key: WinRT_String, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetIcon(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetToolTip(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetContextMenuPlacement(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetButtonStyle(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButtonStyle) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetInputId(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetInvokeUri(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, protocolUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_mixinmethod
    def SetInvokeUri2(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton, protocolUri: win32more.Windows.Foundation.Uri, targetAppId: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_classmethod
    def IsToolTipSupported(cls: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButtonStatics) -> Boolean: ...
    @winrt_classmethod
    def IsButtonStyleSupported(cls: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationButtonStatics) -> Boolean: ...
    Content = property(get_Content, put_Content)
    Arguments = property(get_Arguments, put_Arguments)
    Icon = property(get_Icon, put_Icon)
    ToolTip = property(get_ToolTip, put_ToolTip)
    ContextMenuPlacement = property(get_ContextMenuPlacement, put_ContextMenuPlacement)
    ButtonStyle = property(get_ButtonStyle, put_ButtonStyle)
    InputId = property(get_InputId, put_InputId)
    InvokeUri = property(get_InvokeUri, put_InvokeUri)
    TargetAppId = property(get_TargetAppId, put_TargetAppId)
AppNotificationButtonStyle = Int32
AppNotificationButtonStyle_Default: AppNotificationButtonStyle = 0
AppNotificationButtonStyle_Success: AppNotificationButtonStyle = 1
AppNotificationButtonStyle_Critical: AppNotificationButtonStyle = 2
class AppNotificationComboBox(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    default_interface: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox'
    def __new__(cls, *args, **kwargs):
        if kwargs:
            return super().__new__(cls, **kwargs)
        elif len(args) == 1:
            return win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox.CreateInstance(*args)
        else:
            raise ValueError('no matched constructor')
    @winrt_factorymethod
    def CreateInstance(cls: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBoxFactory, id: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    @winrt_mixinmethod
    def get_Items(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox) -> win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]: ...
    @winrt_mixinmethod
    def put_Items(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox, value: win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]) -> Void: ...
    @winrt_mixinmethod
    def get_Title(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Title(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_SelectedItem(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_SelectedItem(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def AddItem(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox, id: WinRT_String, content: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    @winrt_mixinmethod
    def SetTitle(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    @winrt_mixinmethod
    def SetSelectedItem(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox, id: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    Items = property(get_Items, put_Items)
    Title = property(get_Title, put_Title)
    SelectedItem = property(get_SelectedItem, put_SelectedItem)
AppNotificationDuration = Int32
AppNotificationDuration_Default: AppNotificationDuration = 0
AppNotificationDuration_Long: AppNotificationDuration = 1
AppNotificationImageCrop = Int32
AppNotificationImageCrop_Default: AppNotificationImageCrop = 0
AppNotificationImageCrop_Circle: AppNotificationImageCrop = 1
class AppNotificationProgressBar(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    default_interface: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar'
    def __new__(cls, *args, **kwargs):
        if kwargs:
            return super().__new__(cls, **kwargs)
        elif len(args) == 0:
            return win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar.CreateInstance(*args)
        else:
            raise ValueError('no matched constructor')
    @winrt_activatemethod
    def CreateInstance(cls) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def get_Title(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Title(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Status(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Status(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Value(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> Double: ...
    @winrt_mixinmethod
    def put_Value(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: Double) -> Void: ...
    @winrt_mixinmethod
    def get_ValueStringOverride(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_ValueStringOverride(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def SetTitle(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def BindTitle(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def SetStatus(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def BindStatus(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def SetValue(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: Double) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def BindValue(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def SetValueStringOverride(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_mixinmethod
    def BindValueStringOverride(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    Title = property(get_Title, put_Title)
    Status = property(get_Status, put_Status)
    Value = property(get_Value, put_Value)
    ValueStringOverride = property(get_ValueStringOverride, put_ValueStringOverride)
AppNotificationScenario = Int32
AppNotificationScenario_Default: AppNotificationScenario = 0
AppNotificationScenario_Reminder: AppNotificationScenario = 1
AppNotificationScenario_Alarm: AppNotificationScenario = 2
AppNotificationScenario_IncomingCall: AppNotificationScenario = 3
AppNotificationScenario_Urgent: AppNotificationScenario = 4
AppNotificationSoundEvent = Int32
AppNotificationSoundEvent_Default: AppNotificationSoundEvent = 0
AppNotificationSoundEvent_IM: AppNotificationSoundEvent = 1
AppNotificationSoundEvent_Mail: AppNotificationSoundEvent = 2
AppNotificationSoundEvent_Reminder: AppNotificationSoundEvent = 3
AppNotificationSoundEvent_SMS: AppNotificationSoundEvent = 4
AppNotificationSoundEvent_Alarm: AppNotificationSoundEvent = 5
AppNotificationSoundEvent_Alarm2: AppNotificationSoundEvent = 6
AppNotificationSoundEvent_Alarm3: AppNotificationSoundEvent = 7
AppNotificationSoundEvent_Alarm4: AppNotificationSoundEvent = 8
AppNotificationSoundEvent_Alarm5: AppNotificationSoundEvent = 9
AppNotificationSoundEvent_Alarm6: AppNotificationSoundEvent = 10
AppNotificationSoundEvent_Alarm7: AppNotificationSoundEvent = 11
AppNotificationSoundEvent_Alarm8: AppNotificationSoundEvent = 12
AppNotificationSoundEvent_Alarm9: AppNotificationSoundEvent = 13
AppNotificationSoundEvent_Alarm10: AppNotificationSoundEvent = 14
AppNotificationSoundEvent_Call: AppNotificationSoundEvent = 15
AppNotificationSoundEvent_Call2: AppNotificationSoundEvent = 16
AppNotificationSoundEvent_Call3: AppNotificationSoundEvent = 17
AppNotificationSoundEvent_Call4: AppNotificationSoundEvent = 18
AppNotificationSoundEvent_Call5: AppNotificationSoundEvent = 19
AppNotificationSoundEvent_Call6: AppNotificationSoundEvent = 20
AppNotificationSoundEvent_Call7: AppNotificationSoundEvent = 21
AppNotificationSoundEvent_Call8: AppNotificationSoundEvent = 22
AppNotificationSoundEvent_Call9: AppNotificationSoundEvent = 23
AppNotificationSoundEvent_Call10: AppNotificationSoundEvent = 24
class AppNotificationTextProperties(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    default_interface: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties'
    def __new__(cls, *args, **kwargs):
        if kwargs:
            return super().__new__(cls, **kwargs)
        elif len(args) == 0:
            return win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties.CreateInstance(*args)
        else:
            raise ValueError('no matched constructor')
    @winrt_activatemethod
    def CreateInstance(cls) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    @winrt_mixinmethod
    def get_Language(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_IncomingCallAlignment(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties) -> Boolean: ...
    @winrt_mixinmethod
    def put_IncomingCallAlignment(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties, value: Boolean) -> Void: ...
    @winrt_mixinmethod
    def get_MaxLines(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties) -> Int32: ...
    @winrt_mixinmethod
    def put_MaxLines(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties, value: Int32) -> Void: ...
    @winrt_mixinmethod
    def SetLanguage(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    @winrt_mixinmethod
    def SetIncomingCallAlignment(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    @winrt_mixinmethod
    def SetMaxLines(self: win32more.Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties, value: Int32) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    Language = property(get_Language, put_Language)
    IncomingCallAlignment = property(get_IncomingCallAlignment, put_IncomingCallAlignment)
    MaxLines = property(get_MaxLines, put_MaxLines)
class IAppNotificationBuilder(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilder'
    _iid_ = Guid('{e801d31f-ce03-505c-adec-8a02724ec9de}')
    @winrt_commethod(6)
    def AddArgument(self, key: WinRT_String, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(7)
    def SetTimeStamp(self, value: win32more.Windows.Foundation.DateTime) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(8)
    def SetDuration(self, duration: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationDuration) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(9)
    def SetScenario(self, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationScenario) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(10)
    def AddText(self, text: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(11)
    def AddText2(self, text: WinRT_String, properties: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(12)
    def SetAttributionText(self, text: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(13)
    def SetAttributionText2(self, text: WinRT_String, language: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(14)
    def SetInlineImage(self, imageUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(15)
    def SetInlineImage2(self, imageUri: win32more.Windows.Foundation.Uri, imageCrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(16)
    def SetInlineImage3(self, imageUri: win32more.Windows.Foundation.Uri, imagecrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop, alternateText: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(17)
    def SetAppLogoOverride(self, imageUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(18)
    def SetAppLogoOverride2(self, imageUri: win32more.Windows.Foundation.Uri, imageCrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(19)
    def SetAppLogoOverride3(self, imageUri: win32more.Windows.Foundation.Uri, imageCrop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationImageCrop, alternateText: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(20)
    def SetHeroImage(self, imageUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(21)
    def SetHeroImage2(self, imageUri: win32more.Windows.Foundation.Uri, alternateText: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(22)
    def SetAudioUri(self, audioUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(23)
    def SetAudioUri2(self, audioUri: win32more.Windows.Foundation.Uri, loop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationAudioLooping) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(24)
    def SetAudioEvent(self, appNotificationSoundEvent: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationSoundEvent) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(25)
    def SetAudioEvent2(self, appNotificationSoundEvent: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationSoundEvent, loop: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationAudioLooping) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(26)
    def MuteAudio(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(27)
    def AddTextBox(self, id: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(28)
    def AddTextBox2(self, id: WinRT_String, placeHolderText: WinRT_String, title: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(29)
    def AddButton(self, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(30)
    def AddComboBox(self, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(31)
    def AddProgressBar(self, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(32)
    def BuildNotification(self) -> win32more.Microsoft.Windows.AppNotifications.AppNotification: ...
    @winrt_commethod(33)
    def SetTag(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
    @winrt_commethod(34)
    def SetGroup(self, group: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationBuilder: ...
class IAppNotificationBuilderStatics(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationBuilderStatics'
    _iid_ = Guid('{c7042d2a-d319-520e-a314-50081c8888cc}')
    @winrt_commethod(6)
    def IsUrgentScenarioSupported(self) -> Boolean: ...
class IAppNotificationButton(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationButton'
    _iid_ = Guid('{a7c03031-5634-5098-aec9-47ecb60c3499}')
    @winrt_commethod(6)
    def get_Content(self) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Content(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Arguments(self) -> win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]: ...
    @winrt_commethod(9)
    def put_Arguments(self, value: win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]) -> Void: ...
    @winrt_commethod(10)
    def get_Icon(self) -> win32more.Windows.Foundation.Uri: ...
    @winrt_commethod(11)
    def put_Icon(self, value: win32more.Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(12)
    def get_ToolTip(self) -> WinRT_String: ...
    @winrt_commethod(13)
    def put_ToolTip(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(14)
    def get_ContextMenuPlacement(self) -> Boolean: ...
    @winrt_commethod(15)
    def put_ContextMenuPlacement(self, value: Boolean) -> Void: ...
    @winrt_commethod(16)
    def get_ButtonStyle(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButtonStyle: ...
    @winrt_commethod(17)
    def put_ButtonStyle(self, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButtonStyle) -> Void: ...
    @winrt_commethod(18)
    def get_InputId(self) -> WinRT_String: ...
    @winrt_commethod(19)
    def put_InputId(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(20)
    def get_InvokeUri(self) -> win32more.Windows.Foundation.Uri: ...
    @winrt_commethod(21)
    def put_InvokeUri(self, value: win32more.Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(22)
    def get_TargetAppId(self) -> WinRT_String: ...
    @winrt_commethod(23)
    def put_TargetAppId(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(24)
    def AddArgument(self, key: WinRT_String, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(25)
    def SetIcon(self, value: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(26)
    def SetToolTip(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(27)
    def SetContextMenuPlacement(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(28)
    def SetButtonStyle(self, value: win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButtonStyle) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(29)
    def SetInputId(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(30)
    def SetInvokeUri(self, protocolUri: win32more.Windows.Foundation.Uri) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    @winrt_commethod(31)
    def SetInvokeUri2(self, protocolUri: win32more.Windows.Foundation.Uri, targetAppId: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
    Content = property(get_Content, put_Content)
    Arguments = property(get_Arguments, put_Arguments)
    Icon = property(get_Icon, put_Icon)
    ToolTip = property(get_ToolTip, put_ToolTip)
    ContextMenuPlacement = property(get_ContextMenuPlacement, put_ContextMenuPlacement)
    ButtonStyle = property(get_ButtonStyle, put_ButtonStyle)
    InputId = property(get_InputId, put_InputId)
    InvokeUri = property(get_InvokeUri, put_InvokeUri)
    TargetAppId = property(get_TargetAppId, put_TargetAppId)
class IAppNotificationButtonFactory(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationButtonFactory'
    _iid_ = Guid('{4f109286-0a6d-5a5e-9e8f-9fe31669fbb8}')
    @winrt_commethod(6)
    def CreateInstance(self, content: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationButton: ...
class IAppNotificationButtonStatics(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationButtonStatics'
    _iid_ = Guid('{fead7c18-4144-59a4-9611-86b7e8191853}')
    @winrt_commethod(6)
    def IsToolTipSupported(self) -> Boolean: ...
    @winrt_commethod(7)
    def IsButtonStyleSupported(self) -> Boolean: ...
class IAppNotificationComboBox(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBox'
    _iid_ = Guid('{4547c9e2-4815-538c-be26-040ce17f8b62}')
    @winrt_commethod(6)
    def get_Items(self) -> win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]: ...
    @winrt_commethod(7)
    def put_Items(self, value: win32more.Windows.Foundation.Collections.IMap[WinRT_String, WinRT_String]) -> Void: ...
    @winrt_commethod(8)
    def get_Title(self) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_Title(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_SelectedItem(self) -> WinRT_String: ...
    @winrt_commethod(11)
    def put_SelectedItem(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(12)
    def AddItem(self, id: WinRT_String, content: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    @winrt_commethod(13)
    def SetTitle(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    @winrt_commethod(14)
    def SetSelectedItem(self, id: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
    Items = property(get_Items, put_Items)
    Title = property(get_Title, put_Title)
    SelectedItem = property(get_SelectedItem, put_SelectedItem)
class IAppNotificationComboBoxFactory(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationComboBoxFactory'
    _iid_ = Guid('{1b31b5b0-9d86-59ed-8629-a79498ab5d4b}')
    @winrt_commethod(6)
    def CreateInstance(self, id: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationComboBox: ...
class IAppNotificationProgressBar(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationProgressBar'
    _iid_ = Guid('{fced62f2-2074-5641-8630-87a14315ac86}')
    @winrt_commethod(6)
    def get_Title(self) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Title(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Status(self) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_Status(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_Value(self) -> Double: ...
    @winrt_commethod(11)
    def put_Value(self, value: Double) -> Void: ...
    @winrt_commethod(12)
    def get_ValueStringOverride(self) -> WinRT_String: ...
    @winrt_commethod(13)
    def put_ValueStringOverride(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(14)
    def SetTitle(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(15)
    def BindTitle(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(16)
    def SetStatus(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(17)
    def BindStatus(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(18)
    def SetValue(self, value: Double) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(19)
    def BindValue(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(20)
    def SetValueStringOverride(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    @winrt_commethod(21)
    def BindValueStringOverride(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationProgressBar: ...
    Title = property(get_Title, put_Title)
    Status = property(get_Status, put_Status)
    Value = property(get_Value, put_Value)
    ValueStringOverride = property(get_ValueStringOverride, put_ValueStringOverride)
class IAppNotificationTextProperties(ComPtr):
    extends: win32more.Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Microsoft.Windows.AppNotifications.Builder.IAppNotificationTextProperties'
    _iid_ = Guid('{23a30d0b-5258-5853-932e-9521a3642afb}')
    @winrt_commethod(6)
    def get_Language(self) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Language(self, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_IncomingCallAlignment(self) -> Boolean: ...
    @winrt_commethod(9)
    def put_IncomingCallAlignment(self, value: Boolean) -> Void: ...
    @winrt_commethod(10)
    def get_MaxLines(self) -> Int32: ...
    @winrt_commethod(11)
    def put_MaxLines(self, value: Int32) -> Void: ...
    @winrt_commethod(12)
    def SetLanguage(self, value: WinRT_String) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    @winrt_commethod(13)
    def SetIncomingCallAlignment(self) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    @winrt_commethod(14)
    def SetMaxLines(self, value: Int32) -> win32more.Microsoft.Windows.AppNotifications.Builder.AppNotificationTextProperties: ...
    Language = property(get_Language, put_Language)
    IncomingCallAlignment = property(get_IncomingCallAlignment, put_IncomingCallAlignment)
    MaxLines = property(get_MaxLines, put_MaxLines)
make_ready(__name__)
