from __future__ import annotations
from ctypes import c_void_p, Structure, Union, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from win32more.base import MissingType, c_char_p_no, c_wchar_p_no, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head
import win32more.Foundation
import win32more.Graphics.Gdi
import win32more.System.Com
import win32more.System.Com.Marshal
import win32more.UI.WindowsAndMessaging
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
def __dir__():
    return __all__
@winfunctype('OLEAUT32.dll')
def BSTR_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Foundation.BSTR)) -> UInt32: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.BSTR)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.BSTR)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.Foundation.BSTR)) -> Void: ...
@winfunctype('OLE32.dll')
def HWND_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Foundation.HWND)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HWND_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.HWND)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HWND_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.HWND)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HWND_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.Foundation.HWND)) -> Void: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.System.Com.VARIANT_head)) -> UInt32: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.VARIANT_head)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.VARIANT_head)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.System.Com.VARIANT_head)) -> Void: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Foundation.BSTR)) -> UInt32: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.BSTR)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.BSTR)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def BSTR_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.Foundation.BSTR)) -> Void: ...
@winfunctype('OLE32.dll')
def HWND_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Foundation.HWND)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HWND_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.HWND)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HWND_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Foundation.HWND)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HWND_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.Foundation.HWND)) -> Void: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.System.Com.VARIANT_head)) -> UInt32: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.VARIANT_head)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.VARIANT_head)) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def VARIANT_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.System.Com.VARIANT_head)) -> Void: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(UInt16)) -> UInt32: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(UInt16)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(UInt16)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserFree(param0: POINTER(UInt32), param1: POINTER(UInt16)) -> Void: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> Void: ...
@winfunctype('OLE32.dll')
def HDC_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Graphics.Gdi.HDC)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HDC_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HDC)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HDC_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HDC)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HDC_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.Graphics.Gdi.HDC)) -> Void: ...
@winfunctype('OLE32.dll')
def HICON_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HICON_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HICON_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HICON_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> Void: ...
@winfunctype('ole32.dll')
def SNB_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(POINTER(POINTER(UInt16)))) -> UInt32: ...
@winfunctype('ole32.dll')
def SNB_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(POINTER(UInt16)))) -> c_char_p_no: ...
@winfunctype('ole32.dll')
def SNB_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(POINTER(UInt16)))) -> c_char_p_no: ...
@winfunctype('ole32.dll')
def SNB_UserFree(param0: POINTER(UInt32), param1: POINTER(POINTER(POINTER(UInt16)))) -> Void: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.System.Com.STGMEDIUM_head)) -> UInt32: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.STGMEDIUM_head)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.STGMEDIUM_head)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.System.Com.STGMEDIUM_head)) -> Void: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(UInt16)) -> UInt32: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(UInt16)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(UInt16)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def CLIPFORMAT_UserFree64(param0: POINTER(UInt32), param1: POINTER(UInt16)) -> Void: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HBITMAP_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.Graphics.Gdi.HBITMAP)) -> Void: ...
@winfunctype('OLE32.dll')
def HDC_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Graphics.Gdi.HDC)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HDC_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HDC)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HDC_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HDC)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HDC_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.Graphics.Gdi.HDC)) -> Void: ...
@winfunctype('OLE32.dll')
def HICON_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HICON_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HICON_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HICON_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.UI.WindowsAndMessaging.HICON)) -> Void: ...
@winfunctype('ole32.dll')
def SNB_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(POINTER(POINTER(UInt16)))) -> UInt32: ...
@winfunctype('ole32.dll')
def SNB_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(POINTER(UInt16)))) -> c_char_p_no: ...
@winfunctype('ole32.dll')
def SNB_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(POINTER(UInt16)))) -> c_char_p_no: ...
@winfunctype('ole32.dll')
def SNB_UserFree64(param0: POINTER(UInt32), param1: POINTER(POINTER(POINTER(UInt16)))) -> Void: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.System.Com.STGMEDIUM_head)) -> UInt32: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.STGMEDIUM_head)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.System.Com.STGMEDIUM_head)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def STGMEDIUM_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.System.Com.STGMEDIUM_head)) -> Void: ...
@winfunctype('OLE32.dll')
def CoGetMarshalSizeMax(pulSize: POINTER(UInt32), riid: POINTER(Guid), pUnk: win32more.System.Com.IUnknown_head, dwDestContext: UInt32, pvDestContext: c_void_p, mshlflags: UInt32) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoMarshalInterface(pStm: win32more.System.Com.IStream_head, riid: POINTER(Guid), pUnk: win32more.System.Com.IUnknown_head, dwDestContext: UInt32, pvDestContext: c_void_p, mshlflags: UInt32) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoUnmarshalInterface(pStm: win32more.System.Com.IStream_head, riid: POINTER(Guid), ppv: POINTER(c_void_p)) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoMarshalHresult(pstm: win32more.System.Com.IStream_head, hresult: win32more.Foundation.HRESULT) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoUnmarshalHresult(pstm: win32more.System.Com.IStream_head, phresult: POINTER(win32more.Foundation.HRESULT)) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoReleaseMarshalData(pStm: win32more.System.Com.IStream_head) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoGetStandardMarshal(riid: POINTER(Guid), pUnk: win32more.System.Com.IUnknown_head, dwDestContext: UInt32, pvDestContext: c_void_p, mshlflags: UInt32, ppMarshal: POINTER(win32more.System.Com.Marshal.IMarshal_head)) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoGetStdMarshalEx(pUnkOuter: win32more.System.Com.IUnknown_head, smexflags: UInt32, ppUnkInner: POINTER(win32more.System.Com.IUnknown_head)) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLE32.dll')
def CoMarshalInterThreadInterfaceInStream(riid: POINTER(Guid), pUnk: win32more.System.Com.IUnknown_head, ppStm: POINTER(win32more.System.Com.IStream_head)) -> win32more.Foundation.HRESULT: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> UInt32: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserFree(param0: POINTER(UInt32), param1: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> Void: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> UInt32: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> c_char_p_no: ...
@winfunctype('OLEAUT32.dll')
def LPSAFEARRAY_UserFree64(param0: POINTER(UInt32), param1: POINTER(POINTER(win32more.System.Com.SAFEARRAY_head))) -> Void: ...
@winfunctype('OLE32.dll')
def HACCEL_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HACCEL_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HACCEL_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HACCEL_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> Void: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(IntPtr)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(IntPtr)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(IntPtr)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserFree(param0: POINTER(UInt32), param1: POINTER(IntPtr)) -> Void: ...
@winfunctype('OLE32.dll')
def HMENU_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HMENU_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HMENU_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HMENU_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> Void: ...
@winfunctype('OLE32.dll')
def HACCEL_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HACCEL_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HACCEL_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HACCEL_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.UI.WindowsAndMessaging.HACCEL)) -> Void: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(IntPtr)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(IntPtr)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(IntPtr)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HGLOBAL_UserFree64(param0: POINTER(UInt32), param1: POINTER(IntPtr)) -> Void: ...
@winfunctype('OLE32.dll')
def HMENU_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HMENU_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HMENU_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HMENU_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.UI.WindowsAndMessaging.HMENU)) -> Void: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserSize(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserMarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserUnmarshal(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserFree(param0: POINTER(UInt32), param1: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> Void: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserSize64(param0: POINTER(UInt32), param1: UInt32, param2: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> UInt32: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserMarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserUnmarshal64(param0: POINTER(UInt32), param1: c_char_p_no, param2: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> c_char_p_no: ...
@winfunctype('OLE32.dll')
def HPALETTE_UserFree64(param0: POINTER(UInt32), param1: POINTER(win32more.Graphics.Gdi.HPALETTE)) -> Void: ...
class IMarshal(c_void_p):
    extends: win32more.System.Com.IUnknown
    Guid = Guid('00000003-0000-0000-c0-00-00-00-00-00-00-46')
    @commethod(3)
    def GetUnmarshalClass(riid: POINTER(Guid), pv: c_void_p, dwDestContext: UInt32, pvDestContext: c_void_p, mshlflags: UInt32, pCid: POINTER(Guid)) -> win32more.Foundation.HRESULT: ...
    @commethod(4)
    def GetMarshalSizeMax(riid: POINTER(Guid), pv: c_void_p, dwDestContext: UInt32, pvDestContext: c_void_p, mshlflags: UInt32, pSize: POINTER(UInt32)) -> win32more.Foundation.HRESULT: ...
    @commethod(5)
    def MarshalInterface(pStm: win32more.System.Com.IStream_head, riid: POINTER(Guid), pv: c_void_p, dwDestContext: UInt32, pvDestContext: c_void_p, mshlflags: UInt32) -> win32more.Foundation.HRESULT: ...
    @commethod(6)
    def UnmarshalInterface(pStm: win32more.System.Com.IStream_head, riid: POINTER(Guid), ppv: POINTER(c_void_p)) -> win32more.Foundation.HRESULT: ...
    @commethod(7)
    def ReleaseMarshalData(pStm: win32more.System.Com.IStream_head) -> win32more.Foundation.HRESULT: ...
    @commethod(8)
    def DisconnectObject(dwReserved: UInt32) -> win32more.Foundation.HRESULT: ...
class IMarshal2(c_void_p):
    extends: win32more.System.Com.Marshal.IMarshal
    Guid = Guid('000001cf-0000-0000-c0-00-00-00-00-00-00-46')
class IMarshalingStream(c_void_p):
    extends: win32more.System.Com.IStream
    Guid = Guid('d8f2f5e6-6102-4863-9f-26-38-9a-46-76-ef-de')
    @commethod(14)
    def GetMarshalingContextAttribute(attribute: win32more.System.Com.CO_MARSHALING_CONTEXT_ATTRIBUTES, pAttributeValue: POINTER(UIntPtr)) -> win32more.Foundation.HRESULT: ...
STDMSHLFLAGS = Int32
SMEXF_SERVER: STDMSHLFLAGS = 1
SMEXF_HANDLER: STDMSHLFLAGS = 2
make_head(_module, 'IMarshal')
make_head(_module, 'IMarshal2')
make_head(_module, 'IMarshalingStream')
__all__ = [
    "BSTR_UserFree",
    "BSTR_UserFree64",
    "BSTR_UserMarshal",
    "BSTR_UserMarshal64",
    "BSTR_UserSize",
    "BSTR_UserSize64",
    "BSTR_UserUnmarshal",
    "BSTR_UserUnmarshal64",
    "CLIPFORMAT_UserFree",
    "CLIPFORMAT_UserFree64",
    "CLIPFORMAT_UserMarshal",
    "CLIPFORMAT_UserMarshal64",
    "CLIPFORMAT_UserSize",
    "CLIPFORMAT_UserSize64",
    "CLIPFORMAT_UserUnmarshal",
    "CLIPFORMAT_UserUnmarshal64",
    "CoGetMarshalSizeMax",
    "CoGetStandardMarshal",
    "CoGetStdMarshalEx",
    "CoMarshalHresult",
    "CoMarshalInterThreadInterfaceInStream",
    "CoMarshalInterface",
    "CoReleaseMarshalData",
    "CoUnmarshalHresult",
    "CoUnmarshalInterface",
    "HACCEL_UserFree",
    "HACCEL_UserFree64",
    "HACCEL_UserMarshal",
    "HACCEL_UserMarshal64",
    "HACCEL_UserSize",
    "HACCEL_UserSize64",
    "HACCEL_UserUnmarshal",
    "HACCEL_UserUnmarshal64",
    "HBITMAP_UserFree",
    "HBITMAP_UserFree64",
    "HBITMAP_UserMarshal",
    "HBITMAP_UserMarshal64",
    "HBITMAP_UserSize",
    "HBITMAP_UserSize64",
    "HBITMAP_UserUnmarshal",
    "HBITMAP_UserUnmarshal64",
    "HDC_UserFree",
    "HDC_UserFree64",
    "HDC_UserMarshal",
    "HDC_UserMarshal64",
    "HDC_UserSize",
    "HDC_UserSize64",
    "HDC_UserUnmarshal",
    "HDC_UserUnmarshal64",
    "HGLOBAL_UserFree",
    "HGLOBAL_UserFree64",
    "HGLOBAL_UserMarshal",
    "HGLOBAL_UserMarshal64",
    "HGLOBAL_UserSize",
    "HGLOBAL_UserSize64",
    "HGLOBAL_UserUnmarshal",
    "HGLOBAL_UserUnmarshal64",
    "HICON_UserFree",
    "HICON_UserFree64",
    "HICON_UserMarshal",
    "HICON_UserMarshal64",
    "HICON_UserSize",
    "HICON_UserSize64",
    "HICON_UserUnmarshal",
    "HICON_UserUnmarshal64",
    "HMENU_UserFree",
    "HMENU_UserFree64",
    "HMENU_UserMarshal",
    "HMENU_UserMarshal64",
    "HMENU_UserSize",
    "HMENU_UserSize64",
    "HMENU_UserUnmarshal",
    "HMENU_UserUnmarshal64",
    "HPALETTE_UserFree",
    "HPALETTE_UserFree64",
    "HPALETTE_UserMarshal",
    "HPALETTE_UserMarshal64",
    "HPALETTE_UserSize",
    "HPALETTE_UserSize64",
    "HPALETTE_UserUnmarshal",
    "HPALETTE_UserUnmarshal64",
    "HWND_UserFree",
    "HWND_UserFree64",
    "HWND_UserMarshal",
    "HWND_UserMarshal64",
    "HWND_UserSize",
    "HWND_UserSize64",
    "HWND_UserUnmarshal",
    "HWND_UserUnmarshal64",
    "IMarshal",
    "IMarshal2",
    "IMarshalingStream",
    "LPSAFEARRAY_UserFree",
    "LPSAFEARRAY_UserFree64",
    "LPSAFEARRAY_UserMarshal",
    "LPSAFEARRAY_UserMarshal64",
    "LPSAFEARRAY_UserSize",
    "LPSAFEARRAY_UserSize64",
    "LPSAFEARRAY_UserUnmarshal",
    "LPSAFEARRAY_UserUnmarshal64",
    "SMEXF_HANDLER",
    "SMEXF_SERVER",
    "SNB_UserFree",
    "SNB_UserFree64",
    "SNB_UserMarshal",
    "SNB_UserMarshal64",
    "SNB_UserSize",
    "SNB_UserSize64",
    "SNB_UserUnmarshal",
    "SNB_UserUnmarshal64",
    "STDMSHLFLAGS",
    "STGMEDIUM_UserFree",
    "STGMEDIUM_UserFree64",
    "STGMEDIUM_UserMarshal",
    "STGMEDIUM_UserMarshal64",
    "STGMEDIUM_UserSize",
    "STGMEDIUM_UserSize64",
    "STGMEDIUM_UserUnmarshal",
    "STGMEDIUM_UserUnmarshal64",
    "VARIANT_UserFree",
    "VARIANT_UserFree64",
    "VARIANT_UserMarshal",
    "VARIANT_UserMarshal64",
    "VARIANT_UserSize",
    "VARIANT_UserSize64",
    "VARIANT_UserUnmarshal",
    "VARIANT_UserUnmarshal64",
]
