from __future__ import annotations
from ctypes import c_void_p, c_char_p, c_wchar_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from Windows import ARCH, MissingType, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head, EasyCastStructure, EasyCastUnion, ComPtr
import Windows.Win32.Foundation
import Windows.Win32.System.Com
import Windows.Win32.System.TaskScheduler
import Windows.Win32.System.Variant
import Windows.Win32.UI.Controls
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
TASK_SUNDAY: UInt32 = 1
TASK_MONDAY: UInt32 = 2
TASK_TUESDAY: UInt32 = 4
TASK_WEDNESDAY: UInt32 = 8
TASK_THURSDAY: UInt32 = 16
TASK_FRIDAY: UInt32 = 32
TASK_SATURDAY: UInt32 = 64
TASK_FIRST_WEEK: UInt32 = 1
TASK_SECOND_WEEK: UInt32 = 2
TASK_THIRD_WEEK: UInt32 = 3
TASK_FOURTH_WEEK: UInt32 = 4
TASK_LAST_WEEK: UInt32 = 5
TASK_JANUARY: UInt32 = 1
TASK_FEBRUARY: UInt32 = 2
TASK_MARCH: UInt32 = 4
TASK_APRIL: UInt32 = 8
TASK_MAY: UInt32 = 16
TASK_JUNE: UInt32 = 32
TASK_JULY: UInt32 = 64
TASK_AUGUST: UInt32 = 128
TASK_SEPTEMBER: UInt32 = 256
TASK_OCTOBER: UInt32 = 512
TASK_NOVEMBER: UInt32 = 1024
TASK_DECEMBER: UInt32 = 2048
TASK_FLAG_INTERACTIVE: UInt32 = 1
TASK_FLAG_DELETE_WHEN_DONE: UInt32 = 2
TASK_FLAG_DISABLED: UInt32 = 4
TASK_FLAG_START_ONLY_IF_IDLE: UInt32 = 16
TASK_FLAG_KILL_ON_IDLE_END: UInt32 = 32
TASK_FLAG_DONT_START_IF_ON_BATTERIES: UInt32 = 64
TASK_FLAG_KILL_IF_GOING_ON_BATTERIES: UInt32 = 128
TASK_FLAG_RUN_ONLY_IF_DOCKED: UInt32 = 256
TASK_FLAG_HIDDEN: UInt32 = 512
TASK_FLAG_RUN_IF_CONNECTED_TO_INTERNET: UInt32 = 1024
TASK_FLAG_RESTART_ON_IDLE_RESUME: UInt32 = 2048
TASK_FLAG_SYSTEM_REQUIRED: UInt32 = 4096
TASK_FLAG_RUN_ONLY_IF_LOGGED_ON: UInt32 = 8192
TASK_TRIGGER_FLAG_HAS_END_DATE: UInt32 = 1
TASK_TRIGGER_FLAG_KILL_AT_DURATION_END: UInt32 = 2
TASK_TRIGGER_FLAG_DISABLED: UInt32 = 4
TASK_MAX_RUN_TIMES: UInt32 = 1440
CLSID_CTask: Guid = Guid('{148bd520-a2ab-11ce-b11f-00aa00530503}')
CLSID_CTaskScheduler: Guid = Guid('{148bd52a-a2ab-11ce-b11f-00aa00530503}')
class DAILY(EasyCastStructure):
    DaysInterval: UInt16
class IAction(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{bae54997-48b1-4cbe-9965-d6be263ebea4}')
    @commethod(7)
    def get_Id(self, pId: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_Id(self, Id: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Type(self, pType: POINTER(Windows.Win32.System.TaskScheduler.TASK_ACTION_TYPE)) -> Windows.Win32.Foundation.HRESULT: ...
class IActionCollection(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{02820e19-7b98-4ed2-b2e8-fdccceff619b}')
    @commethod(7)
    def get_Count(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Item(self, index: Int32, ppAction: POINTER(Windows.Win32.System.TaskScheduler.IAction_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get__NewEnum(self, ppEnum: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def get_XmlText(self, pText: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_XmlText(self, text: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def Create(self, type: Windows.Win32.System.TaskScheduler.TASK_ACTION_TYPE, ppAction: POINTER(Windows.Win32.System.TaskScheduler.IAction_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def Remove(self, index: Windows.Win32.System.Variant.VARIANT) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def Clear(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_Context(self, pContext: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def put_Context(self, context: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IBootTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{2a9c35da-d357-41f4-bbc1-207ac1b1f3cb}')
    @commethod(20)
    def get_Delay(self, pDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_Delay(self, delay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IComHandlerAction(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.IAction
    _iid_ = Guid('{6d2fd252-75c5-4f66-90ba-2a7d8cc3039f}')
    @commethod(10)
    def get_ClassId(self, pClsid: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_ClassId(self, clsid: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_Data(self, pData: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def put_Data(self, data: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IDailyTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{126c5cd8-b288-41d5-8dbf-e491446adc5c}')
    @commethod(20)
    def get_DaysInterval(self, pDays: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_DaysInterval(self, days: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_RandomDelay(self, pRandomDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_RandomDelay(self, randomDelay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IEmailAction(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.IAction
    _iid_ = Guid('{10f62c64-7e16-4314-a0c2-0c3683f99d40}')
    @commethod(10)
    def get_Server(self, pServer: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_Server(self, server: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_Subject(self, pSubject: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def put_Subject(self, subject: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def get_To(self, pTo: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def put_To(self, to: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def get_Cc(self, pCc: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def put_Cc(self, cc: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def get_Bcc(self, pBcc: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def put_Bcc(self, bcc: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def get_ReplyTo(self, pReplyTo: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_ReplyTo(self, replyTo: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_From(self, pFrom: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_From(self, from_: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def get_HeaderFields(self, ppHeaderFields: POINTER(Windows.Win32.System.TaskScheduler.ITaskNamedValueCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def put_HeaderFields(self, pHeaderFields: Windows.Win32.System.TaskScheduler.ITaskNamedValueCollection_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def get_Body(self, pBody: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def put_Body(self, body: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(28)
    def get_Attachments(self, pAttachements: POINTER(POINTER(Windows.Win32.System.Com.SAFEARRAY_head))) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(29)
    def put_Attachments(self, pAttachements: POINTER(Windows.Win32.System.Com.SAFEARRAY_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IEnumWorkItems(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{148bd528-a2ab-11ce-b11f-00aa00530503}')
    @commethod(3)
    def Next(self, celt: UInt32, rgpwszNames: POINTER(POINTER(Windows.Win32.Foundation.PWSTR)), pceltFetched: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def Skip(self, celt: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def Reset(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def Clone(self, ppEnumWorkItems: POINTER(Windows.Win32.System.TaskScheduler.IEnumWorkItems_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IEventTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{d45b0167-9653-4eef-b94f-0732ca7af251}')
    @commethod(20)
    def get_Subscription(self, pQuery: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_Subscription(self, query: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_Delay(self, pDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_Delay(self, delay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def get_ValueQueries(self, ppNamedXPaths: POINTER(Windows.Win32.System.TaskScheduler.ITaskNamedValueCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def put_ValueQueries(self, pNamedXPaths: Windows.Win32.System.TaskScheduler.ITaskNamedValueCollection_head) -> Windows.Win32.Foundation.HRESULT: ...
class IExecAction(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.IAction
    _iid_ = Guid('{4c3d624d-fd6b-49a3-b9b7-09cb3cd3f047}')
    @commethod(10)
    def get_Path(self, pPath: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_Path(self, path: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_Arguments(self, pArgument: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def put_Arguments(self, argument: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def get_WorkingDirectory(self, pWorkingDirectory: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def put_WorkingDirectory(self, workingDirectory: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IExecAction2(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.IExecAction
    _iid_ = Guid('{f2a82542-bda5-4e6b-9143-e2bf4f8987b6}')
    @commethod(16)
    def get_HideAppWindow(self, pHideAppWindow: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def put_HideAppWindow(self, hideAppWindow: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IIdleSettings(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{84594461-0053-4342-a8fd-088fabf11f32}')
    @commethod(7)
    def get_IdleDuration(self, pDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_IdleDuration(self, delay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_WaitTimeout(self, pTimeout: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_WaitTimeout(self, timeout: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_StopOnIdleEnd(self, pStop: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def put_StopOnIdleEnd(self, stop: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def get_RestartOnIdle(self, pRestart: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def put_RestartOnIdle(self, restart: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IIdleTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{d537d2b0-9fb3-4d34-9739-1ff5ce7b1ef3}')
class ILogonTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{72dade38-fae4-4b3e-baf4-5d009af02b1c}')
    @commethod(20)
    def get_Delay(self, pDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_Delay(self, delay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_UserId(self, pUser: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_UserId(self, user: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IMaintenanceSettings(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{a6024fa8-9652-4adb-a6bf-5cfcd877a7ba}')
    @commethod(7)
    def put_Period(self, value: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Period(self, target: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def put_Deadline(self, value: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def get_Deadline(self, target: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_Exclusive(self, value: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_Exclusive(self, target: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
class IMonthlyDOWTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{77d025a3-90fa-43aa-b52e-cda5499b946a}')
    @commethod(20)
    def get_DaysOfWeek(self, pDays: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_DaysOfWeek(self, days: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_WeeksOfMonth(self, pWeeks: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_WeeksOfMonth(self, weeks: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def get_MonthsOfYear(self, pMonths: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def put_MonthsOfYear(self, months: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def get_RunOnLastWeekOfMonth(self, pLastWeek: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def put_RunOnLastWeekOfMonth(self, lastWeek: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(28)
    def get_RandomDelay(self, pRandomDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(29)
    def put_RandomDelay(self, randomDelay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IMonthlyTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{97c45ef1-6b02-4a1a-9c0e-1ebfba1500ac}')
    @commethod(20)
    def get_DaysOfMonth(self, pDays: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_DaysOfMonth(self, days: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_MonthsOfYear(self, pMonths: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_MonthsOfYear(self, months: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def get_RunOnLastDayOfMonth(self, pLastDay: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def put_RunOnLastDayOfMonth(self, lastDay: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def get_RandomDelay(self, pRandomDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def put_RandomDelay(self, randomDelay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class INetworkSettings(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{9f7dea84-c30b-4245-80b6-00e9f646f1b4}')
    @commethod(7)
    def get_Name(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_Name(self, name: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Id(self, pId: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_Id(self, id: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IPrincipal(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{d98d51e5-c9b4-496a-a9c1-18980261cf0f}')
    @commethod(7)
    def get_Id(self, pId: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_Id(self, Id: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_DisplayName(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_DisplayName(self, name: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_UserId(self, pUser: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def put_UserId(self, user: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def get_LogonType(self, pLogon: POINTER(Windows.Win32.System.TaskScheduler.TASK_LOGON_TYPE)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def put_LogonType(self, logon: Windows.Win32.System.TaskScheduler.TASK_LOGON_TYPE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_GroupId(self, pGroup: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def put_GroupId(self, group: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def get_RunLevel(self, pRunLevel: POINTER(Windows.Win32.System.TaskScheduler.TASK_RUNLEVEL_TYPE)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def put_RunLevel(self, runLevel: Windows.Win32.System.TaskScheduler.TASK_RUNLEVEL_TYPE) -> Windows.Win32.Foundation.HRESULT: ...
class IPrincipal2(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{248919ae-e345-4a6d-8aeb-e0d3165c904e}')
    @commethod(7)
    def get_ProcessTokenSidType(self, pProcessTokenSidType: POINTER(Windows.Win32.System.TaskScheduler.TASK_PROCESSTOKENSID_TYPE)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_ProcessTokenSidType(self, processTokenSidType: Windows.Win32.System.TaskScheduler.TASK_PROCESSTOKENSID_TYPE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_RequiredPrivilegeCount(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def get_RequiredPrivilege(self, index: Int32, pPrivilege: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def AddRequiredPrivilege(self, privilege: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IProvideTaskPage(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{4086658a-cbbb-11cf-b604-00c04fd8d565}')
    @commethod(3)
    def GetPage(self, tpType: Windows.Win32.System.TaskScheduler.TASKPAGE, fPersistChanges: Windows.Win32.Foundation.BOOL, phPage: POINTER(Windows.Win32.UI.Controls.HPROPSHEETPAGE)) -> Windows.Win32.Foundation.HRESULT: ...
class IRegisteredTask(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{9c86f320-dee3-4dd1-b972-a303f26b061e}')
    @commethod(7)
    def get_Name(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Path(self, pPath: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_State(self, pState: POINTER(Windows.Win32.System.TaskScheduler.TASK_STATE)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def get_Enabled(self, pEnabled: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_Enabled(self, enabled: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def Run(self, params: Windows.Win32.System.Variant.VARIANT, ppRunningTask: POINTER(Windows.Win32.System.TaskScheduler.IRunningTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def RunEx(self, params: Windows.Win32.System.Variant.VARIANT, flags: Int32, sessionID: Int32, user: Windows.Win32.Foundation.BSTR, ppRunningTask: POINTER(Windows.Win32.System.TaskScheduler.IRunningTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def GetInstances(self, flags: Int32, ppRunningTasks: POINTER(Windows.Win32.System.TaskScheduler.IRunningTaskCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_LastRunTime(self, pLastRunTime: POINTER(Double)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def get_LastTaskResult(self, pLastTaskResult: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def get_NumberOfMissedRuns(self, pNumberOfMissedRuns: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def get_NextRunTime(self, pNextRunTime: POINTER(Double)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def get_Definition(self, ppDefinition: POINTER(Windows.Win32.System.TaskScheduler.ITaskDefinition_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def get_Xml(self, pXml: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def GetSecurityDescriptor(self, securityInformation: Int32, pSddl: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def SetSecurityDescriptor(self, sddl: Windows.Win32.Foundation.BSTR, flags: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def Stop(self, flags: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def GetRunTimes(self, pstStart: POINTER(Windows.Win32.Foundation.SYSTEMTIME_head), pstEnd: POINTER(Windows.Win32.Foundation.SYSTEMTIME_head), pCount: POINTER(UInt32), pRunTimes: POINTER(POINTER(Windows.Win32.Foundation.SYSTEMTIME_head))) -> Windows.Win32.Foundation.HRESULT: ...
class IRegisteredTaskCollection(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{86627eb4-42a7-41e4-a4d9-ac33a72f2d52}')
    @commethod(7)
    def get_Count(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Item(self, index: Windows.Win32.System.Variant.VARIANT, ppRegisteredTask: POINTER(Windows.Win32.System.TaskScheduler.IRegisteredTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get__NewEnum(self, ppEnum: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IRegistrationInfo(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{416d8b73-cb41-4ea1-805c-9be9a5ac4a74}')
    @commethod(7)
    def get_Description(self, pDescription: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_Description(self, description: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Author(self, pAuthor: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_Author(self, author: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_Version(self, pVersion: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def put_Version(self, version: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def get_Date(self, pDate: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def put_Date(self, date: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_Documentation(self, pDocumentation: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def put_Documentation(self, documentation: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def get_XmlText(self, pText: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def put_XmlText(self, text: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def get_URI(self, pUri: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def put_URI(self, uri: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def get_SecurityDescriptor(self, pSddl: POINTER(Windows.Win32.System.Variant.VARIANT_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def put_SecurityDescriptor(self, sddl: Windows.Win32.System.Variant.VARIANT) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def get_Source(self, pSource: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def put_Source(self, source: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IRegistrationTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{4c8fec3a-c218-4e0c-b23d-629024db91a2}')
    @commethod(20)
    def get_Delay(self, pDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_Delay(self, delay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class IRepetitionPattern(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{7fb9acf1-26be-400e-85b5-294b9c75dfd6}')
    @commethod(7)
    def get_Interval(self, pInterval: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_Interval(self, interval: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Duration(self, pDuration: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_Duration(self, duration: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_StopAtDurationEnd(self, pStop: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def put_StopAtDurationEnd(self, stop: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IRunningTask(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{653758fb-7b9a-4f1e-a471-beeb8e9b834e}')
    @commethod(7)
    def get_Name(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_InstanceGuid(self, pGuid: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Path(self, pPath: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def get_State(self, pState: POINTER(Windows.Win32.System.TaskScheduler.TASK_STATE)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_CurrentAction(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def Stop(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def Refresh(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def get_EnginePID(self, pPID: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
class IRunningTaskCollection(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{6a67614b-6828-4fec-aa54-6d52e8f1f2db}')
    @commethod(7)
    def get_Count(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Item(self, index: Windows.Win32.System.Variant.VARIANT, ppRunningTask: POINTER(Windows.Win32.System.TaskScheduler.IRunningTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get__NewEnum(self, ppEnum: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IScheduledWorkItem(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{a6b952f0-a4b1-11d0-997d-00aa006887ec}')
    @commethod(3)
    def CreateTrigger(self, piNewTrigger: POINTER(UInt16), ppTrigger: POINTER(Windows.Win32.System.TaskScheduler.ITaskTrigger_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def DeleteTrigger(self, iTrigger: UInt16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def GetTriggerCount(self, pwCount: POINTER(UInt16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def GetTrigger(self, iTrigger: UInt16, ppTrigger: POINTER(Windows.Win32.System.TaskScheduler.ITaskTrigger_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def GetTriggerString(self, iTrigger: UInt16, ppwszTrigger: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def GetRunTimes(self, pstBegin: POINTER(Windows.Win32.Foundation.SYSTEMTIME_head), pstEnd: POINTER(Windows.Win32.Foundation.SYSTEMTIME_head), pCount: POINTER(UInt16), rgstTaskTimes: POINTER(POINTER(Windows.Win32.Foundation.SYSTEMTIME_head))) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def GetNextRunTime(self, pstNextRun: POINTER(Windows.Win32.Foundation.SYSTEMTIME_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetIdleWait(self, wIdleMinutes: UInt16, wDeadlineMinutes: UInt16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def GetIdleWait(self, pwIdleMinutes: POINTER(UInt16), pwDeadlineMinutes: POINTER(UInt16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def Run(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def Terminate(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def EditWorkItem(self, hParent: Windows.Win32.Foundation.HWND, dwReserved: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def GetMostRecentRunTime(self, pstLastRun: POINTER(Windows.Win32.Foundation.SYSTEMTIME_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def GetStatus(self, phrStatus: POINTER(Windows.Win32.Foundation.HRESULT)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def GetExitCode(self, pdwExitCode: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def SetComment(self, pwszComment: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def GetComment(self, ppwszComment: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def SetCreator(self, pwszCreator: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def GetCreator(self, ppwszCreator: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def SetWorkItemData(self, cbData: UInt16, rgbData: POINTER(Byte)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def GetWorkItemData(self, pcbData: POINTER(UInt16), prgbData: POINTER(POINTER(Byte))) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def SetErrorRetryCount(self, wRetryCount: UInt16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def GetErrorRetryCount(self, pwRetryCount: POINTER(UInt16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def SetErrorRetryInterval(self, wRetryInterval: UInt16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def GetErrorRetryInterval(self, pwRetryInterval: POINTER(UInt16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(28)
    def SetFlags(self, dwFlags: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(29)
    def GetFlags(self, pdwFlags: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(30)
    def SetAccountInformation(self, pwszAccountName: Windows.Win32.Foundation.PWSTR, pwszPassword: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(31)
    def GetAccountInformation(self, ppwszAccountName: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
class ISessionStateChangeTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{754da71b-4385-4475-9dd9-598294fa3641}')
    @commethod(20)
    def get_Delay(self, pDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_Delay(self, delay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_UserId(self, pUser: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_UserId(self, user: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def get_StateChange(self, pType: POINTER(Windows.Win32.System.TaskScheduler.TASK_SESSION_STATE_CHANGE_TYPE)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def put_StateChange(self, type: Windows.Win32.System.TaskScheduler.TASK_SESSION_STATE_CHANGE_TYPE) -> Windows.Win32.Foundation.HRESULT: ...
class IShowMessageAction(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.IAction
    _iid_ = Guid('{505e9e68-af89-46b8-a30f-56162a83d537}')
    @commethod(10)
    def get_Title(self, pTitle: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_Title(self, title: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_MessageBody(self, pMessageBody: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def put_MessageBody(self, messageBody: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class ITask(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.IScheduledWorkItem
    _iid_ = Guid('{148bd524-a2ab-11ce-b11f-00aa00530503}')
    @commethod(32)
    def SetApplicationName(self, pwszApplicationName: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(33)
    def GetApplicationName(self, ppwszApplicationName: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(34)
    def SetParameters(self, pwszParameters: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(35)
    def GetParameters(self, ppwszParameters: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(36)
    def SetWorkingDirectory(self, pwszWorkingDirectory: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(37)
    def GetWorkingDirectory(self, ppwszWorkingDirectory: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(38)
    def SetPriority(self, dwPriority: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(39)
    def GetPriority(self, pdwPriority: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(40)
    def SetTaskFlags(self, dwFlags: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(41)
    def GetTaskFlags(self, pdwFlags: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(42)
    def SetMaxRunTime(self, dwMaxRunTimeMS: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(43)
    def GetMaxRunTime(self, pdwMaxRunTimeMS: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskDefinition(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{f5bc8fc5-536d-4f77-b852-fbc1356fdeb6}')
    @commethod(7)
    def get_RegistrationInfo(self, ppRegistrationInfo: POINTER(Windows.Win32.System.TaskScheduler.IRegistrationInfo_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_RegistrationInfo(self, pRegistrationInfo: Windows.Win32.System.TaskScheduler.IRegistrationInfo_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Triggers(self, ppTriggers: POINTER(Windows.Win32.System.TaskScheduler.ITriggerCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_Triggers(self, pTriggers: Windows.Win32.System.TaskScheduler.ITriggerCollection_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_Settings(self, ppSettings: POINTER(Windows.Win32.System.TaskScheduler.ITaskSettings_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def put_Settings(self, pSettings: Windows.Win32.System.TaskScheduler.ITaskSettings_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def get_Data(self, pData: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def put_Data(self, data: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_Principal(self, ppPrincipal: POINTER(Windows.Win32.System.TaskScheduler.IPrincipal_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def put_Principal(self, pPrincipal: Windows.Win32.System.TaskScheduler.IPrincipal_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def get_Actions(self, ppActions: POINTER(Windows.Win32.System.TaskScheduler.IActionCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def put_Actions(self, pActions: Windows.Win32.System.TaskScheduler.IActionCollection_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def get_XmlText(self, pXml: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def put_XmlText(self, xml: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskFolder(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{8cfac062-a080-4c15-9a88-aa7c2af80dfc}')
    @commethod(7)
    def get_Name(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Path(self, pPath: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def GetFolder(self, path: Windows.Win32.Foundation.BSTR, ppFolder: POINTER(Windows.Win32.System.TaskScheduler.ITaskFolder_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def GetFolders(self, flags: Int32, ppFolders: POINTER(Windows.Win32.System.TaskScheduler.ITaskFolderCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def CreateFolder(self, subFolderName: Windows.Win32.Foundation.BSTR, sddl: Windows.Win32.System.Variant.VARIANT, ppFolder: POINTER(Windows.Win32.System.TaskScheduler.ITaskFolder_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def DeleteFolder(self, subFolderName: Windows.Win32.Foundation.BSTR, flags: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def GetTask(self, path: Windows.Win32.Foundation.BSTR, ppTask: POINTER(Windows.Win32.System.TaskScheduler.IRegisteredTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def GetTasks(self, flags: Int32, ppTasks: POINTER(Windows.Win32.System.TaskScheduler.IRegisteredTaskCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def DeleteTask(self, name: Windows.Win32.Foundation.BSTR, flags: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def RegisterTask(self, path: Windows.Win32.Foundation.BSTR, xmlText: Windows.Win32.Foundation.BSTR, flags: Int32, userId: Windows.Win32.System.Variant.VARIANT, password: Windows.Win32.System.Variant.VARIANT, logonType: Windows.Win32.System.TaskScheduler.TASK_LOGON_TYPE, sddl: Windows.Win32.System.Variant.VARIANT, ppTask: POINTER(Windows.Win32.System.TaskScheduler.IRegisteredTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def RegisterTaskDefinition(self, path: Windows.Win32.Foundation.BSTR, pDefinition: Windows.Win32.System.TaskScheduler.ITaskDefinition_head, flags: Int32, userId: Windows.Win32.System.Variant.VARIANT, password: Windows.Win32.System.Variant.VARIANT, logonType: Windows.Win32.System.TaskScheduler.TASK_LOGON_TYPE, sddl: Windows.Win32.System.Variant.VARIANT, ppTask: POINTER(Windows.Win32.System.TaskScheduler.IRegisteredTask_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def GetSecurityDescriptor(self, securityInformation: Int32, pSddl: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def SetSecurityDescriptor(self, sddl: Windows.Win32.Foundation.BSTR, flags: Int32) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskFolderCollection(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{79184a66-8664-423f-97f1-637356a5d812}')
    @commethod(7)
    def get_Count(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Item(self, index: Windows.Win32.System.Variant.VARIANT, ppFolder: POINTER(Windows.Win32.System.TaskScheduler.ITaskFolder_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get__NewEnum(self, ppEnum: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskHandler(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{839d7762-5121-4009-9234-4f0d19394f04}')
    @commethod(3)
    def Start(self, pHandlerServices: Windows.Win32.System.Com.IUnknown_head, data: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def Stop(self, pRetCode: POINTER(Windows.Win32.Foundation.HRESULT)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def Pause(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def Resume(self) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskHandlerStatus(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{eaec7a8f-27a0-4ddc-8675-14726a01a38a}')
    @commethod(3)
    def UpdateStatus(self, percentComplete: Int16, statusMessage: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def TaskCompleted(self, taskErrCode: Windows.Win32.Foundation.HRESULT) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskNamedValueCollection(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{b4ef826b-63c3-46e4-a504-ef69e4f7ea4d}')
    @commethod(7)
    def get_Count(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Item(self, index: Int32, ppPair: POINTER(Windows.Win32.System.TaskScheduler.ITaskNamedValuePair_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get__NewEnum(self, ppEnum: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def Create(self, name: Windows.Win32.Foundation.BSTR, value: Windows.Win32.Foundation.BSTR, ppPair: POINTER(Windows.Win32.System.TaskScheduler.ITaskNamedValuePair_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def Remove(self, index: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def Clear(self) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskNamedValuePair(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{39038068-2b46-4afd-8662-7bb6f868d221}')
    @commethod(7)
    def get_Name(self, pName: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_Name(self, name: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_Value(self, pValue: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_Value(self, value: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskScheduler(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{148bd527-a2ab-11ce-b11f-00aa00530503}')
    @commethod(3)
    def SetTargetComputer(self, pwszComputer: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def GetTargetComputer(self, ppwszComputer: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def Enum(self, ppEnumWorkItems: POINTER(Windows.Win32.System.TaskScheduler.IEnumWorkItems_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def Activate(self, pwszName: Windows.Win32.Foundation.PWSTR, riid: POINTER(Guid), ppUnk: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def Delete(self, pwszName: Windows.Win32.Foundation.PWSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def NewWorkItem(self, pwszTaskName: Windows.Win32.Foundation.PWSTR, rclsid: POINTER(Guid), riid: POINTER(Guid), ppUnk: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def AddWorkItem(self, pwszTaskName: Windows.Win32.Foundation.PWSTR, pWorkItem: Windows.Win32.System.TaskScheduler.IScheduledWorkItem_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def IsOfType(self, pwszName: Windows.Win32.Foundation.PWSTR, riid: POINTER(Guid)) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskService(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{2faba4c7-4da9-4013-9697-20cc3fd40f85}')
    @commethod(7)
    def GetFolder(self, path: Windows.Win32.Foundation.BSTR, ppFolder: POINTER(Windows.Win32.System.TaskScheduler.ITaskFolder_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def GetRunningTasks(self, flags: Int32, ppRunningTasks: POINTER(Windows.Win32.System.TaskScheduler.IRunningTaskCollection_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def NewTask(self, flags: UInt32, ppDefinition: POINTER(Windows.Win32.System.TaskScheduler.ITaskDefinition_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def Connect(self, serverName: Windows.Win32.System.Variant.VARIANT, user: Windows.Win32.System.Variant.VARIANT, domain: Windows.Win32.System.Variant.VARIANT, password: Windows.Win32.System.Variant.VARIANT) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_Connected(self, pConnected: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_TargetServer(self, pServer: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def get_ConnectedUser(self, pUser: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def get_ConnectedDomain(self, pDomain: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_HighestVersion(self, pVersion: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskSettings(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{8fd4711d-2d02-4c8c-87e3-eff699de127e}')
    @commethod(7)
    def get_AllowDemandStart(self, pAllowDemandStart: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_AllowDemandStart(self, allowDemandStart: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_RestartInterval(self, pRestartInterval: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_RestartInterval(self, restartInterval: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def get_RestartCount(self, pRestartCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def put_RestartCount(self, restartCount: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def get_MultipleInstances(self, pPolicy: POINTER(Windows.Win32.System.TaskScheduler.TASK_INSTANCES_POLICY)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def put_MultipleInstances(self, policy: Windows.Win32.System.TaskScheduler.TASK_INSTANCES_POLICY) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def get_StopIfGoingOnBatteries(self, pStopIfOnBatteries: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def put_StopIfGoingOnBatteries(self, stopIfOnBatteries: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def get_DisallowStartIfOnBatteries(self, pDisallowStart: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def put_DisallowStartIfOnBatteries(self, disallowStart: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def get_AllowHardTerminate(self, pAllowHardTerminate: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def put_AllowHardTerminate(self, allowHardTerminate: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def get_StartWhenAvailable(self, pStartWhenAvailable: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def put_StartWhenAvailable(self, startWhenAvailable: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def get_XmlText(self, pText: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def put_XmlText(self, text: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def get_RunOnlyIfNetworkAvailable(self, pRunOnlyIfNetworkAvailable: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def put_RunOnlyIfNetworkAvailable(self, runOnlyIfNetworkAvailable: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def get_ExecutionTimeLimit(self, pExecutionTimeLimit: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(28)
    def put_ExecutionTimeLimit(self, executionTimeLimit: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(29)
    def get_Enabled(self, pEnabled: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(30)
    def put_Enabled(self, enabled: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(31)
    def get_DeleteExpiredTaskAfter(self, pExpirationDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(32)
    def put_DeleteExpiredTaskAfter(self, expirationDelay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(33)
    def get_Priority(self, pPriority: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(34)
    def put_Priority(self, priority: Int32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(35)
    def get_Compatibility(self, pCompatLevel: POINTER(Windows.Win32.System.TaskScheduler.TASK_COMPATIBILITY)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(36)
    def put_Compatibility(self, compatLevel: Windows.Win32.System.TaskScheduler.TASK_COMPATIBILITY) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(37)
    def get_Hidden(self, pHidden: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(38)
    def put_Hidden(self, hidden: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(39)
    def get_IdleSettings(self, ppIdleSettings: POINTER(Windows.Win32.System.TaskScheduler.IIdleSettings_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(40)
    def put_IdleSettings(self, pIdleSettings: Windows.Win32.System.TaskScheduler.IIdleSettings_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(41)
    def get_RunOnlyIfIdle(self, pRunOnlyIfIdle: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(42)
    def put_RunOnlyIfIdle(self, runOnlyIfIdle: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(43)
    def get_WakeToRun(self, pWake: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(44)
    def put_WakeToRun(self, wake: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(45)
    def get_NetworkSettings(self, ppNetworkSettings: POINTER(Windows.Win32.System.TaskScheduler.INetworkSettings_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(46)
    def put_NetworkSettings(self, pNetworkSettings: Windows.Win32.System.TaskScheduler.INetworkSettings_head) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskSettings2(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{2c05c3f0-6eed-4c05-a15f-ed7d7a98a369}')
    @commethod(7)
    def get_DisallowStartOnRemoteAppSession(self, pDisallowStart: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def put_DisallowStartOnRemoteAppSession(self, disallowStart: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get_UseUnifiedSchedulingEngine(self, pUseUnifiedEngine: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def put_UseUnifiedSchedulingEngine(self, useUnifiedEngine: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskSettings3(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITaskSettings
    _iid_ = Guid('{0ad9d0d7-0c7f-4ebb-9a5f-d1c648dca528}')
    @commethod(47)
    def get_DisallowStartOnRemoteAppSession(self, pDisallowStart: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(48)
    def put_DisallowStartOnRemoteAppSession(self, disallowStart: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(49)
    def get_UseUnifiedSchedulingEngine(self, pUseUnifiedEngine: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(50)
    def put_UseUnifiedSchedulingEngine(self, useUnifiedEngine: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(51)
    def get_MaintenanceSettings(self, ppMaintenanceSettings: POINTER(Windows.Win32.System.TaskScheduler.IMaintenanceSettings_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(52)
    def put_MaintenanceSettings(self, pMaintenanceSettings: Windows.Win32.System.TaskScheduler.IMaintenanceSettings_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(53)
    def CreateMaintenanceSettings(self, ppMaintenanceSettings: POINTER(Windows.Win32.System.TaskScheduler.IMaintenanceSettings_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(54)
    def get_Volatile(self, pVolatile: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(55)
    def put_Volatile(self, Volatile: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskTrigger(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{148bd52b-a2ab-11ce-b11f-00aa00530503}')
    @commethod(3)
    def SetTrigger(self, pTrigger: POINTER(Windows.Win32.System.TaskScheduler.TASK_TRIGGER_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def GetTrigger(self, pTrigger: POINTER(Windows.Win32.System.TaskScheduler.TASK_TRIGGER_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def GetTriggerString(self, ppwszTrigger: POINTER(Windows.Win32.Foundation.PWSTR)) -> Windows.Win32.Foundation.HRESULT: ...
class ITaskVariables(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{3e4c9351-d966-4b8b-bb87-ceba68bb0107}')
    @commethod(3)
    def GetInput(self, pInput: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetOutput(self, input: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def GetContext(self, pContext: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
class ITimeTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{b45747e0-eba7-4276-9f29-85c5bb300006}')
    @commethod(20)
    def get_RandomDelay(self, pRandomDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_RandomDelay(self, randomDelay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class ITrigger(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{09941815-ea89-4b5b-89e0-2a773801fac3}')
    @commethod(7)
    def get_Type(self, pType: POINTER(Windows.Win32.System.TaskScheduler.TASK_TRIGGER_TYPE2)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Id(self, pId: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def put_Id(self, id: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def get_Repetition(self, ppRepeat: POINTER(Windows.Win32.System.TaskScheduler.IRepetitionPattern_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def put_Repetition(self, pRepeat: Windows.Win32.System.TaskScheduler.IRepetitionPattern_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def get_ExecutionTimeLimit(self, pTimeLimit: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def put_ExecutionTimeLimit(self, timelimit: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def get_StartBoundary(self, pStart: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def put_StartBoundary(self, start: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def get_EndBoundary(self, pEnd: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def put_EndBoundary(self, end: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def get_Enabled(self, pEnabled: POINTER(Windows.Win32.Foundation.VARIANT_BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def put_Enabled(self, enabled: Windows.Win32.Foundation.VARIANT_BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class ITriggerCollection(ComPtr):
    extends: Windows.Win32.System.Com.IDispatch
    _iid_ = Guid('{85df5081-1b24-4f32-878a-d9d14df4cb77}')
    @commethod(7)
    def get_Count(self, pCount: POINTER(Int32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def get_Item(self, index: Int32, ppTrigger: POINTER(Windows.Win32.System.TaskScheduler.ITrigger_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def get__NewEnum(self, ppEnum: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def Create(self, type: Windows.Win32.System.TaskScheduler.TASK_TRIGGER_TYPE2, ppTrigger: POINTER(Windows.Win32.System.TaskScheduler.ITrigger_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def Remove(self, index: Windows.Win32.System.Variant.VARIANT) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def Clear(self) -> Windows.Win32.Foundation.HRESULT: ...
class IWeeklyTrigger(ComPtr):
    extends: Windows.Win32.System.TaskScheduler.ITrigger
    _iid_ = Guid('{5038fc98-82ff-436d-8728-a512a57c9dc1}')
    @commethod(20)
    def get_DaysOfWeek(self, pDays: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def put_DaysOfWeek(self, days: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def get_WeeksInterval(self, pWeeks: POINTER(Int16)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def put_WeeksInterval(self, weeks: Int16) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def get_RandomDelay(self, pRandomDelay: POINTER(Windows.Win32.Foundation.BSTR)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def put_RandomDelay(self, randomDelay: Windows.Win32.Foundation.BSTR) -> Windows.Win32.Foundation.HRESULT: ...
class MONTHLYDATE(EasyCastStructure):
    rgfDays: UInt32
    rgfMonths: UInt16
class MONTHLYDOW(EasyCastStructure):
    wWhichWeek: UInt16
    rgfDaysOfTheWeek: UInt16
    rgfMonths: UInt16
TASKPAGE = Int32
TASKPAGE_TASK: TASKPAGE = 0
TASKPAGE_SCHEDULE: TASKPAGE = 1
TASKPAGE_SETTINGS: TASKPAGE = 2
TASK_ACTION_TYPE = Int32
TASK_ACTION_EXEC: TASK_ACTION_TYPE = 0
TASK_ACTION_COM_HANDLER: TASK_ACTION_TYPE = 5
TASK_ACTION_SEND_EMAIL: TASK_ACTION_TYPE = 6
TASK_ACTION_SHOW_MESSAGE: TASK_ACTION_TYPE = 7
TASK_COMPATIBILITY = Int32
TASK_COMPATIBILITY_AT: TASK_COMPATIBILITY = 0
TASK_COMPATIBILITY_V1: TASK_COMPATIBILITY = 1
TASK_COMPATIBILITY_V2: TASK_COMPATIBILITY = 2
TASK_COMPATIBILITY_V2_1: TASK_COMPATIBILITY = 3
TASK_COMPATIBILITY_V2_2: TASK_COMPATIBILITY = 4
TASK_COMPATIBILITY_V2_3: TASK_COMPATIBILITY = 5
TASK_COMPATIBILITY_V2_4: TASK_COMPATIBILITY = 6
TASK_CREATION = Int32
TASK_VALIDATE_ONLY: TASK_CREATION = 1
TASK_CREATE: TASK_CREATION = 2
TASK_UPDATE: TASK_CREATION = 4
TASK_CREATE_OR_UPDATE: TASK_CREATION = 6
TASK_DISABLE: TASK_CREATION = 8
TASK_DONT_ADD_PRINCIPAL_ACE: TASK_CREATION = 16
TASK_IGNORE_REGISTRATION_TRIGGERS: TASK_CREATION = 32
TASK_ENUM_FLAGS = Int32
TASK_ENUM_HIDDEN: TASK_ENUM_FLAGS = 1
TASK_INSTANCES_POLICY = Int32
TASK_INSTANCES_PARALLEL: TASK_INSTANCES_POLICY = 0
TASK_INSTANCES_QUEUE: TASK_INSTANCES_POLICY = 1
TASK_INSTANCES_IGNORE_NEW: TASK_INSTANCES_POLICY = 2
TASK_INSTANCES_STOP_EXISTING: TASK_INSTANCES_POLICY = 3
TASK_LOGON_TYPE = Int32
TASK_LOGON_NONE: TASK_LOGON_TYPE = 0
TASK_LOGON_PASSWORD: TASK_LOGON_TYPE = 1
TASK_LOGON_S4U: TASK_LOGON_TYPE = 2
TASK_LOGON_INTERACTIVE_TOKEN: TASK_LOGON_TYPE = 3
TASK_LOGON_GROUP: TASK_LOGON_TYPE = 4
TASK_LOGON_SERVICE_ACCOUNT: TASK_LOGON_TYPE = 5
TASK_LOGON_INTERACTIVE_TOKEN_OR_PASSWORD: TASK_LOGON_TYPE = 6
TASK_PROCESSTOKENSID_TYPE = Int32
TASK_PROCESSTOKENSID_NONE: TASK_PROCESSTOKENSID_TYPE = 0
TASK_PROCESSTOKENSID_UNRESTRICTED: TASK_PROCESSTOKENSID_TYPE = 1
TASK_PROCESSTOKENSID_DEFAULT: TASK_PROCESSTOKENSID_TYPE = 2
TASK_RUNLEVEL_TYPE = Int32
TASK_RUNLEVEL_LUA: TASK_RUNLEVEL_TYPE = 0
TASK_RUNLEVEL_HIGHEST: TASK_RUNLEVEL_TYPE = 1
TASK_RUN_FLAGS = Int32
TASK_RUN_NO_FLAGS: TASK_RUN_FLAGS = 0
TASK_RUN_AS_SELF: TASK_RUN_FLAGS = 1
TASK_RUN_IGNORE_CONSTRAINTS: TASK_RUN_FLAGS = 2
TASK_RUN_USE_SESSION_ID: TASK_RUN_FLAGS = 4
TASK_RUN_USER_SID: TASK_RUN_FLAGS = 8
TASK_SESSION_STATE_CHANGE_TYPE = Int32
TASK_CONSOLE_CONNECT: TASK_SESSION_STATE_CHANGE_TYPE = 1
TASK_CONSOLE_DISCONNECT: TASK_SESSION_STATE_CHANGE_TYPE = 2
TASK_REMOTE_CONNECT: TASK_SESSION_STATE_CHANGE_TYPE = 3
TASK_REMOTE_DISCONNECT: TASK_SESSION_STATE_CHANGE_TYPE = 4
TASK_SESSION_LOCK: TASK_SESSION_STATE_CHANGE_TYPE = 7
TASK_SESSION_UNLOCK: TASK_SESSION_STATE_CHANGE_TYPE = 8
TASK_STATE = Int32
TASK_STATE_UNKNOWN: TASK_STATE = 0
TASK_STATE_DISABLED: TASK_STATE = 1
TASK_STATE_QUEUED: TASK_STATE = 2
TASK_STATE_READY: TASK_STATE = 3
TASK_STATE_RUNNING: TASK_STATE = 4
class TASK_TRIGGER(EasyCastStructure):
    cbTriggerSize: UInt16
    Reserved1: UInt16
    wBeginYear: UInt16
    wBeginMonth: UInt16
    wBeginDay: UInt16
    wEndYear: UInt16
    wEndMonth: UInt16
    wEndDay: UInt16
    wStartHour: UInt16
    wStartMinute: UInt16
    MinutesDuration: UInt32
    MinutesInterval: UInt32
    rgFlags: UInt32
    TriggerType: Windows.Win32.System.TaskScheduler.TASK_TRIGGER_TYPE
    Type: Windows.Win32.System.TaskScheduler.TRIGGER_TYPE_UNION
    Reserved2: UInt16
    wRandomMinutesInterval: UInt16
TASK_TRIGGER_TYPE = Int32
TASK_TIME_TRIGGER_ONCE: TASK_TRIGGER_TYPE = 0
TASK_TIME_TRIGGER_DAILY: TASK_TRIGGER_TYPE = 1
TASK_TIME_TRIGGER_WEEKLY: TASK_TRIGGER_TYPE = 2
TASK_TIME_TRIGGER_MONTHLYDATE: TASK_TRIGGER_TYPE = 3
TASK_TIME_TRIGGER_MONTHLYDOW: TASK_TRIGGER_TYPE = 4
TASK_EVENT_TRIGGER_ON_IDLE: TASK_TRIGGER_TYPE = 5
TASK_EVENT_TRIGGER_AT_SYSTEMSTART: TASK_TRIGGER_TYPE = 6
TASK_EVENT_TRIGGER_AT_LOGON: TASK_TRIGGER_TYPE = 7
TASK_TRIGGER_TYPE2 = Int32
TASK_TRIGGER_EVENT: TASK_TRIGGER_TYPE2 = 0
TASK_TRIGGER_TIME: TASK_TRIGGER_TYPE2 = 1
TASK_TRIGGER_DAILY: TASK_TRIGGER_TYPE2 = 2
TASK_TRIGGER_WEEKLY: TASK_TRIGGER_TYPE2 = 3
TASK_TRIGGER_MONTHLY: TASK_TRIGGER_TYPE2 = 4
TASK_TRIGGER_MONTHLYDOW: TASK_TRIGGER_TYPE2 = 5
TASK_TRIGGER_IDLE: TASK_TRIGGER_TYPE2 = 6
TASK_TRIGGER_REGISTRATION: TASK_TRIGGER_TYPE2 = 7
TASK_TRIGGER_BOOT: TASK_TRIGGER_TYPE2 = 8
TASK_TRIGGER_LOGON: TASK_TRIGGER_TYPE2 = 9
TASK_TRIGGER_SESSION_STATE_CHANGE: TASK_TRIGGER_TYPE2 = 11
TASK_TRIGGER_CUSTOM_TRIGGER_01: TASK_TRIGGER_TYPE2 = 12
class TRIGGER_TYPE_UNION(EasyCastUnion):
    Daily: Windows.Win32.System.TaskScheduler.DAILY
    Weekly: Windows.Win32.System.TaskScheduler.WEEKLY
    MonthlyDate: Windows.Win32.System.TaskScheduler.MONTHLYDATE
    MonthlyDOW: Windows.Win32.System.TaskScheduler.MONTHLYDOW
TaskHandlerPS = Guid('{f2a69db7-da2c-4352-9066-86fee6dacac9}')
TaskHandlerStatusPS = Guid('{9f15266d-d7ba-48f0-93c1-e6895f6fe5ac}')
TaskScheduler = Guid('{0f87369f-a4e5-4cfc-bd3e-73e6154572dd}')
class WEEKLY(EasyCastStructure):
    WeeksInterval: UInt16
    rgfDaysOfTheWeek: UInt16
make_head(_module, 'DAILY')
make_head(_module, 'IAction')
make_head(_module, 'IActionCollection')
make_head(_module, 'IBootTrigger')
make_head(_module, 'IComHandlerAction')
make_head(_module, 'IDailyTrigger')
make_head(_module, 'IEmailAction')
make_head(_module, 'IEnumWorkItems')
make_head(_module, 'IEventTrigger')
make_head(_module, 'IExecAction')
make_head(_module, 'IExecAction2')
make_head(_module, 'IIdleSettings')
make_head(_module, 'IIdleTrigger')
make_head(_module, 'ILogonTrigger')
make_head(_module, 'IMaintenanceSettings')
make_head(_module, 'IMonthlyDOWTrigger')
make_head(_module, 'IMonthlyTrigger')
make_head(_module, 'INetworkSettings')
make_head(_module, 'IPrincipal')
make_head(_module, 'IPrincipal2')
make_head(_module, 'IProvideTaskPage')
make_head(_module, 'IRegisteredTask')
make_head(_module, 'IRegisteredTaskCollection')
make_head(_module, 'IRegistrationInfo')
make_head(_module, 'IRegistrationTrigger')
make_head(_module, 'IRepetitionPattern')
make_head(_module, 'IRunningTask')
make_head(_module, 'IRunningTaskCollection')
make_head(_module, 'IScheduledWorkItem')
make_head(_module, 'ISessionStateChangeTrigger')
make_head(_module, 'IShowMessageAction')
make_head(_module, 'ITask')
make_head(_module, 'ITaskDefinition')
make_head(_module, 'ITaskFolder')
make_head(_module, 'ITaskFolderCollection')
make_head(_module, 'ITaskHandler')
make_head(_module, 'ITaskHandlerStatus')
make_head(_module, 'ITaskNamedValueCollection')
make_head(_module, 'ITaskNamedValuePair')
make_head(_module, 'ITaskScheduler')
make_head(_module, 'ITaskService')
make_head(_module, 'ITaskSettings')
make_head(_module, 'ITaskSettings2')
make_head(_module, 'ITaskSettings3')
make_head(_module, 'ITaskTrigger')
make_head(_module, 'ITaskVariables')
make_head(_module, 'ITimeTrigger')
make_head(_module, 'ITrigger')
make_head(_module, 'ITriggerCollection')
make_head(_module, 'IWeeklyTrigger')
make_head(_module, 'MONTHLYDATE')
make_head(_module, 'MONTHLYDOW')
make_head(_module, 'TASK_TRIGGER')
make_head(_module, 'TRIGGER_TYPE_UNION')
make_head(_module, 'WEEKLY')
