from __future__ import annotations
from ctypes import POINTER
from Windows import ARCH, Boolean, Byte, Bytes, Char, ComPtr, Double, EasyCastStructure, EasyCastUnion, FAILED, Guid, Int16, Int32, Int64, IntPtr, MissingType, SByte, SUCCEEDED, Single, String, String, UInt16, UInt32, UInt64, UIntPtr, Void, VoidPtr, cfunctype, cfunctype_pointer, commethod, make_head, press, winfunctype, winfunctype_pointer
import Windows.Win32.Foundation
import Windows.Win32.System.Diagnostics.Debug.ActiveScript
import Windows.Win32.System.Js
import Windows.Win32.System.Variant
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
JS_SOURCE_CONTEXT_NONE: UInt64 = 18446744073709551615
if ARCH in 'X64,ARM64':
    @winfunctype('chakra.dll')
    def JsCreateContext(runtime: VoidPtr, debugApplication: Windows.Win32.System.Diagnostics.Debug.ActiveScript.IDebugApplication64_head, newContext: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
if ARCH in 'X64,ARM64':
    @winfunctype('chakra.dll')
    def JsStartDebugging(debugApplication: Windows.Win32.System.Diagnostics.Debug.ActiveScript.IDebugApplication64_head) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateRuntime(attributes: Windows.Win32.System.Js.JsRuntimeAttributes, runtimeVersion: Windows.Win32.System.Js.JsRuntimeVersion, threadService: Windows.Win32.System.Js.JsThreadServiceCallback, runtime: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCollectGarbage(runtime: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsDisposeRuntime(runtime: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetRuntimeMemoryUsage(runtime: VoidPtr, memoryUsage: POINTER(UIntPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetRuntimeMemoryLimit(runtime: VoidPtr, memoryLimit: POINTER(UIntPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetRuntimeMemoryLimit(runtime: VoidPtr, memoryLimit: UIntPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetRuntimeMemoryAllocationCallback(runtime: VoidPtr, callbackState: VoidPtr, allocationCallback: Windows.Win32.System.Js.JsMemoryAllocationCallback) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetRuntimeBeforeCollectCallback(runtime: VoidPtr, callbackState: VoidPtr, beforeCollectCallback: Windows.Win32.System.Js.JsBeforeCollectCallback) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsAddRef(ref: VoidPtr, count: POINTER(UInt32)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsRelease(ref: VoidPtr, count: POINTER(UInt32)) -> Windows.Win32.System.Js.JsErrorCode: ...
if ARCH in 'X86':
    @winfunctype('chakra.dll')
    def JsCreateContext(runtime: VoidPtr, debugApplication: Windows.Win32.System.Diagnostics.Debug.ActiveScript.IDebugApplication32_head, newContext: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetCurrentContext(currentContext: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetCurrentContext(context: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetRuntime(context: VoidPtr, runtime: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
if ARCH in 'X86':
    @winfunctype('chakra.dll')
    def JsStartDebugging(debugApplication: Windows.Win32.System.Diagnostics.Debug.ActiveScript.IDebugApplication32_head) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsIdle(nextIdleTick: POINTER(UInt32)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsParseScript(script: Windows.Win32.Foundation.PWSTR, sourceContext: UIntPtr, sourceUrl: Windows.Win32.Foundation.PWSTR, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsRunScript(script: Windows.Win32.Foundation.PWSTR, sourceContext: UIntPtr, sourceUrl: Windows.Win32.Foundation.PWSTR, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSerializeScript(script: Windows.Win32.Foundation.PWSTR, buffer: POINTER(Byte), bufferSize: POINTER(UInt32)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsParseSerializedScript(script: Windows.Win32.Foundation.PWSTR, buffer: POINTER(Byte), sourceContext: UIntPtr, sourceUrl: Windows.Win32.Foundation.PWSTR, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsRunSerializedScript(script: Windows.Win32.Foundation.PWSTR, buffer: POINTER(Byte), sourceContext: UIntPtr, sourceUrl: Windows.Win32.Foundation.PWSTR, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetPropertyIdFromName(name: Windows.Win32.Foundation.PWSTR, propertyId: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetPropertyNameFromId(propertyId: VoidPtr, name: POINTER(POINTER(UInt16))) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetUndefinedValue(undefinedValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetNullValue(nullValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetTrueValue(trueValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetFalseValue(falseValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsBoolToBoolean(value: Byte, booleanValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsBooleanToBool(value: VoidPtr, boolValue: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsConvertValueToBoolean(value: VoidPtr, booleanValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetValueType(value: VoidPtr, type: POINTER(Windows.Win32.System.Js.JsValueType)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsDoubleToNumber(doubleValue: Double, value: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsIntToNumber(intValue: Int32, value: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsNumberToDouble(value: VoidPtr, doubleValue: POINTER(Double)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsConvertValueToNumber(value: VoidPtr, numberValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetStringLength(stringValue: VoidPtr, length: POINTER(Int32)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsPointerToString(stringValue: Windows.Win32.Foundation.PWSTR, stringLength: UIntPtr, value: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsStringToPointer(value: VoidPtr, stringValue: POINTER(POINTER(UInt16)), stringLength: POINTER(UIntPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsConvertValueToString(value: VoidPtr, stringValue: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsVariantToValue(variant: POINTER(Windows.Win32.System.Variant.VARIANT_head), value: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsValueToVariant(object: VoidPtr, variant: POINTER(Windows.Win32.System.Variant.VARIANT_head)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetGlobalObject(globalObject: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateObject(object: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateExternalObject(data: VoidPtr, finalizeCallback: Windows.Win32.System.Js.JsFinalizeCallback, object: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsConvertValueToObject(value: VoidPtr, object: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetPrototype(object: VoidPtr, prototypeObject: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetPrototype(object: VoidPtr, prototypeObject: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetExtensionAllowed(object: VoidPtr, value: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsPreventExtension(object: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetProperty(object: VoidPtr, propertyId: VoidPtr, value: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetOwnPropertyDescriptor(object: VoidPtr, propertyId: VoidPtr, propertyDescriptor: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetOwnPropertyNames(object: VoidPtr, propertyNames: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetProperty(object: VoidPtr, propertyId: VoidPtr, value: VoidPtr, useStrictRules: Byte) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsHasProperty(object: VoidPtr, propertyId: VoidPtr, hasProperty: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsDeleteProperty(object: VoidPtr, propertyId: VoidPtr, useStrictRules: Byte, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsDefineProperty(object: VoidPtr, propertyId: VoidPtr, propertyDescriptor: VoidPtr, result: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsHasIndexedProperty(object: VoidPtr, index: VoidPtr, result: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetIndexedProperty(object: VoidPtr, index: VoidPtr, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetIndexedProperty(object: VoidPtr, index: VoidPtr, value: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsDeleteIndexedProperty(object: VoidPtr, index: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsEquals(object1: VoidPtr, object2: VoidPtr, result: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsStrictEquals(object1: VoidPtr, object2: VoidPtr, result: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsHasExternalData(object: VoidPtr, value: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetExternalData(object: VoidPtr, externalData: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetExternalData(object: VoidPtr, externalData: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateArray(length: UInt32, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCallFunction(function: VoidPtr, arguments: POINTER(VoidPtr), argumentCount: UInt16, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsConstructObject(function: VoidPtr, arguments: POINTER(VoidPtr), argumentCount: UInt16, result: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateFunction(nativeFunction: Windows.Win32.System.Js.JsNativeFunction, callbackState: VoidPtr, function: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateError(message: VoidPtr, error: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateRangeError(message: VoidPtr, error: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateReferenceError(message: VoidPtr, error: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateSyntaxError(message: VoidPtr, error: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateTypeError(message: VoidPtr, error: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsCreateURIError(message: VoidPtr, error: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsHasException(hasException: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsGetAndClearException(exception: POINTER(VoidPtr)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsSetException(exception: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsDisableRuntimeExecution(runtime: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsEnableRuntimeExecution(runtime: VoidPtr) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsIsRuntimeExecutionDisabled(runtime: VoidPtr, isDisabled: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsStartProfiling(callback: Windows.Win32.System.Diagnostics.Debug.ActiveScript.IActiveScriptProfilerCallback_head, eventMask: Windows.Win32.System.Diagnostics.Debug.ActiveScript.PROFILER_EVENT_MASK, context: UInt32) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsStopProfiling(reason: Windows.Win32.Foundation.HRESULT) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsEnumerateHeap(enumerator: POINTER(Windows.Win32.System.Diagnostics.Debug.ActiveScript.IActiveScriptProfilerHeapEnum_head)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype('chakra.dll')
def JsIsEnumeratingHeap(isEnumeratingHeap: POINTER(Boolean)) -> Windows.Win32.System.Js.JsErrorCode: ...
@winfunctype_pointer
def JsBackgroundWorkItemCallback(callbackState: VoidPtr) -> Void: ...
@winfunctype_pointer
def JsBeforeCollectCallback(callbackState: VoidPtr) -> Void: ...
JsErrorCode = UInt32
JsErrorCode_JsNoError: JsErrorCode = 0
JsErrorCode_JsErrorCategoryUsage: JsErrorCode = 65536
JsErrorCode_JsErrorInvalidArgument: JsErrorCode = 65537
JsErrorCode_JsErrorNullArgument: JsErrorCode = 65538
JsErrorCode_JsErrorNoCurrentContext: JsErrorCode = 65539
JsErrorCode_JsErrorInExceptionState: JsErrorCode = 65540
JsErrorCode_JsErrorNotImplemented: JsErrorCode = 65541
JsErrorCode_JsErrorWrongThread: JsErrorCode = 65542
JsErrorCode_JsErrorRuntimeInUse: JsErrorCode = 65543
JsErrorCode_JsErrorBadSerializedScript: JsErrorCode = 65544
JsErrorCode_JsErrorInDisabledState: JsErrorCode = 65545
JsErrorCode_JsErrorCannotDisableExecution: JsErrorCode = 65546
JsErrorCode_JsErrorHeapEnumInProgress: JsErrorCode = 65547
JsErrorCode_JsErrorArgumentNotObject: JsErrorCode = 65548
JsErrorCode_JsErrorInProfileCallback: JsErrorCode = 65549
JsErrorCode_JsErrorInThreadServiceCallback: JsErrorCode = 65550
JsErrorCode_JsErrorCannotSerializeDebugScript: JsErrorCode = 65551
JsErrorCode_JsErrorAlreadyDebuggingContext: JsErrorCode = 65552
JsErrorCode_JsErrorAlreadyProfilingContext: JsErrorCode = 65553
JsErrorCode_JsErrorIdleNotEnabled: JsErrorCode = 65554
JsErrorCode_JsErrorCategoryEngine: JsErrorCode = 131072
JsErrorCode_JsErrorOutOfMemory: JsErrorCode = 131073
JsErrorCode_JsErrorCategoryScript: JsErrorCode = 196608
JsErrorCode_JsErrorScriptException: JsErrorCode = 196609
JsErrorCode_JsErrorScriptCompile: JsErrorCode = 196610
JsErrorCode_JsErrorScriptTerminated: JsErrorCode = 196611
JsErrorCode_JsErrorScriptEvalDisabled: JsErrorCode = 196612
JsErrorCode_JsErrorCategoryFatal: JsErrorCode = 262144
JsErrorCode_JsErrorFatal: JsErrorCode = 262145
@winfunctype_pointer
def JsFinalizeCallback(data: VoidPtr) -> Void: ...
@winfunctype_pointer
def JsMemoryAllocationCallback(callbackState: VoidPtr, allocationEvent: Windows.Win32.System.Js.JsMemoryEventType, allocationSize: UIntPtr) -> Boolean: ...
JsMemoryEventType = Int32
JsMemoryEventType_JsMemoryAllocate: JsMemoryEventType = 0
JsMemoryEventType_JsMemoryFree: JsMemoryEventType = 1
JsMemoryEventType_JsMemoryFailure: JsMemoryEventType = 2
@winfunctype_pointer
def JsNativeFunction(callee: VoidPtr, isConstructCall: Boolean, arguments: POINTER(VoidPtr), argumentCount: UInt16, callbackState: VoidPtr) -> VoidPtr: ...
JsRuntimeAttributes = Int32
JsRuntimeAttributes_JsRuntimeAttributeNone: JsRuntimeAttributes = 0
JsRuntimeAttributes_JsRuntimeAttributeDisableBackgroundWork: JsRuntimeAttributes = 1
JsRuntimeAttributes_JsRuntimeAttributeAllowScriptInterrupt: JsRuntimeAttributes = 2
JsRuntimeAttributes_JsRuntimeAttributeEnableIdleProcessing: JsRuntimeAttributes = 4
JsRuntimeAttributes_JsRuntimeAttributeDisableNativeCodeGeneration: JsRuntimeAttributes = 8
JsRuntimeAttributes_JsRuntimeAttributeDisableEval: JsRuntimeAttributes = 16
JsRuntimeVersion = Int32
JsRuntimeVersion_JsRuntimeVersion10: JsRuntimeVersion = 0
JsRuntimeVersion_JsRuntimeVersion11: JsRuntimeVersion = 1
JsRuntimeVersion_JsRuntimeVersionEdge: JsRuntimeVersion = -1
@winfunctype_pointer
def JsThreadServiceCallback(callback: Windows.Win32.System.Js.JsBackgroundWorkItemCallback, callbackState: VoidPtr) -> Boolean: ...
JsValueType = Int32
JsValueType_JsUndefined: JsValueType = 0
JsValueType_JsNull: JsValueType = 1
JsValueType_JsNumber: JsValueType = 2
JsValueType_JsString: JsValueType = 3
JsValueType_JsBoolean: JsValueType = 4
JsValueType_JsObject: JsValueType = 5
JsValueType_JsFunction: JsValueType = 6
JsValueType_JsError: JsValueType = 7
JsValueType_JsArray: JsValueType = 8
make_head(_module, 'JsBackgroundWorkItemCallback')
make_head(_module, 'JsBeforeCollectCallback')
make_head(_module, 'JsFinalizeCallback')
make_head(_module, 'JsMemoryAllocationCallback')
make_head(_module, 'JsNativeFunction')
make_head(_module, 'JsThreadServiceCallback')
