from win32more import *
import win32more.NetworkManagement.WindowsConnectNow
import win32more.Foundation
import win32more.System.Com

def __getattr__(name):
    if name == "__path__":
        raise AttributeError()
    setattr(win32more.NetworkManagement.WindowsConnectNow, name, eval(f"_define_{name}()"))
    return getattr(win32more.NetworkManagement.WindowsConnectNow, name)
WCN_E_PEER_NOT_FOUND = -2147206143
WCN_E_AUTHENTICATION_FAILED = -2147206142
WCN_E_CONNECTION_REJECTED = -2147206141
WCN_E_SESSION_TIMEDOUT = -2147206140
WCN_E_PROTOCOL_ERROR = -2147206139
WCN_VALUE_DT_CATEGORY_COMPUTER = 1
WCN_VALUE_DT_CATEGORY_INPUT_DEVICE = 2
WCN_VALUE_DT_CATEGORY_PRINTER = 3
WCN_VALUE_DT_CATEGORY_CAMERA = 4
WCN_VALUE_DT_CATEGORY_STORAGE = 5
WCN_VALUE_DT_CATEGORY_NETWORK_INFRASTRUCTURE = 6
WCN_VALUE_DT_CATEGORY_DISPLAY = 7
WCN_VALUE_DT_CATEGORY_MULTIMEDIA_DEVICE = 8
WCN_VALUE_DT_CATEGORY_GAMING_DEVICE = 9
WCN_VALUE_DT_CATEGORY_TELEPHONE = 10
WCN_VALUE_DT_CATEGORY_AUDIO_DEVICE = 11
WCN_VALUE_DT_CATEGORY_OTHER = 255
WCN_VALUE_DT_SUBTYPE_WIFI_OUI = 5304836
WCN_VALUE_DT_SUBTYPE_COMPUTER__PC = 1
WCN_VALUE_DT_SUBTYPE_COMPUTER__SERVER = 2
WCN_VALUE_DT_SUBTYPE_COMPUTER__MEDIACENTER = 3
WCN_VALUE_DT_SUBTYPE_COMPUTER__ULTRAMOBILEPC = 4
WCN_VALUE_DT_SUBTYPE_COMPUTER__NOTEBOOK = 5
WCN_VALUE_DT_SUBTYPE_COMPUTER__DESKTOP = 6
WCN_VALUE_DT_SUBTYPE_COMPUTER__MID = 7
WCN_VALUE_DT_SUBTYPE_COMPUTER__NETBOOK = 8
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__KEYBOARD = 1
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__MOUSE = 2
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__JOYSTICK = 3
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__TRACKBALL = 4
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__GAMECONTROLLER = 5
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__REMOTE = 6
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__TOUCHSCREEN = 7
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__BIOMETRICREADER = 8
WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__BARCODEREADER = 9
WCN_VALUE_DT_SUBTYPE_PRINTER__PRINTER = 1
WCN_VALUE_DT_SUBTYPE_PRINTER__SCANNER = 2
WCN_VALUE_DT_SUBTYPE_PRINTER__FAX = 3
WCN_VALUE_DT_SUBTYPE_PRINTER__COPIER = 4
WCN_VALUE_DT_SUBTYPE_PRINTER__ALLINONE = 5
WCN_VALUE_DT_SUBTYPE_CAMERA__STILL_CAMERA = 1
WCN_VALUE_DT_SUBTYPE_CAMERA__VIDEO_CAMERA = 2
WCN_VALUE_DT_SUBTYPE_CAMERA__WEB_CAMERA = 3
WCN_VALUE_DT_SUBTYPE_CAMERA__SECURITY_CAMERA = 4
WCN_VALUE_DT_SUBTYPE_STORAGE__NAS = 1
WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__AP = 1
WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__ROUTER = 2
WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__SWITCH = 3
WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__GATEWAY = 4
WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__BRIDGE = 5
WCN_VALUE_DT_SUBTYPE_DISPLAY__TELEVISION = 1
WCN_VALUE_DT_SUBTYPE_DISPLAY__PICTURE_FRAME = 2
WCN_VALUE_DT_SUBTYPE_DISPLAY__PROJECTOR = 3
WCN_VALUE_DT_SUBTYPE_DISPLAY__MONITOR = 4
WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__DAR = 1
WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__PVR = 2
WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__MCX = 3
WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__SETTOPBOX = 4
WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__MEDIA_SERVER_ADAPT_EXT = 5
WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__PVP = 6
WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__XBOX = 1
WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__XBOX360 = 2
WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__PLAYSTATION = 3
WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__CONSOLE_ADAPT = 4
WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__PORTABLE = 5
WCN_VALUE_DT_SUBTYPE_TELEPHONE__WINDOWS_MOBILE = 1
WCN_VALUE_DT_SUBTYPE_TELEPHONE__PHONE_SINGLEMODE = 2
WCN_VALUE_DT_SUBTYPE_TELEPHONE__PHONE_DUALMODE = 3
WCN_VALUE_DT_SUBTYPE_TELEPHONE__SMARTPHONE_SINGLEMODE = 4
WCN_VALUE_DT_SUBTYPE_TELEPHONE__SMARTPHONE_DUALMODE = 5
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__TUNER_RECEIVER = 1
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__SPEAKERS = 2
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__PMP = 3
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__HEADSET = 4
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__HEADPHONES = 5
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__MICROPHONE = 6
WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__HOMETHEATER = 7
WCN_API_MAX_BUFFER_SIZE = 2096
WCN_MICROSOFT_VENDOR_ID = 311
WCN_NO_SUBTYPE = 4294967294
WCN_FLAG_DISCOVERY_VE = 1
WCN_FLAG_AUTHENTICATED_VE = 2
WCN_FLAG_ENCRYPTED_VE = 4
SID_WcnProvider = 'c100beca-d33a-4a4b-bf23-bbef4663d017'
WCN_ATTRIBUTE_TYPE = Int32
WCN_TYPE_AP_CHANNEL = 0
WCN_TYPE_ASSOCIATION_STATE = 1
WCN_TYPE_AUTHENTICATION_TYPE = 2
WCN_TYPE_AUTHENTICATION_TYPE_FLAGS = 3
WCN_TYPE_AUTHENTICATOR = 4
WCN_TYPE_CONFIG_METHODS = 5
WCN_TYPE_CONFIGURATION_ERROR = 6
WCN_TYPE_CONFIRMATION_URL4 = 7
WCN_TYPE_CONFIRMATION_URL6 = 8
WCN_TYPE_CONNECTION_TYPE = 9
WCN_TYPE_CONNECTION_TYPE_FLAGS = 10
WCN_TYPE_CREDENTIAL = 11
WCN_TYPE_DEVICE_NAME = 12
WCN_TYPE_DEVICE_PASSWORD_ID = 13
WCN_TYPE_E_HASH1 = 14
WCN_TYPE_E_HASH2 = 15
WCN_TYPE_E_SNONCE1 = 16
WCN_TYPE_E_SNONCE2 = 17
WCN_TYPE_ENCRYPTED_SETTINGS = 18
WCN_TYPE_ENCRYPTION_TYPE = 19
WCN_TYPE_ENCRYPTION_TYPE_FLAGS = 20
WCN_TYPE_ENROLLEE_NONCE = 21
WCN_TYPE_FEATURE_ID = 22
WCN_TYPE_IDENTITY = 23
WCN_TYPE_IDENTITY_PROOF = 24
WCN_TYPE_KEY_WRAP_AUTHENTICATOR = 25
WCN_TYPE_KEY_IDENTIFIER = 26
WCN_TYPE_MAC_ADDRESS = 27
WCN_TYPE_MANUFACTURER = 28
WCN_TYPE_MESSAGE_TYPE = 29
WCN_TYPE_MODEL_NAME = 30
WCN_TYPE_MODEL_NUMBER = 31
WCN_TYPE_NETWORK_INDEX = 32
WCN_TYPE_NETWORK_KEY = 33
WCN_TYPE_NETWORK_KEY_INDEX = 34
WCN_TYPE_NEW_DEVICE_NAME = 35
WCN_TYPE_NEW_PASSWORD = 36
WCN_TYPE_OOB_DEVICE_PASSWORD = 37
WCN_TYPE_OS_VERSION = 38
WCN_TYPE_POWER_LEVEL = 39
WCN_TYPE_PSK_CURRENT = 40
WCN_TYPE_PSK_MAX = 41
WCN_TYPE_PUBLIC_KEY = 42
WCN_TYPE_RADIO_ENABLED = 43
WCN_TYPE_REBOOT = 44
WCN_TYPE_REGISTRAR_CURRENT = 45
WCN_TYPE_REGISTRAR_ESTABLISHED = 46
WCN_TYPE_REGISTRAR_LIST = 47
WCN_TYPE_REGISTRAR_MAX = 48
WCN_TYPE_REGISTRAR_NONCE = 49
WCN_TYPE_REQUEST_TYPE = 50
WCN_TYPE_RESPONSE_TYPE = 51
WCN_TYPE_RF_BANDS = 52
WCN_TYPE_R_HASH1 = 53
WCN_TYPE_R_HASH2 = 54
WCN_TYPE_R_SNONCE1 = 55
WCN_TYPE_R_SNONCE2 = 56
WCN_TYPE_SELECTED_REGISTRAR = 57
WCN_TYPE_SERIAL_NUMBER = 58
WCN_TYPE_WI_FI_PROTECTED_SETUP_STATE = 59
WCN_TYPE_SSID = 60
WCN_TYPE_TOTAL_NETWORKS = 61
WCN_TYPE_UUID_E = 62
WCN_TYPE_UUID_R = 63
WCN_TYPE_VENDOR_EXTENSION = 64
WCN_TYPE_VERSION = 65
WCN_TYPE_X_509_CERTIFICATE_REQUEST = 66
WCN_TYPE_X_509_CERTIFICATE = 67
WCN_TYPE_EAP_IDENTITY = 68
WCN_TYPE_MESSAGE_COUNTER = 69
WCN_TYPE_PUBLIC_KEY_HASH = 70
WCN_TYPE_REKEY_KEY = 71
WCN_TYPE_KEY_LIFETIME = 72
WCN_TYPE_PERMITTED_CONFIG_METHODS = 73
WCN_TYPE_SELECTED_REGISTRAR_CONFIG_METHODS = 74
WCN_TYPE_PRIMARY_DEVICE_TYPE = 75
WCN_TYPE_SECONDARY_DEVICE_TYPE_LIST = 76
WCN_TYPE_PORTABLE_DEVICE = 77
WCN_TYPE_AP_SETUP_LOCKED = 78
WCN_TYPE_APPLICATION_EXTENSION = 79
WCN_TYPE_EAP_TYPE = 80
WCN_TYPE_INITIALIZATION_VECTOR = 81
WCN_TYPE_KEY_PROVIDED_AUTOMATICALLY = 82
WCN_TYPE_802_1X_ENABLED = 83
WCN_TYPE_APPSESSIONKEY = 84
WCN_TYPE_WEPTRANSMITKEY = 85
WCN_TYPE_UUID = 86
WCN_TYPE_PRIMARY_DEVICE_TYPE_CATEGORY = 87
WCN_TYPE_PRIMARY_DEVICE_TYPE_SUBCATEGORY_OUI = 88
WCN_TYPE_PRIMARY_DEVICE_TYPE_SUBCATEGORY = 89
WCN_TYPE_CURRENT_SSID = 90
WCN_TYPE_BSSID = 91
WCN_TYPE_DOT11_MAC_ADDRESS = 92
WCN_TYPE_AUTHORIZED_MACS = 93
WCN_TYPE_NETWORK_KEY_SHAREABLE = 94
WCN_TYPE_REQUEST_TO_ENROLL = 95
WCN_TYPE_REQUESTED_DEVICE_TYPE = 96
WCN_TYPE_SETTINGS_DELAY_TIME = 97
WCN_TYPE_VERSION2 = 98
WCN_TYPE_VENDOR_EXTENSION_WFA = 99
WCN_NUM_ATTRIBUTE_TYPES = 100
WCN_VALUE_TYPE_VERSION = Int32
WCN_VALUE_VERSION_1_0 = 16
WCN_VALUE_VERSION_2_0 = 32
WCN_VALUE_TYPE_BOOLEAN = Int32
WCN_VALUE_FALSE = 0
WCN_VALUE_TRUE = 1
WCN_VALUE_TYPE_ASSOCIATION_STATE = Int32
WCN_VALUE_AS_NOT_ASSOCIATED = 0
WCN_VALUE_AS_CONNECTION_SUCCESS = 1
WCN_VALUE_AS_CONFIGURATION_FAILURE = 2
WCN_VALUE_AS_ASSOCIATION_FAILURE = 3
WCN_VALUE_AS_IP_FAILURE = 4
WCN_VALUE_TYPE_AUTHENTICATION_TYPE = Int32
WCN_VALUE_AT_OPEN = 1
WCN_VALUE_AT_WPAPSK = 2
WCN_VALUE_AT_SHARED = 4
WCN_VALUE_AT_WPA = 8
WCN_VALUE_AT_WPA2 = 16
WCN_VALUE_AT_WPA2PSK = 32
WCN_VALUE_AT_WPAWPA2PSK_MIXED = 34
WCN_VALUE_TYPE_CONFIG_METHODS = Int32
WCN_VALUE_CM_USBA = 1
WCN_VALUE_CM_ETHERNET = 2
WCN_VALUE_CM_LABEL = 4
WCN_VALUE_CM_DISPLAY = 8
WCN_VALUE_CM_EXTERNAL_NFC = 16
WCN_VALUE_CM_INTEGRATED_NFC = 32
WCN_VALUE_CM_NFC_INTERFACE = 64
WCN_VALUE_CM_PUSHBUTTON = 128
WCN_VALUE_CM_KEYPAD = 256
WCN_VALUE_CM_VIRT_PUSHBUTTON = 640
WCN_VALUE_CM_PHYS_PUSHBUTTON = 1152
WCN_VALUE_CM_VIRT_DISPLAY = 8200
WCN_VALUE_CM_PHYS_DISPLAY = 16392
WCN_VALUE_TYPE_CONFIGURATION_ERROR = Int32
WCN_VALUE_CE_NO_ERROR = 0
WCN_VALUE_CE_OOB_INTERFACE_READ_ERROR = 1
WCN_VALUE_CE_DECRYPTION_CRC_FAILURE = 2
WCN_VALUE_CE_2_4_CHANNEL_NOT_SUPPORTED = 3
WCN_VALUE_CE_5_0_CHANNEL_NOT_SUPPORTED = 4
WCN_VALUE_CE_SIGNAL_TOO_WEAK = 5
WCN_VALUE_CE_NETWORK_AUTHENTICATION_FAILURE = 6
WCN_VALUE_CE_NETWORK_ASSOCIATION_FAILURE = 7
WCN_VALUE_CE_NO_DHCP_RESPONSE = 8
WCN_VALUE_CE_FAILED_DHCP_CONFIG = 9
WCN_VALUE_CE_IP_ADDRESS_CONFLICT = 10
WCN_VALUE_CE_COULD_NOT_CONNECT_TO_REGISTRAR = 11
WCN_VALUE_CE_MULTIPLE_PBC_SESSIONS_DETECTED = 12
WCN_VALUE_CE_ROGUE_ACTIVITY_SUSPECTED = 13
WCN_VALUE_CE_DEVICE_BUSY = 14
WCN_VALUE_CE_SETUP_LOCKED = 15
WCN_VALUE_CE_MESSAGE_TIMEOUT = 16
WCN_VALUE_CE_REGISTRATION_SESSION_TIMEOUT = 17
WCN_VALUE_CE_DEVICE_PASSWORD_AUTH_FAILURE = 18
WCN_VALUE_TYPE_CONNECTION_TYPE = Int32
WCN_VALUE_CT_ESS = 1
WCN_VALUE_CT_IBSS = 2
WCN_VALUE_TYPE_DEVICE_PASSWORD_ID = Int32
WCN_VALUE_DP_DEFAULT = 0
WCN_VALUE_DP_USER_SPECIFIED = 1
WCN_VALUE_DP_MACHINE_SPECIFIED = 2
WCN_VALUE_DP_REKEY = 3
WCN_VALUE_DP_PUSHBUTTON = 4
WCN_VALUE_DP_REGISTRAR_SPECIFIED = 5
WCN_VALUE_DP_NFC_CONNECTION_HANDOVER = 7
WCN_VALUE_DP_WFD_SERVICES = 8
WCN_VALUE_DP_OUTOFBAND_MIN = 16
WCN_VALUE_DP_OUTOFBAND_MAX = 65535
WCN_VALUE_TYPE_ENCRYPTION_TYPE = Int32
WCN_VALUE_ET_NONE = 1
WCN_VALUE_ET_WEP = 2
WCN_VALUE_ET_TKIP = 4
WCN_VALUE_ET_AES = 8
WCN_VALUE_ET_TKIP_AES_MIXED = 12
WCN_VALUE_TYPE_MESSAGE_TYPE = Int32
WCN_VALUE_MT_BEACON = 1
WCN_VALUE_MT_PROBE_REQUEST = 2
WCN_VALUE_MT_PROBE_RESPONSE = 3
WCN_VALUE_MT_M1 = 4
WCN_VALUE_MT_M2 = 5
WCN_VALUE_MT_M2D = 6
WCN_VALUE_MT_M3 = 7
WCN_VALUE_MT_M4 = 8
WCN_VALUE_MT_M5 = 9
WCN_VALUE_MT_M6 = 10
WCN_VALUE_MT_M7 = 11
WCN_VALUE_MT_M8 = 12
WCN_VALUE_MT_ACK = 13
WCN_VALUE_MT_NACK = 14
WCN_VALUE_MT_DONE = 15
WCN_VALUE_TYPE_REQUEST_TYPE = Int32
WCN_VALUE_ReqT_ENROLLEE_INFO = 0
WCN_VALUE_ReqT_ENROLLEE_OPEN_1X = 1
WCN_VALUE_ReqT_REGISTRAR = 2
WCN_VALUE_ReqT_MANAGER_REGISTRAR = 3
WCN_VALUE_TYPE_RESPONSE_TYPE = Int32
WCN_VALUE_RspT_ENROLLEE_INFO = 0
WCN_VALUE_RspT_ENROLLEE_OPEN_1X = 1
WCN_VALUE_RspT_REGISTRAR = 2
WCN_VALUE_RspT_AP = 3
WCN_VALUE_TYPE_RF_BANDS = Int32
WCN_VALUE_RB_24GHZ = 1
WCN_VALUE_RB_50GHZ = 2
WCN_VALUE_TYPE_WI_FI_PROTECTED_SETUP_STATE = Int32
WCN_VALUE_SS_RESERVED00 = 0
WCN_VALUE_SS_NOT_CONFIGURED = 1
WCN_VALUE_SS_CONFIGURED = 2
def _define_WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE_head():
    class WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE(Structure):
        pass
    return WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE
def _define_WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE():
    WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE = win32more.NetworkManagement.WindowsConnectNow.WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE_head
    WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE._pack_ = 1
    WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE._fields_ = [
        ("Category", UInt16),
        ("SubCategoryOUI", UInt32),
        ("SubCategory", UInt16),
    ]
    return WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE
WCNDeviceObject = Guid('c100bea7-d33a-4a4b-bf23-bbef4663d017')
WCN_PASSWORD_TYPE = Int32
WCN_PASSWORD_TYPE_PUSH_BUTTON = 0
WCN_PASSWORD_TYPE_PIN = 1
WCN_PASSWORD_TYPE_PIN_REGISTRAR_SPECIFIED = 2
WCN_PASSWORD_TYPE_OOB_SPECIFIED = 3
WCN_PASSWORD_TYPE_WFDS = 4
WCN_SESSION_STATUS = Int32
WCN_SESSION_STATUS_SUCCESS = 0
WCN_SESSION_STATUS_FAILURE_GENERIC = 1
WCN_SESSION_STATUS_FAILURE_TIMEOUT = 2
def _define_WCN_VENDOR_EXTENSION_SPEC_head():
    class WCN_VENDOR_EXTENSION_SPEC(Structure):
        pass
    return WCN_VENDOR_EXTENSION_SPEC
def _define_WCN_VENDOR_EXTENSION_SPEC():
    WCN_VENDOR_EXTENSION_SPEC = win32more.NetworkManagement.WindowsConnectNow.WCN_VENDOR_EXTENSION_SPEC_head
    WCN_VENDOR_EXTENSION_SPEC._fields_ = [
        ("VendorId", UInt32),
        ("SubType", UInt32),
        ("Index", UInt32),
        ("Flags", UInt32),
    ]
    return WCN_VENDOR_EXTENSION_SPEC
def _define_IWCNDevice_head():
    class IWCNDevice(win32more.System.Com.IUnknown_head):
        Guid = Guid('c100be9c-d33a-4a4b-bf23-bbef4663d017')
    return IWCNDevice
def _define_IWCNDevice():
    IWCNDevice = win32more.NetworkManagement.WindowsConnectNow.IWCNDevice_head
    IWCNDevice.SetPassword = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.NetworkManagement.WindowsConnectNow.WCN_PASSWORD_TYPE,UInt32,POINTER(Byte), use_last_error=False)(3, 'SetPassword', ((1, 'Type'),(1, 'dwPasswordLength'),(1, 'pbPassword'),)))
    IWCNDevice.Connect = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.NetworkManagement.WindowsConnectNow.IWCNConnectNotify_head, use_last_error=False)(4, 'Connect', ((1, 'pNotify'),)))
    IWCNDevice.GetAttribute = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.NetworkManagement.WindowsConnectNow.WCN_ATTRIBUTE_TYPE,UInt32,POINTER(Byte),POINTER(UInt32), use_last_error=False)(5, 'GetAttribute', ((1, 'AttributeType'),(1, 'dwMaxBufferSize'),(1, 'pbBuffer'),(1, 'pdwBufferUsed'),)))
    IWCNDevice.GetIntegerAttribute = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.NetworkManagement.WindowsConnectNow.WCN_ATTRIBUTE_TYPE,POINTER(UInt32), use_last_error=False)(6, 'GetIntegerAttribute', ((1, 'AttributeType'),(1, 'puInteger'),)))
    IWCNDevice.GetStringAttribute = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.NetworkManagement.WindowsConnectNow.WCN_ATTRIBUTE_TYPE,UInt32,POINTER(Char), use_last_error=False)(7, 'GetStringAttribute', ((1, 'AttributeType'),(1, 'cchMaxString'),(1, 'wszString'),)))
    IWCNDevice.GetNetworkProfile = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,UInt32,POINTER(Char), use_last_error=False)(8, 'GetNetworkProfile', ((1, 'cchMaxStringLength'),(1, 'wszProfile'),)))
    IWCNDevice.SetNetworkProfile = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.Foundation.PWSTR, use_last_error=False)(9, 'SetNetworkProfile', ((1, 'pszProfileXml'),)))
    IWCNDevice.GetVendorExtension = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,POINTER(win32more.NetworkManagement.WindowsConnectNow.WCN_VENDOR_EXTENSION_SPEC_head),UInt32,POINTER(Byte),POINTER(UInt32), use_last_error=False)(10, 'GetVendorExtension', ((1, 'pVendorExtSpec'),(1, 'dwMaxBufferSize'),(1, 'pbBuffer'),(1, 'pdwBufferUsed'),)))
    IWCNDevice.SetVendorExtension = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,POINTER(win32more.NetworkManagement.WindowsConnectNow.WCN_VENDOR_EXTENSION_SPEC_head),UInt32,POINTER(Byte), use_last_error=False)(11, 'SetVendorExtension', ((1, 'pVendorExtSpec'),(1, 'cbBuffer'),(1, 'pbBuffer'),)))
    IWCNDevice.Unadvise = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT, use_last_error=False)(12, 'Unadvise', ()))
    IWCNDevice.SetNFCPasswordParams = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.NetworkManagement.WindowsConnectNow.WCN_PASSWORD_TYPE,UInt32,UInt32,POINTER(Byte),UInt32,POINTER(Byte),UInt32,POINTER(Byte), use_last_error=False)(13, 'SetNFCPasswordParams', ((1, 'Type'),(1, 'dwOOBPasswordID'),(1, 'dwPasswordLength'),(1, 'pbPassword'),(1, 'dwRemotePublicKeyHashLength'),(1, 'pbRemotePublicKeyHash'),(1, 'dwDHKeyBlobLength'),(1, 'pbDHKeyBlob'),)))
    return IWCNDevice
def _define_IWCNConnectNotify_head():
    class IWCNConnectNotify(win32more.System.Com.IUnknown_head):
        Guid = Guid('c100be9f-d33a-4a4b-bf23-bbef4663d017')
    return IWCNConnectNotify
def _define_IWCNConnectNotify():
    IWCNConnectNotify = win32more.NetworkManagement.WindowsConnectNow.IWCNConnectNotify_head
    IWCNConnectNotify.ConnectSucceeded = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT, use_last_error=False)(3, 'ConnectSucceeded', ()))
    IWCNConnectNotify.ConnectFailed = COMMETHOD(WINFUNCTYPE(win32more.Foundation.HRESULT,win32more.Foundation.HRESULT, use_last_error=False)(4, 'ConnectFailed', ((1, 'hrFailure'),)))
    return IWCNConnectNotify
__all__ = [
    "WCN_E_PEER_NOT_FOUND",
    "WCN_E_AUTHENTICATION_FAILED",
    "WCN_E_CONNECTION_REJECTED",
    "WCN_E_SESSION_TIMEDOUT",
    "WCN_E_PROTOCOL_ERROR",
    "WCN_VALUE_DT_CATEGORY_COMPUTER",
    "WCN_VALUE_DT_CATEGORY_INPUT_DEVICE",
    "WCN_VALUE_DT_CATEGORY_PRINTER",
    "WCN_VALUE_DT_CATEGORY_CAMERA",
    "WCN_VALUE_DT_CATEGORY_STORAGE",
    "WCN_VALUE_DT_CATEGORY_NETWORK_INFRASTRUCTURE",
    "WCN_VALUE_DT_CATEGORY_DISPLAY",
    "WCN_VALUE_DT_CATEGORY_MULTIMEDIA_DEVICE",
    "WCN_VALUE_DT_CATEGORY_GAMING_DEVICE",
    "WCN_VALUE_DT_CATEGORY_TELEPHONE",
    "WCN_VALUE_DT_CATEGORY_AUDIO_DEVICE",
    "WCN_VALUE_DT_CATEGORY_OTHER",
    "WCN_VALUE_DT_SUBTYPE_WIFI_OUI",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__PC",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__SERVER",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__MEDIACENTER",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__ULTRAMOBILEPC",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__NOTEBOOK",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__DESKTOP",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__MID",
    "WCN_VALUE_DT_SUBTYPE_COMPUTER__NETBOOK",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__KEYBOARD",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__MOUSE",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__JOYSTICK",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__TRACKBALL",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__GAMECONTROLLER",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__REMOTE",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__TOUCHSCREEN",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__BIOMETRICREADER",
    "WCN_VALUE_DT_SUBTYPE_INPUT_DEVICE__BARCODEREADER",
    "WCN_VALUE_DT_SUBTYPE_PRINTER__PRINTER",
    "WCN_VALUE_DT_SUBTYPE_PRINTER__SCANNER",
    "WCN_VALUE_DT_SUBTYPE_PRINTER__FAX",
    "WCN_VALUE_DT_SUBTYPE_PRINTER__COPIER",
    "WCN_VALUE_DT_SUBTYPE_PRINTER__ALLINONE",
    "WCN_VALUE_DT_SUBTYPE_CAMERA__STILL_CAMERA",
    "WCN_VALUE_DT_SUBTYPE_CAMERA__VIDEO_CAMERA",
    "WCN_VALUE_DT_SUBTYPE_CAMERA__WEB_CAMERA",
    "WCN_VALUE_DT_SUBTYPE_CAMERA__SECURITY_CAMERA",
    "WCN_VALUE_DT_SUBTYPE_STORAGE__NAS",
    "WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__AP",
    "WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__ROUTER",
    "WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__SWITCH",
    "WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__GATEWAY",
    "WCN_VALUE_DT_SUBTYPE_NETWORK_INFRASTRUCUTURE__BRIDGE",
    "WCN_VALUE_DT_SUBTYPE_DISPLAY__TELEVISION",
    "WCN_VALUE_DT_SUBTYPE_DISPLAY__PICTURE_FRAME",
    "WCN_VALUE_DT_SUBTYPE_DISPLAY__PROJECTOR",
    "WCN_VALUE_DT_SUBTYPE_DISPLAY__MONITOR",
    "WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__DAR",
    "WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__PVR",
    "WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__MCX",
    "WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__SETTOPBOX",
    "WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__MEDIA_SERVER_ADAPT_EXT",
    "WCN_VALUE_DT_SUBTYPE_MULTIMEDIA_DEVICE__PVP",
    "WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__XBOX",
    "WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__XBOX360",
    "WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__PLAYSTATION",
    "WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__CONSOLE_ADAPT",
    "WCN_VALUE_DT_SUBTYPE_GAMING_DEVICE__PORTABLE",
    "WCN_VALUE_DT_SUBTYPE_TELEPHONE__WINDOWS_MOBILE",
    "WCN_VALUE_DT_SUBTYPE_TELEPHONE__PHONE_SINGLEMODE",
    "WCN_VALUE_DT_SUBTYPE_TELEPHONE__PHONE_DUALMODE",
    "WCN_VALUE_DT_SUBTYPE_TELEPHONE__SMARTPHONE_SINGLEMODE",
    "WCN_VALUE_DT_SUBTYPE_TELEPHONE__SMARTPHONE_DUALMODE",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__TUNER_RECEIVER",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__SPEAKERS",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__PMP",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__HEADSET",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__HEADPHONES",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__MICROPHONE",
    "WCN_VALUE_DT_SUBTYPE_AUDIO_DEVICE__HOMETHEATER",
    "WCN_API_MAX_BUFFER_SIZE",
    "WCN_MICROSOFT_VENDOR_ID",
    "WCN_NO_SUBTYPE",
    "WCN_FLAG_DISCOVERY_VE",
    "WCN_FLAG_AUTHENTICATED_VE",
    "WCN_FLAG_ENCRYPTED_VE",
    "SID_WcnProvider",
    "WCN_ATTRIBUTE_TYPE",
    "WCN_TYPE_AP_CHANNEL",
    "WCN_TYPE_ASSOCIATION_STATE",
    "WCN_TYPE_AUTHENTICATION_TYPE",
    "WCN_TYPE_AUTHENTICATION_TYPE_FLAGS",
    "WCN_TYPE_AUTHENTICATOR",
    "WCN_TYPE_CONFIG_METHODS",
    "WCN_TYPE_CONFIGURATION_ERROR",
    "WCN_TYPE_CONFIRMATION_URL4",
    "WCN_TYPE_CONFIRMATION_URL6",
    "WCN_TYPE_CONNECTION_TYPE",
    "WCN_TYPE_CONNECTION_TYPE_FLAGS",
    "WCN_TYPE_CREDENTIAL",
    "WCN_TYPE_DEVICE_NAME",
    "WCN_TYPE_DEVICE_PASSWORD_ID",
    "WCN_TYPE_E_HASH1",
    "WCN_TYPE_E_HASH2",
    "WCN_TYPE_E_SNONCE1",
    "WCN_TYPE_E_SNONCE2",
    "WCN_TYPE_ENCRYPTED_SETTINGS",
    "WCN_TYPE_ENCRYPTION_TYPE",
    "WCN_TYPE_ENCRYPTION_TYPE_FLAGS",
    "WCN_TYPE_ENROLLEE_NONCE",
    "WCN_TYPE_FEATURE_ID",
    "WCN_TYPE_IDENTITY",
    "WCN_TYPE_IDENTITY_PROOF",
    "WCN_TYPE_KEY_WRAP_AUTHENTICATOR",
    "WCN_TYPE_KEY_IDENTIFIER",
    "WCN_TYPE_MAC_ADDRESS",
    "WCN_TYPE_MANUFACTURER",
    "WCN_TYPE_MESSAGE_TYPE",
    "WCN_TYPE_MODEL_NAME",
    "WCN_TYPE_MODEL_NUMBER",
    "WCN_TYPE_NETWORK_INDEX",
    "WCN_TYPE_NETWORK_KEY",
    "WCN_TYPE_NETWORK_KEY_INDEX",
    "WCN_TYPE_NEW_DEVICE_NAME",
    "WCN_TYPE_NEW_PASSWORD",
    "WCN_TYPE_OOB_DEVICE_PASSWORD",
    "WCN_TYPE_OS_VERSION",
    "WCN_TYPE_POWER_LEVEL",
    "WCN_TYPE_PSK_CURRENT",
    "WCN_TYPE_PSK_MAX",
    "WCN_TYPE_PUBLIC_KEY",
    "WCN_TYPE_RADIO_ENABLED",
    "WCN_TYPE_REBOOT",
    "WCN_TYPE_REGISTRAR_CURRENT",
    "WCN_TYPE_REGISTRAR_ESTABLISHED",
    "WCN_TYPE_REGISTRAR_LIST",
    "WCN_TYPE_REGISTRAR_MAX",
    "WCN_TYPE_REGISTRAR_NONCE",
    "WCN_TYPE_REQUEST_TYPE",
    "WCN_TYPE_RESPONSE_TYPE",
    "WCN_TYPE_RF_BANDS",
    "WCN_TYPE_R_HASH1",
    "WCN_TYPE_R_HASH2",
    "WCN_TYPE_R_SNONCE1",
    "WCN_TYPE_R_SNONCE2",
    "WCN_TYPE_SELECTED_REGISTRAR",
    "WCN_TYPE_SERIAL_NUMBER",
    "WCN_TYPE_WI_FI_PROTECTED_SETUP_STATE",
    "WCN_TYPE_SSID",
    "WCN_TYPE_TOTAL_NETWORKS",
    "WCN_TYPE_UUID_E",
    "WCN_TYPE_UUID_R",
    "WCN_TYPE_VENDOR_EXTENSION",
    "WCN_TYPE_VERSION",
    "WCN_TYPE_X_509_CERTIFICATE_REQUEST",
    "WCN_TYPE_X_509_CERTIFICATE",
    "WCN_TYPE_EAP_IDENTITY",
    "WCN_TYPE_MESSAGE_COUNTER",
    "WCN_TYPE_PUBLIC_KEY_HASH",
    "WCN_TYPE_REKEY_KEY",
    "WCN_TYPE_KEY_LIFETIME",
    "WCN_TYPE_PERMITTED_CONFIG_METHODS",
    "WCN_TYPE_SELECTED_REGISTRAR_CONFIG_METHODS",
    "WCN_TYPE_PRIMARY_DEVICE_TYPE",
    "WCN_TYPE_SECONDARY_DEVICE_TYPE_LIST",
    "WCN_TYPE_PORTABLE_DEVICE",
    "WCN_TYPE_AP_SETUP_LOCKED",
    "WCN_TYPE_APPLICATION_EXTENSION",
    "WCN_TYPE_EAP_TYPE",
    "WCN_TYPE_INITIALIZATION_VECTOR",
    "WCN_TYPE_KEY_PROVIDED_AUTOMATICALLY",
    "WCN_TYPE_802_1X_ENABLED",
    "WCN_TYPE_APPSESSIONKEY",
    "WCN_TYPE_WEPTRANSMITKEY",
    "WCN_TYPE_UUID",
    "WCN_TYPE_PRIMARY_DEVICE_TYPE_CATEGORY",
    "WCN_TYPE_PRIMARY_DEVICE_TYPE_SUBCATEGORY_OUI",
    "WCN_TYPE_PRIMARY_DEVICE_TYPE_SUBCATEGORY",
    "WCN_TYPE_CURRENT_SSID",
    "WCN_TYPE_BSSID",
    "WCN_TYPE_DOT11_MAC_ADDRESS",
    "WCN_TYPE_AUTHORIZED_MACS",
    "WCN_TYPE_NETWORK_KEY_SHAREABLE",
    "WCN_TYPE_REQUEST_TO_ENROLL",
    "WCN_TYPE_REQUESTED_DEVICE_TYPE",
    "WCN_TYPE_SETTINGS_DELAY_TIME",
    "WCN_TYPE_VERSION2",
    "WCN_TYPE_VENDOR_EXTENSION_WFA",
    "WCN_NUM_ATTRIBUTE_TYPES",
    "WCN_VALUE_TYPE_VERSION",
    "WCN_VALUE_VERSION_1_0",
    "WCN_VALUE_VERSION_2_0",
    "WCN_VALUE_TYPE_BOOLEAN",
    "WCN_VALUE_FALSE",
    "WCN_VALUE_TRUE",
    "WCN_VALUE_TYPE_ASSOCIATION_STATE",
    "WCN_VALUE_AS_NOT_ASSOCIATED",
    "WCN_VALUE_AS_CONNECTION_SUCCESS",
    "WCN_VALUE_AS_CONFIGURATION_FAILURE",
    "WCN_VALUE_AS_ASSOCIATION_FAILURE",
    "WCN_VALUE_AS_IP_FAILURE",
    "WCN_VALUE_TYPE_AUTHENTICATION_TYPE",
    "WCN_VALUE_AT_OPEN",
    "WCN_VALUE_AT_WPAPSK",
    "WCN_VALUE_AT_SHARED",
    "WCN_VALUE_AT_WPA",
    "WCN_VALUE_AT_WPA2",
    "WCN_VALUE_AT_WPA2PSK",
    "WCN_VALUE_AT_WPAWPA2PSK_MIXED",
    "WCN_VALUE_TYPE_CONFIG_METHODS",
    "WCN_VALUE_CM_USBA",
    "WCN_VALUE_CM_ETHERNET",
    "WCN_VALUE_CM_LABEL",
    "WCN_VALUE_CM_DISPLAY",
    "WCN_VALUE_CM_EXTERNAL_NFC",
    "WCN_VALUE_CM_INTEGRATED_NFC",
    "WCN_VALUE_CM_NFC_INTERFACE",
    "WCN_VALUE_CM_PUSHBUTTON",
    "WCN_VALUE_CM_KEYPAD",
    "WCN_VALUE_CM_VIRT_PUSHBUTTON",
    "WCN_VALUE_CM_PHYS_PUSHBUTTON",
    "WCN_VALUE_CM_VIRT_DISPLAY",
    "WCN_VALUE_CM_PHYS_DISPLAY",
    "WCN_VALUE_TYPE_CONFIGURATION_ERROR",
    "WCN_VALUE_CE_NO_ERROR",
    "WCN_VALUE_CE_OOB_INTERFACE_READ_ERROR",
    "WCN_VALUE_CE_DECRYPTION_CRC_FAILURE",
    "WCN_VALUE_CE_2_4_CHANNEL_NOT_SUPPORTED",
    "WCN_VALUE_CE_5_0_CHANNEL_NOT_SUPPORTED",
    "WCN_VALUE_CE_SIGNAL_TOO_WEAK",
    "WCN_VALUE_CE_NETWORK_AUTHENTICATION_FAILURE",
    "WCN_VALUE_CE_NETWORK_ASSOCIATION_FAILURE",
    "WCN_VALUE_CE_NO_DHCP_RESPONSE",
    "WCN_VALUE_CE_FAILED_DHCP_CONFIG",
    "WCN_VALUE_CE_IP_ADDRESS_CONFLICT",
    "WCN_VALUE_CE_COULD_NOT_CONNECT_TO_REGISTRAR",
    "WCN_VALUE_CE_MULTIPLE_PBC_SESSIONS_DETECTED",
    "WCN_VALUE_CE_ROGUE_ACTIVITY_SUSPECTED",
    "WCN_VALUE_CE_DEVICE_BUSY",
    "WCN_VALUE_CE_SETUP_LOCKED",
    "WCN_VALUE_CE_MESSAGE_TIMEOUT",
    "WCN_VALUE_CE_REGISTRATION_SESSION_TIMEOUT",
    "WCN_VALUE_CE_DEVICE_PASSWORD_AUTH_FAILURE",
    "WCN_VALUE_TYPE_CONNECTION_TYPE",
    "WCN_VALUE_CT_ESS",
    "WCN_VALUE_CT_IBSS",
    "WCN_VALUE_TYPE_DEVICE_PASSWORD_ID",
    "WCN_VALUE_DP_DEFAULT",
    "WCN_VALUE_DP_USER_SPECIFIED",
    "WCN_VALUE_DP_MACHINE_SPECIFIED",
    "WCN_VALUE_DP_REKEY",
    "WCN_VALUE_DP_PUSHBUTTON",
    "WCN_VALUE_DP_REGISTRAR_SPECIFIED",
    "WCN_VALUE_DP_NFC_CONNECTION_HANDOVER",
    "WCN_VALUE_DP_WFD_SERVICES",
    "WCN_VALUE_DP_OUTOFBAND_MIN",
    "WCN_VALUE_DP_OUTOFBAND_MAX",
    "WCN_VALUE_TYPE_ENCRYPTION_TYPE",
    "WCN_VALUE_ET_NONE",
    "WCN_VALUE_ET_WEP",
    "WCN_VALUE_ET_TKIP",
    "WCN_VALUE_ET_AES",
    "WCN_VALUE_ET_TKIP_AES_MIXED",
    "WCN_VALUE_TYPE_MESSAGE_TYPE",
    "WCN_VALUE_MT_BEACON",
    "WCN_VALUE_MT_PROBE_REQUEST",
    "WCN_VALUE_MT_PROBE_RESPONSE",
    "WCN_VALUE_MT_M1",
    "WCN_VALUE_MT_M2",
    "WCN_VALUE_MT_M2D",
    "WCN_VALUE_MT_M3",
    "WCN_VALUE_MT_M4",
    "WCN_VALUE_MT_M5",
    "WCN_VALUE_MT_M6",
    "WCN_VALUE_MT_M7",
    "WCN_VALUE_MT_M8",
    "WCN_VALUE_MT_ACK",
    "WCN_VALUE_MT_NACK",
    "WCN_VALUE_MT_DONE",
    "WCN_VALUE_TYPE_REQUEST_TYPE",
    "WCN_VALUE_ReqT_ENROLLEE_INFO",
    "WCN_VALUE_ReqT_ENROLLEE_OPEN_1X",
    "WCN_VALUE_ReqT_REGISTRAR",
    "WCN_VALUE_ReqT_MANAGER_REGISTRAR",
    "WCN_VALUE_TYPE_RESPONSE_TYPE",
    "WCN_VALUE_RspT_ENROLLEE_INFO",
    "WCN_VALUE_RspT_ENROLLEE_OPEN_1X",
    "WCN_VALUE_RspT_REGISTRAR",
    "WCN_VALUE_RspT_AP",
    "WCN_VALUE_TYPE_RF_BANDS",
    "WCN_VALUE_RB_24GHZ",
    "WCN_VALUE_RB_50GHZ",
    "WCN_VALUE_TYPE_WI_FI_PROTECTED_SETUP_STATE",
    "WCN_VALUE_SS_RESERVED00",
    "WCN_VALUE_SS_NOT_CONFIGURED",
    "WCN_VALUE_SS_CONFIGURED",
    "WCN_VALUE_TYPE_PRIMARY_DEVICE_TYPE",
    "WCNDeviceObject",
    "WCN_PASSWORD_TYPE",
    "WCN_PASSWORD_TYPE_PUSH_BUTTON",
    "WCN_PASSWORD_TYPE_PIN",
    "WCN_PASSWORD_TYPE_PIN_REGISTRAR_SPECIFIED",
    "WCN_PASSWORD_TYPE_OOB_SPECIFIED",
    "WCN_PASSWORD_TYPE_WFDS",
    "WCN_SESSION_STATUS",
    "WCN_SESSION_STATUS_SUCCESS",
    "WCN_SESSION_STATUS_FAILURE_GENERIC",
    "WCN_SESSION_STATUS_FAILURE_TIMEOUT",
    "WCN_VENDOR_EXTENSION_SPEC",
    "IWCNDevice",
    "IWCNConnectNotify",
]
