from __future__ import annotations
from ctypes import c_void_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from typing import Generic, TypeVar
K = TypeVar('T')
T = TypeVar('T')
V = TypeVar('V')
TProgress = TypeVar('TProgress')
TResult = TypeVar('TResult')
TSender = TypeVar('TSender')
from Windows import ARCH, MissingType, c_char_p_no, c_wchar_p_no, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head, EasyCastStructure, EasyCastUnion, ComPtr
from Windows._winrt import WinRT_String, winrt_commethod, winrt_mixinmethod, winrt_classmethod, winrt_factorymethod, winrt_activatemethod
import Windows.Win32.System.WinRT
import Windows.Foundation
import Windows.Foundation.Collections
import Windows.Storage
import Windows.Storage.BulkAccess
import Windows.Storage.FileProperties
import Windows.Storage.Search
import Windows.Storage.Streams
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
class FileInformation(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Storage.BulkAccess.IStorageItemInformation
    _classid_ = 'Windows.Storage.BulkAccess.FileInformation'
    @winrt_mixinmethod
    def get_MusicProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.MusicProperties: ...
    @winrt_mixinmethod
    def get_VideoProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.VideoProperties: ...
    @winrt_mixinmethod
    def get_ImageProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.ImageProperties: ...
    @winrt_mixinmethod
    def get_DocumentProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.DocumentProperties: ...
    @winrt_mixinmethod
    def get_BasicProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.BasicProperties: ...
    @winrt_mixinmethod
    def get_Thumbnail(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.StorageItemThumbnail: ...
    @winrt_mixinmethod
    def add_ThumbnailUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, changedHandler: Windows.Foundation.TypedEventHandler[Windows.Storage.BulkAccess.IStorageItemInformation, Windows.Win32.System.WinRT.IInspectable_head]) -> Windows.Foundation.EventRegistrationToken: ...
    @winrt_mixinmethod
    def remove_ThumbnailUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, eventCookie: Windows.Foundation.EventRegistrationToken) -> Void: ...
    @winrt_mixinmethod
    def add_PropertiesUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, changedHandler: Windows.Foundation.TypedEventHandler[Windows.Storage.BulkAccess.IStorageItemInformation, Windows.Win32.System.WinRT.IInspectable_head]) -> Windows.Foundation.EventRegistrationToken: ...
    @winrt_mixinmethod
    def remove_PropertiesUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, eventCookie: Windows.Foundation.EventRegistrationToken) -> Void: ...
    @winrt_mixinmethod
    def get_FileType(self: Windows.Storage.IStorageFile) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_ContentType(self: Windows.Storage.IStorageFile) -> WinRT_String: ...
    @winrt_mixinmethod
    def OpenAsync(self: Windows.Storage.IStorageFile, accessMode: Windows.Storage.FileAccessMode) -> Windows.Foundation.IAsyncOperation[Windows.Storage.Streams.IRandomAccessStream]: ...
    @winrt_mixinmethod
    def OpenTransactedWriteAsync(self: Windows.Storage.IStorageFile) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageStreamTransaction]: ...
    @winrt_mixinmethod
    def CopyOverloadDefaultNameAndOptions(self: Windows.Storage.IStorageFile, destinationFolder: Windows.Storage.IStorageFolder) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFile]: ...
    @winrt_mixinmethod
    def CopyOverloadDefaultOptions(self: Windows.Storage.IStorageFile, destinationFolder: Windows.Storage.IStorageFolder, desiredNewName: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFile]: ...
    @winrt_mixinmethod
    def CopyOverload(self: Windows.Storage.IStorageFile, destinationFolder: Windows.Storage.IStorageFolder, desiredNewName: WinRT_String, option: Windows.Storage.NameCollisionOption) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFile]: ...
    @winrt_mixinmethod
    def CopyAndReplaceAsync(self: Windows.Storage.IStorageFile, fileToReplace: Windows.Storage.IStorageFile) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def MoveOverloadDefaultNameAndOptions(self: Windows.Storage.IStorageFile, destinationFolder: Windows.Storage.IStorageFolder) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def MoveOverloadDefaultOptions(self: Windows.Storage.IStorageFile, destinationFolder: Windows.Storage.IStorageFolder, desiredNewName: WinRT_String) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def MoveOverload(self: Windows.Storage.IStorageFile, destinationFolder: Windows.Storage.IStorageFolder, desiredNewName: WinRT_String, option: Windows.Storage.NameCollisionOption) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def MoveAndReplaceAsync(self: Windows.Storage.IStorageFile, fileToReplace: Windows.Storage.IStorageFile) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def RenameAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageItem, desiredName: WinRT_String) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def RenameAsync(self: Windows.Storage.IStorageItem, desiredName: WinRT_String, option: Windows.Storage.NameCollisionOption) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def DeleteAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageItem) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def DeleteAsync(self: Windows.Storage.IStorageItem, option: Windows.Storage.StorageDeleteOption) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def GetBasicPropertiesAsync(self: Windows.Storage.IStorageItem) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.BasicProperties]: ...
    @winrt_mixinmethod
    def get_Name(self: Windows.Storage.IStorageItem) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_Path(self: Windows.Storage.IStorageItem) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_Attributes(self: Windows.Storage.IStorageItem) -> Windows.Storage.FileAttributes: ...
    @winrt_mixinmethod
    def get_DateCreated(self: Windows.Storage.IStorageItem) -> Windows.Foundation.DateTime: ...
    @winrt_mixinmethod
    def IsOfType(self: Windows.Storage.IStorageItem, type: Windows.Storage.StorageItemTypes) -> Boolean: ...
    @winrt_mixinmethod
    def OpenReadAsync(self: Windows.Storage.Streams.IRandomAccessStreamReference) -> Windows.Foundation.IAsyncOperation[Windows.Storage.Streams.IRandomAccessStreamWithContentType]: ...
    @winrt_mixinmethod
    def OpenSequentialReadAsync(self: Windows.Storage.Streams.IInputStreamReference) -> Windows.Foundation.IAsyncOperation[Windows.Storage.Streams.IInputStream]: ...
    @winrt_mixinmethod
    def GetThumbnailAsyncOverloadDefaultSizeDefaultOptions(self: Windows.Storage.IStorageItemProperties, mode: Windows.Storage.FileProperties.ThumbnailMode) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.StorageItemThumbnail]: ...
    @winrt_mixinmethod
    def GetThumbnailAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageItemProperties, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedSize: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.StorageItemThumbnail]: ...
    @winrt_mixinmethod
    def GetThumbnailAsync(self: Windows.Storage.IStorageItemProperties, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedSize: UInt32, options: Windows.Storage.FileProperties.ThumbnailOptions) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.StorageItemThumbnail]: ...
    @winrt_mixinmethod
    def get_DisplayName(self: Windows.Storage.IStorageItemProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_DisplayType(self: Windows.Storage.IStorageItemProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_FolderRelativeId(self: Windows.Storage.IStorageItemProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_Properties(self: Windows.Storage.IStorageItemProperties) -> Windows.Storage.FileProperties.StorageItemContentProperties: ...
    @winrt_mixinmethod
    def GetParentAsync(self: Windows.Storage.IStorageItem2) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFolder]: ...
    @winrt_mixinmethod
    def IsEqual(self: Windows.Storage.IStorageItem2, item: Windows.Storage.IStorageItem) -> Boolean: ...
    @winrt_mixinmethod
    def get_Provider(self: Windows.Storage.IStorageItemPropertiesWithProvider) -> Windows.Storage.StorageProvider: ...
    @winrt_mixinmethod
    def get_IsAvailable(self: Windows.Storage.IStorageFilePropertiesWithAvailability) -> Boolean: ...
    @winrt_mixinmethod
    def OpenWithOptionsAsync(self: Windows.Storage.IStorageFile2, accessMode: Windows.Storage.FileAccessMode, options: Windows.Storage.StorageOpenOptions) -> Windows.Foundation.IAsyncOperation[Windows.Storage.Streams.IRandomAccessStream]: ...
    @winrt_mixinmethod
    def OpenTransactedWriteWithOptionsAsync(self: Windows.Storage.IStorageFile2, options: Windows.Storage.StorageOpenOptions) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageStreamTransaction]: ...
    MusicProperties = property(get_MusicProperties, None)
    VideoProperties = property(get_VideoProperties, None)
    ImageProperties = property(get_ImageProperties, None)
    DocumentProperties = property(get_DocumentProperties, None)
    BasicProperties = property(get_BasicProperties, None)
    Thumbnail = property(get_Thumbnail, None)
    FileType = property(get_FileType, None)
    ContentType = property(get_ContentType, None)
    Name = property(get_Name, None)
    Path = property(get_Path, None)
    Attributes = property(get_Attributes, None)
    DateCreated = property(get_DateCreated, None)
    DisplayName = property(get_DisplayName, None)
    DisplayType = property(get_DisplayType, None)
    FolderRelativeId = property(get_FolderRelativeId, None)
    Properties = property(get_Properties, None)
    Provider = property(get_Provider, None)
    IsAvailable = property(get_IsAvailable, None)
class FileInformationFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Storage.BulkAccess.IFileInformationFactory
    _classid_ = 'Windows.Storage.BulkAccess.FileInformationFactory'
    @winrt_factorymethod
    def CreateWithMode(cls: Windows.Storage.BulkAccess.IFileInformationFactoryFactory, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_factorymethod
    def CreateWithModeAndSize(cls: Windows.Storage.BulkAccess.IFileInformationFactoryFactory, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedThumbnailSize: UInt32) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_factorymethod
    def CreateWithModeAndSizeAndOptions(cls: Windows.Storage.BulkAccess.IFileInformationFactoryFactory, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedThumbnailSize: UInt32, thumbnailOptions: Windows.Storage.FileProperties.ThumbnailOptions) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_factorymethod
    def CreateWithModeAndSizeAndOptionsAndFlags(cls: Windows.Storage.BulkAccess.IFileInformationFactoryFactory, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedThumbnailSize: UInt32, thumbnailOptions: Windows.Storage.FileProperties.ThumbnailOptions, delayLoad: Boolean) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_mixinmethod
    def GetItemsAsync(self: Windows.Storage.BulkAccess.IFileInformationFactory, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.IStorageItemInformation]]: ...
    @winrt_mixinmethod
    def GetItemsAsyncDefaultStartAndCount(self: Windows.Storage.BulkAccess.IFileInformationFactory) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.IStorageItemInformation]]: ...
    @winrt_mixinmethod
    def GetFilesAsync(self: Windows.Storage.BulkAccess.IFileInformationFactory, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FileInformation]]: ...
    @winrt_mixinmethod
    def GetFilesAsyncDefaultStartAndCount(self: Windows.Storage.BulkAccess.IFileInformationFactory) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FileInformation]]: ...
    @winrt_mixinmethod
    def GetFoldersAsync(self: Windows.Storage.BulkAccess.IFileInformationFactory, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FolderInformation]]: ...
    @winrt_mixinmethod
    def GetFoldersAsyncDefaultStartAndCount(self: Windows.Storage.BulkAccess.IFileInformationFactory) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FolderInformation]]: ...
    @winrt_mixinmethod
    def GetVirtualizedItemsVector(self: Windows.Storage.BulkAccess.IFileInformationFactory) -> Windows.Win32.System.WinRT.IInspectable_head: ...
    @winrt_mixinmethod
    def GetVirtualizedFilesVector(self: Windows.Storage.BulkAccess.IFileInformationFactory) -> Windows.Win32.System.WinRT.IInspectable_head: ...
    @winrt_mixinmethod
    def GetVirtualizedFoldersVector(self: Windows.Storage.BulkAccess.IFileInformationFactory) -> Windows.Win32.System.WinRT.IInspectable_head: ...
class FolderInformation(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Storage.BulkAccess.IStorageItemInformation
    _classid_ = 'Windows.Storage.BulkAccess.FolderInformation'
    @winrt_mixinmethod
    def get_MusicProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.MusicProperties: ...
    @winrt_mixinmethod
    def get_VideoProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.VideoProperties: ...
    @winrt_mixinmethod
    def get_ImageProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.ImageProperties: ...
    @winrt_mixinmethod
    def get_DocumentProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.DocumentProperties: ...
    @winrt_mixinmethod
    def get_BasicProperties(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.BasicProperties: ...
    @winrt_mixinmethod
    def get_Thumbnail(self: Windows.Storage.BulkAccess.IStorageItemInformation) -> Windows.Storage.FileProperties.StorageItemThumbnail: ...
    @winrt_mixinmethod
    def add_ThumbnailUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, changedHandler: Windows.Foundation.TypedEventHandler[Windows.Storage.BulkAccess.IStorageItemInformation, Windows.Win32.System.WinRT.IInspectable_head]) -> Windows.Foundation.EventRegistrationToken: ...
    @winrt_mixinmethod
    def remove_ThumbnailUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, eventCookie: Windows.Foundation.EventRegistrationToken) -> Void: ...
    @winrt_mixinmethod
    def add_PropertiesUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, changedHandler: Windows.Foundation.TypedEventHandler[Windows.Storage.BulkAccess.IStorageItemInformation, Windows.Win32.System.WinRT.IInspectable_head]) -> Windows.Foundation.EventRegistrationToken: ...
    @winrt_mixinmethod
    def remove_PropertiesUpdated(self: Windows.Storage.BulkAccess.IStorageItemInformation, eventCookie: Windows.Foundation.EventRegistrationToken) -> Void: ...
    @winrt_mixinmethod
    def CreateFileAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageFolder, desiredName: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFile]: ...
    @winrt_mixinmethod
    def CreateFileAsync(self: Windows.Storage.IStorageFolder, desiredName: WinRT_String, options: Windows.Storage.CreationCollisionOption) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFile]: ...
    @winrt_mixinmethod
    def CreateFolderAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageFolder, desiredName: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFolder]: ...
    @winrt_mixinmethod
    def CreateFolderAsync(self: Windows.Storage.IStorageFolder, desiredName: WinRT_String, options: Windows.Storage.CreationCollisionOption) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFolder]: ...
    @winrt_mixinmethod
    def GetFileAsync(self: Windows.Storage.IStorageFolder, name: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFile]: ...
    @winrt_mixinmethod
    def GetFolderAsync(self: Windows.Storage.IStorageFolder, name: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFolder]: ...
    @winrt_mixinmethod
    def GetItemAsync(self: Windows.Storage.IStorageFolder, name: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.IStorageItem]: ...
    @winrt_mixinmethod
    def GetFilesAsyncOverloadDefaultOptionsStartAndCount(self: Windows.Storage.IStorageFolder) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.StorageFile]]: ...
    @winrt_mixinmethod
    def GetFoldersAsyncOverloadDefaultOptionsStartAndCount(self: Windows.Storage.IStorageFolder) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.StorageFolder]]: ...
    @winrt_mixinmethod
    def GetItemsAsyncOverloadDefaultStartAndCount(self: Windows.Storage.IStorageFolder) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.IStorageItem]]: ...
    @winrt_mixinmethod
    def RenameAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageItem, desiredName: WinRT_String) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def RenameAsync(self: Windows.Storage.IStorageItem, desiredName: WinRT_String, option: Windows.Storage.NameCollisionOption) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def DeleteAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageItem) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def DeleteAsync(self: Windows.Storage.IStorageItem, option: Windows.Storage.StorageDeleteOption) -> Windows.Foundation.IAsyncAction: ...
    @winrt_mixinmethod
    def GetBasicPropertiesAsync(self: Windows.Storage.IStorageItem) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.BasicProperties]: ...
    @winrt_mixinmethod
    def get_Name(self: Windows.Storage.IStorageItem) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_Path(self: Windows.Storage.IStorageItem) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_Attributes(self: Windows.Storage.IStorageItem) -> Windows.Storage.FileAttributes: ...
    @winrt_mixinmethod
    def get_DateCreated(self: Windows.Storage.IStorageItem) -> Windows.Foundation.DateTime: ...
    @winrt_mixinmethod
    def IsOfType(self: Windows.Storage.IStorageItem, type: Windows.Storage.StorageItemTypes) -> Boolean: ...
    @winrt_mixinmethod
    def GetThumbnailAsyncOverloadDefaultSizeDefaultOptions(self: Windows.Storage.IStorageItemProperties, mode: Windows.Storage.FileProperties.ThumbnailMode) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.StorageItemThumbnail]: ...
    @winrt_mixinmethod
    def GetThumbnailAsyncOverloadDefaultOptions(self: Windows.Storage.IStorageItemProperties, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedSize: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.StorageItemThumbnail]: ...
    @winrt_mixinmethod
    def GetThumbnailAsync(self: Windows.Storage.IStorageItemProperties, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedSize: UInt32, options: Windows.Storage.FileProperties.ThumbnailOptions) -> Windows.Foundation.IAsyncOperation[Windows.Storage.FileProperties.StorageItemThumbnail]: ...
    @winrt_mixinmethod
    def get_DisplayName(self: Windows.Storage.IStorageItemProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_DisplayType(self: Windows.Storage.IStorageItemProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_FolderRelativeId(self: Windows.Storage.IStorageItemProperties) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_Properties(self: Windows.Storage.IStorageItemProperties) -> Windows.Storage.FileProperties.StorageItemContentProperties: ...
    @winrt_mixinmethod
    def GetIndexedStateAsync(self: Windows.Storage.Search.IStorageFolderQueryOperations) -> Windows.Foundation.IAsyncOperation[Windows.Storage.Search.IndexedState]: ...
    @winrt_mixinmethod
    def CreateFileQueryOverloadDefault(self: Windows.Storage.Search.IStorageFolderQueryOperations) -> Windows.Storage.Search.StorageFileQueryResult: ...
    @winrt_mixinmethod
    def CreateFileQuery(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFileQuery) -> Windows.Storage.Search.StorageFileQueryResult: ...
    @winrt_mixinmethod
    def CreateFileQueryWithOptions(self: Windows.Storage.Search.IStorageFolderQueryOperations, queryOptions: Windows.Storage.Search.QueryOptions) -> Windows.Storage.Search.StorageFileQueryResult: ...
    @winrt_mixinmethod
    def CreateFolderQueryOverloadDefault(self: Windows.Storage.Search.IStorageFolderQueryOperations) -> Windows.Storage.Search.StorageFolderQueryResult: ...
    @winrt_mixinmethod
    def CreateFolderQuery(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFolderQuery) -> Windows.Storage.Search.StorageFolderQueryResult: ...
    @winrt_mixinmethod
    def CreateFolderQueryWithOptions(self: Windows.Storage.Search.IStorageFolderQueryOperations, queryOptions: Windows.Storage.Search.QueryOptions) -> Windows.Storage.Search.StorageFolderQueryResult: ...
    @winrt_mixinmethod
    def CreateItemQuery(self: Windows.Storage.Search.IStorageFolderQueryOperations) -> Windows.Storage.Search.StorageItemQueryResult: ...
    @winrt_mixinmethod
    def CreateItemQueryWithOptions(self: Windows.Storage.Search.IStorageFolderQueryOperations, queryOptions: Windows.Storage.Search.QueryOptions) -> Windows.Storage.Search.StorageItemQueryResult: ...
    @winrt_mixinmethod
    def GetFilesAsync(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFileQuery, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.StorageFile]]: ...
    @winrt_mixinmethod
    def GetFilesAsyncOverloadDefaultStartAndCount(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFileQuery) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.StorageFile]]: ...
    @winrt_mixinmethod
    def GetFoldersAsync(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFolderQuery, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.StorageFolder]]: ...
    @winrt_mixinmethod
    def GetFoldersAsyncOverloadDefaultStartAndCount(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFolderQuery) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.StorageFolder]]: ...
    @winrt_mixinmethod
    def GetItemsAsync(self: Windows.Storage.Search.IStorageFolderQueryOperations, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.IStorageItem]]: ...
    @winrt_mixinmethod
    def AreQueryOptionsSupported(self: Windows.Storage.Search.IStorageFolderQueryOperations, queryOptions: Windows.Storage.Search.QueryOptions) -> Boolean: ...
    @winrt_mixinmethod
    def IsCommonFolderQuerySupported(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFolderQuery) -> Boolean: ...
    @winrt_mixinmethod
    def IsCommonFileQuerySupported(self: Windows.Storage.Search.IStorageFolderQueryOperations, query: Windows.Storage.Search.CommonFileQuery) -> Boolean: ...
    @winrt_mixinmethod
    def GetParentAsync(self: Windows.Storage.IStorageItem2) -> Windows.Foundation.IAsyncOperation[Windows.Storage.StorageFolder]: ...
    @winrt_mixinmethod
    def IsEqual(self: Windows.Storage.IStorageItem2, item: Windows.Storage.IStorageItem) -> Boolean: ...
    @winrt_mixinmethod
    def TryGetItemAsync(self: Windows.Storage.IStorageFolder2, name: WinRT_String) -> Windows.Foundation.IAsyncOperation[Windows.Storage.IStorageItem]: ...
    @winrt_mixinmethod
    def get_Provider(self: Windows.Storage.IStorageItemPropertiesWithProvider) -> Windows.Storage.StorageProvider: ...
    MusicProperties = property(get_MusicProperties, None)
    VideoProperties = property(get_VideoProperties, None)
    ImageProperties = property(get_ImageProperties, None)
    DocumentProperties = property(get_DocumentProperties, None)
    BasicProperties = property(get_BasicProperties, None)
    Thumbnail = property(get_Thumbnail, None)
    Name = property(get_Name, None)
    Path = property(get_Path, None)
    Attributes = property(get_Attributes, None)
    DateCreated = property(get_DateCreated, None)
    DisplayName = property(get_DisplayName, None)
    DisplayType = property(get_DisplayType, None)
    FolderRelativeId = property(get_FolderRelativeId, None)
    Properties = property(get_Properties, None)
    Provider = property(get_Provider, None)
class IFileInformationFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Storage.BulkAccess.IFileInformationFactory'
    _iid_ = Guid('{401d88be-960f-4d6d-a7d0-1a3861e76c83}')
    @winrt_commethod(6)
    def GetItemsAsync(self, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.IStorageItemInformation]]: ...
    @winrt_commethod(7)
    def GetItemsAsyncDefaultStartAndCount(self) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.IStorageItemInformation]]: ...
    @winrt_commethod(8)
    def GetFilesAsync(self, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FileInformation]]: ...
    @winrt_commethod(9)
    def GetFilesAsyncDefaultStartAndCount(self) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FileInformation]]: ...
    @winrt_commethod(10)
    def GetFoldersAsync(self, startIndex: UInt32, maxItemsToRetrieve: UInt32) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FolderInformation]]: ...
    @winrt_commethod(11)
    def GetFoldersAsyncDefaultStartAndCount(self) -> Windows.Foundation.IAsyncOperation[Windows.Foundation.Collections.IVectorView[Windows.Storage.BulkAccess.FolderInformation]]: ...
    @winrt_commethod(12)
    def GetVirtualizedItemsVector(self) -> Windows.Win32.System.WinRT.IInspectable_head: ...
    @winrt_commethod(13)
    def GetVirtualizedFilesVector(self) -> Windows.Win32.System.WinRT.IInspectable_head: ...
    @winrt_commethod(14)
    def GetVirtualizedFoldersVector(self) -> Windows.Win32.System.WinRT.IInspectable_head: ...
class IFileInformationFactoryFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Storage.BulkAccess.IFileInformationFactoryFactory'
    _iid_ = Guid('{84ea0e7d-e4a2-4f00-8afa-af5e0f826bd5}')
    @winrt_commethod(6)
    def CreateWithMode(self, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_commethod(7)
    def CreateWithModeAndSize(self, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedThumbnailSize: UInt32) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_commethod(8)
    def CreateWithModeAndSizeAndOptions(self, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedThumbnailSize: UInt32, thumbnailOptions: Windows.Storage.FileProperties.ThumbnailOptions) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
    @winrt_commethod(9)
    def CreateWithModeAndSizeAndOptionsAndFlags(self, queryResult: Windows.Storage.Search.IStorageQueryResultBase, mode: Windows.Storage.FileProperties.ThumbnailMode, requestedThumbnailSize: UInt32, thumbnailOptions: Windows.Storage.FileProperties.ThumbnailOptions, delayLoad: Boolean) -> Windows.Storage.BulkAccess.FileInformationFactory: ...
class IStorageItemInformation(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Storage.BulkAccess.IStorageItemInformation'
    _iid_ = Guid('{87a5cb8b-8972-4f40-8de0-d86fb179d8fa}')
    @winrt_commethod(6)
    def get_MusicProperties(self) -> Windows.Storage.FileProperties.MusicProperties: ...
    @winrt_commethod(7)
    def get_VideoProperties(self) -> Windows.Storage.FileProperties.VideoProperties: ...
    @winrt_commethod(8)
    def get_ImageProperties(self) -> Windows.Storage.FileProperties.ImageProperties: ...
    @winrt_commethod(9)
    def get_DocumentProperties(self) -> Windows.Storage.FileProperties.DocumentProperties: ...
    @winrt_commethod(10)
    def get_BasicProperties(self) -> Windows.Storage.FileProperties.BasicProperties: ...
    @winrt_commethod(11)
    def get_Thumbnail(self) -> Windows.Storage.FileProperties.StorageItemThumbnail: ...
    @winrt_commethod(12)
    def add_ThumbnailUpdated(self, changedHandler: Windows.Foundation.TypedEventHandler[Windows.Storage.BulkAccess.IStorageItemInformation, Windows.Win32.System.WinRT.IInspectable_head]) -> Windows.Foundation.EventRegistrationToken: ...
    @winrt_commethod(13)
    def remove_ThumbnailUpdated(self, eventCookie: Windows.Foundation.EventRegistrationToken) -> Void: ...
    @winrt_commethod(14)
    def add_PropertiesUpdated(self, changedHandler: Windows.Foundation.TypedEventHandler[Windows.Storage.BulkAccess.IStorageItemInformation, Windows.Win32.System.WinRT.IInspectable_head]) -> Windows.Foundation.EventRegistrationToken: ...
    @winrt_commethod(15)
    def remove_PropertiesUpdated(self, eventCookie: Windows.Foundation.EventRegistrationToken) -> Void: ...
    MusicProperties = property(get_MusicProperties, None)
    VideoProperties = property(get_VideoProperties, None)
    ImageProperties = property(get_ImageProperties, None)
    DocumentProperties = property(get_DocumentProperties, None)
    BasicProperties = property(get_BasicProperties, None)
    Thumbnail = property(get_Thumbnail, None)
make_head(_module, 'FileInformation')
make_head(_module, 'FileInformationFactory')
make_head(_module, 'FolderInformation')
make_head(_module, 'IFileInformationFactory')
make_head(_module, 'IFileInformationFactoryFactory')
make_head(_module, 'IStorageItemInformation')
