from __future__ import annotations
from win32more._prelude import *
import win32more.Windows.Wdk.System.OfflineRegistry
import win32more.Windows.Win32.Foundation
import win32more.Windows.Win32.Security
@winfunctype('OFFREG.dll')
def ORGetVersion(pdwMajorVersion: POINTER(UInt32), pdwMinorVersion: POINTER(UInt32)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def OROpenHive(FilePath: win32more.Windows.Win32.Foundation.PWSTR, HORKey: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def OROpenHiveByHandle(FileHandle: win32more.Windows.Win32.Foundation.HANDLE, HORKey: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORCreateHive(HORKey: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORCloseHive(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORSaveHive(HORKey: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, HivePath: win32more.Windows.Win32.Foundation.PWSTR, OsMajorVersion: UInt32, OsMinorVersion: UInt32) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def OROpenKey(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpSubKey: win32more.Windows.Win32.Foundation.PWSTR, phkResult: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORCloseKey(KeyHandle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORCreateKey(KeyHandle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpSubKey: win32more.Windows.Win32.Foundation.PWSTR, lpClass: win32more.Windows.Win32.Foundation.PWSTR, dwOptions: UInt32, pSecurityDescriptor: win32more.Windows.Win32.Security.PSECURITY_DESCRIPTOR, phkResult: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY), pdwDisposition: POINTER(UInt32)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORDeleteKey(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpSubKey: win32more.Windows.Win32.Foundation.PWSTR) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORQueryInfoKey(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpClass: win32more.Windows.Win32.Foundation.PWSTR, lpcClass: POINTER(UInt32), lpcSubKeys: POINTER(UInt32), lpcMaxSubKeyLen: POINTER(UInt32), lpcMaxClassLen: POINTER(UInt32), lpcValues: POINTER(UInt32), lpcMaxValueNameLen: POINTER(UInt32), lpcMaxValueLen: POINTER(UInt32), lpcbSecurityDescriptor: POINTER(UInt32), lpftLastWriteTime: POINTER(win32more.Windows.Win32.Foundation.FILETIME)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def OREnumKey(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, dwIndex: UInt32, lpName: win32more.Windows.Win32.Foundation.PWSTR, lpcName: POINTER(UInt32), lpClass: win32more.Windows.Win32.Foundation.PWSTR, lpcClass: POINTER(UInt32), lpftLastWriteTime: POINTER(win32more.Windows.Win32.Foundation.FILETIME)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORGetKeySecurity(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, SecurityInformation: UInt32, pSecurityDescriptor: win32more.Windows.Win32.Security.PSECURITY_DESCRIPTOR, lpcbSecurityDescriptor: POINTER(UInt32)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORSetKeySecurity(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, SecurityInformation: UInt32, pSecurityDescriptor: win32more.Windows.Win32.Security.PSECURITY_DESCRIPTOR) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORGetVirtualFlags(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, pdwFlags: POINTER(UInt32)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORSetVirtualFlags(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, dwFlags: UInt32) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORDeleteValue(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpValueName: win32more.Windows.Win32.Foundation.PWSTR) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORGetValue(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpSubKey: win32more.Windows.Win32.Foundation.PWSTR, lpValue: win32more.Windows.Win32.Foundation.PWSTR, pdwType: POINTER(UInt32), pvData: VoidPtr, pcbData: POINTER(UInt32)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORSetValue(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpValueName: win32more.Windows.Win32.Foundation.PWSTR, dwType: UInt32, lpData: POINTER(Byte), cbData: UInt32) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def OREnumValue(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, dwIndex: UInt32, lpValueName: win32more.Windows.Win32.Foundation.PWSTR, lpcValueName: POINTER(UInt32), lpType: POINTER(UInt32), lpData: POINTER(Byte), lpcbData: POINTER(UInt32)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORRenameKey(Handle: win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY, lpNewName: win32more.Windows.Win32.Foundation.PWSTR) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORStart() -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORShutdown() -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
@winfunctype('OFFREG.dll')
def ORMergeHives(HiveHandles: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY), HiveCount: UInt32, phkResult: POINTER(win32more.Windows.Wdk.System.OfflineRegistry.ORHKEY)) -> win32more.Windows.Win32.Foundation.WIN32_ERROR: ...
ORHKEY = VoidPtr


make_ready(__name__)
