from __future__ import annotations
from ctypes import c_void_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from typing import Generic, TypeVar
K = TypeVar('T')
T = TypeVar('T')
V = TypeVar('V')
TProgress = TypeVar('TProgress')
TResult = TypeVar('TResult')
TSender = TypeVar('TSender')
from Windows import ARCH, MissingType, c_char_p_no, c_wchar_p_no, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head, EasyCastStructure, EasyCastUnion, ComPtr
from Windows._winrt import WinRT_String, winrt_commethod, winrt_mixinmethod, winrt_classmethod, winrt_factorymethod, winrt_activatemethod
import Windows.Win32.System.WinRT
import Windows.Data.Xml.Dom
import Windows.Foundation
import Windows.Foundation.Collections
import Windows.Security.Credentials
import Windows.Web.Syndication
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
class ISyndicationAttribute(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationAttribute'
    _iid_ = Guid('{71e8f969-526e-4001-9a91-e84f83161ab1}')
    @winrt_commethod(6)
    def get_Name(self: Windows.Web.Syndication.ISyndicationAttribute) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Name(self: Windows.Web.Syndication.ISyndicationAttribute, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Namespace(self: Windows.Web.Syndication.ISyndicationAttribute) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_Namespace(self: Windows.Web.Syndication.ISyndicationAttribute, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_Value(self: Windows.Web.Syndication.ISyndicationAttribute) -> WinRT_String: ...
    @winrt_commethod(11)
    def put_Value(self: Windows.Web.Syndication.ISyndicationAttribute, value: WinRT_String) -> Void: ...
    Name = property(get_Name, put_Name)
    Namespace = property(get_Namespace, put_Namespace)
    Value = property(get_Value, put_Value)
class ISyndicationAttributeFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationAttributeFactory'
    _iid_ = Guid('{624f1599-ed3e-420f-be86-640414886e4b}')
    @winrt_commethod(6)
    def CreateSyndicationAttribute(self: Windows.Web.Syndication.ISyndicationAttributeFactory, attributeName: WinRT_String, attributeNamespace: WinRT_String, attributeValue: WinRT_String) -> Windows.Web.Syndication.SyndicationAttribute: ...
class ISyndicationCategory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationCategory'
    _iid_ = Guid('{8715626f-0cba-4a7f-89ff-ecb5281423b6}')
    @winrt_commethod(6)
    def get_Label(self: Windows.Web.Syndication.ISyndicationCategory) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Label(self: Windows.Web.Syndication.ISyndicationCategory, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Scheme(self: Windows.Web.Syndication.ISyndicationCategory) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_Scheme(self: Windows.Web.Syndication.ISyndicationCategory, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_Term(self: Windows.Web.Syndication.ISyndicationCategory) -> WinRT_String: ...
    @winrt_commethod(11)
    def put_Term(self: Windows.Web.Syndication.ISyndicationCategory, value: WinRT_String) -> Void: ...
    Label = property(get_Label, put_Label)
    Scheme = property(get_Scheme, put_Scheme)
    Term = property(get_Term, put_Term)
class ISyndicationCategoryFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationCategoryFactory'
    _iid_ = Guid('{ab42802f-49e0-4525-8ab2-ab45c02528ff}')
    @winrt_commethod(6)
    def CreateSyndicationCategory(self: Windows.Web.Syndication.ISyndicationCategoryFactory, term: WinRT_String) -> Windows.Web.Syndication.SyndicationCategory: ...
    @winrt_commethod(7)
    def CreateSyndicationCategoryEx(self: Windows.Web.Syndication.ISyndicationCategoryFactory, term: WinRT_String, scheme: WinRT_String, label: WinRT_String) -> Windows.Web.Syndication.SyndicationCategory: ...
class ISyndicationClient(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationClient'
    _iid_ = Guid('{9e18a9b7-7249-4b45-b229-7df895a5a1f5}')
    @winrt_commethod(6)
    def get_ServerCredential(self: Windows.Web.Syndication.ISyndicationClient) -> Windows.Security.Credentials.PasswordCredential: ...
    @winrt_commethod(7)
    def put_ServerCredential(self: Windows.Web.Syndication.ISyndicationClient, value: Windows.Security.Credentials.PasswordCredential) -> Void: ...
    @winrt_commethod(8)
    def get_ProxyCredential(self: Windows.Web.Syndication.ISyndicationClient) -> Windows.Security.Credentials.PasswordCredential: ...
    @winrt_commethod(9)
    def put_ProxyCredential(self: Windows.Web.Syndication.ISyndicationClient, value: Windows.Security.Credentials.PasswordCredential) -> Void: ...
    @winrt_commethod(10)
    def get_MaxResponseBufferSize(self: Windows.Web.Syndication.ISyndicationClient) -> UInt32: ...
    @winrt_commethod(11)
    def put_MaxResponseBufferSize(self: Windows.Web.Syndication.ISyndicationClient, value: UInt32) -> Void: ...
    @winrt_commethod(12)
    def get_Timeout(self: Windows.Web.Syndication.ISyndicationClient) -> UInt32: ...
    @winrt_commethod(13)
    def put_Timeout(self: Windows.Web.Syndication.ISyndicationClient, value: UInt32) -> Void: ...
    @winrt_commethod(14)
    def get_BypassCacheOnRetrieve(self: Windows.Web.Syndication.ISyndicationClient) -> Boolean: ...
    @winrt_commethod(15)
    def put_BypassCacheOnRetrieve(self: Windows.Web.Syndication.ISyndicationClient, value: Boolean) -> Void: ...
    @winrt_commethod(16)
    def SetRequestHeader(self: Windows.Web.Syndication.ISyndicationClient, name: WinRT_String, value: WinRT_String) -> Void: ...
    @winrt_commethod(17)
    def RetrieveFeedAsync(self: Windows.Web.Syndication.ISyndicationClient, uri: Windows.Foundation.Uri) -> Windows.Foundation.IAsyncOperationWithProgress[Windows.Web.Syndication.SyndicationFeed, Windows.Web.Syndication.RetrievalProgress]: ...
    ServerCredential = property(get_ServerCredential, put_ServerCredential)
    ProxyCredential = property(get_ProxyCredential, put_ProxyCredential)
    MaxResponseBufferSize = property(get_MaxResponseBufferSize, put_MaxResponseBufferSize)
    Timeout = property(get_Timeout, put_Timeout)
    BypassCacheOnRetrieve = property(get_BypassCacheOnRetrieve, put_BypassCacheOnRetrieve)
class ISyndicationClientFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationClientFactory'
    _iid_ = Guid('{2ec4b32c-a79b-4114-b29a-05dffbafb9a4}')
    @winrt_commethod(6)
    def CreateSyndicationClient(self: Windows.Web.Syndication.ISyndicationClientFactory, serverCredential: Windows.Security.Credentials.PasswordCredential) -> Windows.Web.Syndication.SyndicationClient: ...
class ISyndicationContent(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationContent'
    _iid_ = Guid('{4641fefe-0e55-40d0-b8d0-6a2ccba9fc7c}')
    @winrt_commethod(6)
    def get_SourceUri(self: Windows.Web.Syndication.ISyndicationContent) -> Windows.Foundation.Uri: ...
    @winrt_commethod(7)
    def put_SourceUri(self: Windows.Web.Syndication.ISyndicationContent, value: Windows.Foundation.Uri) -> Void: ...
    SourceUri = property(get_SourceUri, put_SourceUri)
class ISyndicationContentFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationContentFactory'
    _iid_ = Guid('{3d2fbb93-9520-4173-9388-7e2df324a8a0}')
    @winrt_commethod(6)
    def CreateSyndicationContent(self: Windows.Web.Syndication.ISyndicationContentFactory, text: WinRT_String, type: Windows.Web.Syndication.SyndicationTextType) -> Windows.Web.Syndication.SyndicationContent: ...
    @winrt_commethod(7)
    def CreateSyndicationContentWithSourceUri(self: Windows.Web.Syndication.ISyndicationContentFactory, sourceUri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationContent: ...
class ISyndicationErrorStatics(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationErrorStatics'
    _iid_ = Guid('{1fbb2361-45c7-4833-8aa0-be5f3b58a7f4}')
    @winrt_commethod(6)
    def GetStatus(self: Windows.Web.Syndication.ISyndicationErrorStatics, hresult: Int32) -> Windows.Web.Syndication.SyndicationErrorStatus: ...
class ISyndicationFeed(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationFeed'
    _iid_ = Guid('{7ffe3cd2-5b66-4d62-8403-1bc10d910d6b}')
    @winrt_commethod(6)
    def get_Authors(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_commethod(7)
    def get_Categories(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationCategory]: ...
    @winrt_commethod(8)
    def get_Contributors(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_commethod(9)
    def get_Generator(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.SyndicationGenerator: ...
    @winrt_commethod(10)
    def put_Generator(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.SyndicationGenerator) -> Void: ...
    @winrt_commethod(11)
    def get_IconUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_commethod(12)
    def put_IconUri(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(13)
    def get_Id(self: Windows.Web.Syndication.ISyndicationFeed) -> WinRT_String: ...
    @winrt_commethod(14)
    def put_Id(self: Windows.Web.Syndication.ISyndicationFeed, value: WinRT_String) -> Void: ...
    @winrt_commethod(15)
    def get_Items(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationItem]: ...
    @winrt_commethod(16)
    def get_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.DateTime: ...
    @winrt_commethod(17)
    def put_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Foundation.DateTime) -> Void: ...
    @winrt_commethod(18)
    def get_Links(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationLink]: ...
    @winrt_commethod(19)
    def get_ImageUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_commethod(20)
    def put_ImageUri(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(21)
    def get_Rights(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_commethod(22)
    def put_Rights(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_commethod(23)
    def get_Subtitle(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_commethod(24)
    def put_Subtitle(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_commethod(25)
    def get_Title(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_commethod(26)
    def put_Title(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_commethod(27)
    def get_FirstUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_commethod(28)
    def get_LastUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_commethod(29)
    def get_NextUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_commethod(30)
    def get_PreviousUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_commethod(31)
    def get_SourceFormat(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.SyndicationFormat: ...
    @winrt_commethod(32)
    def Load(self: Windows.Web.Syndication.ISyndicationFeed, feed: WinRT_String) -> Void: ...
    @winrt_commethod(33)
    def LoadFromXml(self: Windows.Web.Syndication.ISyndicationFeed, feedDocument: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    Authors = property(get_Authors, None)
    Categories = property(get_Categories, None)
    Contributors = property(get_Contributors, None)
    Generator = property(get_Generator, put_Generator)
    IconUri = property(get_IconUri, put_IconUri)
    Id = property(get_Id, put_Id)
    Items = property(get_Items, None)
    LastUpdatedTime = property(get_LastUpdatedTime, put_LastUpdatedTime)
    Links = property(get_Links, None)
    ImageUri = property(get_ImageUri, put_ImageUri)
    Rights = property(get_Rights, put_Rights)
    Subtitle = property(get_Subtitle, put_Subtitle)
    Title = property(get_Title, put_Title)
    FirstUri = property(get_FirstUri, None)
    LastUri = property(get_LastUri, None)
    NextUri = property(get_NextUri, None)
    PreviousUri = property(get_PreviousUri, None)
    SourceFormat = property(get_SourceFormat, None)
class ISyndicationFeedFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationFeedFactory'
    _iid_ = Guid('{23472232-8be9-48b7-8934-6205131d9357}')
    @winrt_commethod(6)
    def CreateSyndicationFeed(self: Windows.Web.Syndication.ISyndicationFeedFactory, title: WinRT_String, subtitle: WinRT_String, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationFeed: ...
class ISyndicationGenerator(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationGenerator'
    _iid_ = Guid('{9768b379-fb2b-4f6d-b41c-088a5868825c}')
    @winrt_commethod(6)
    def get_Text(self: Windows.Web.Syndication.ISyndicationGenerator) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Text(self: Windows.Web.Syndication.ISyndicationGenerator, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Uri(self: Windows.Web.Syndication.ISyndicationGenerator) -> Windows.Foundation.Uri: ...
    @winrt_commethod(9)
    def put_Uri(self: Windows.Web.Syndication.ISyndicationGenerator, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(10)
    def get_Version(self: Windows.Web.Syndication.ISyndicationGenerator) -> WinRT_String: ...
    @winrt_commethod(11)
    def put_Version(self: Windows.Web.Syndication.ISyndicationGenerator, value: WinRT_String) -> Void: ...
    Text = property(get_Text, put_Text)
    Uri = property(get_Uri, put_Uri)
    Version = property(get_Version, put_Version)
class ISyndicationGeneratorFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationGeneratorFactory'
    _iid_ = Guid('{a34083e3-1e26-4dbc-ba9d-1ab84beff97b}')
    @winrt_commethod(6)
    def CreateSyndicationGenerator(self: Windows.Web.Syndication.ISyndicationGeneratorFactory, text: WinRT_String) -> Windows.Web.Syndication.SyndicationGenerator: ...
class ISyndicationItem(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationItem'
    _iid_ = Guid('{548db883-c384-45c1-8ae8-a378c4ec486c}')
    @winrt_commethod(6)
    def get_Authors(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_commethod(7)
    def get_Categories(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationCategory]: ...
    @winrt_commethod(8)
    def get_Contributors(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_commethod(9)
    def get_Content(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.SyndicationContent: ...
    @winrt_commethod(10)
    def put_Content(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.SyndicationContent) -> Void: ...
    @winrt_commethod(11)
    def get_Id(self: Windows.Web.Syndication.ISyndicationItem) -> WinRT_String: ...
    @winrt_commethod(12)
    def put_Id(self: Windows.Web.Syndication.ISyndicationItem, value: WinRT_String) -> Void: ...
    @winrt_commethod(13)
    def get_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.DateTime: ...
    @winrt_commethod(14)
    def put_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Foundation.DateTime) -> Void: ...
    @winrt_commethod(15)
    def get_Links(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationLink]: ...
    @winrt_commethod(16)
    def get_PublishedDate(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.DateTime: ...
    @winrt_commethod(17)
    def put_PublishedDate(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Foundation.DateTime) -> Void: ...
    @winrt_commethod(18)
    def get_Rights(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_commethod(19)
    def put_Rights(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_commethod(20)
    def get_Source(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.SyndicationFeed: ...
    @winrt_commethod(21)
    def put_Source(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.SyndicationFeed) -> Void: ...
    @winrt_commethod(22)
    def get_Summary(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_commethod(23)
    def put_Summary(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_commethod(24)
    def get_Title(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_commethod(25)
    def put_Title(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_commethod(26)
    def get_CommentsUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_commethod(27)
    def put_CommentsUri(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(28)
    def get_EditUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_commethod(29)
    def get_EditMediaUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_commethod(30)
    def get_ETag(self: Windows.Web.Syndication.ISyndicationItem) -> WinRT_String: ...
    @winrt_commethod(31)
    def get_ItemUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_commethod(32)
    def Load(self: Windows.Web.Syndication.ISyndicationItem, item: WinRT_String) -> Void: ...
    @winrt_commethod(33)
    def LoadFromXml(self: Windows.Web.Syndication.ISyndicationItem, itemDocument: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    Authors = property(get_Authors, None)
    Categories = property(get_Categories, None)
    Contributors = property(get_Contributors, None)
    Content = property(get_Content, put_Content)
    Id = property(get_Id, put_Id)
    LastUpdatedTime = property(get_LastUpdatedTime, put_LastUpdatedTime)
    Links = property(get_Links, None)
    PublishedDate = property(get_PublishedDate, put_PublishedDate)
    Rights = property(get_Rights, put_Rights)
    Source = property(get_Source, put_Source)
    Summary = property(get_Summary, put_Summary)
    Title = property(get_Title, put_Title)
    CommentsUri = property(get_CommentsUri, put_CommentsUri)
    EditUri = property(get_EditUri, None)
    EditMediaUri = property(get_EditMediaUri, None)
    ETag = property(get_ETag, None)
    ItemUri = property(get_ItemUri, None)
class ISyndicationItemFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationItemFactory'
    _iid_ = Guid('{251d434f-7db8-487a-85e4-10d191e66ebb}')
    @winrt_commethod(6)
    def CreateSyndicationItem(self: Windows.Web.Syndication.ISyndicationItemFactory, title: WinRT_String, content: Windows.Web.Syndication.SyndicationContent, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationItem: ...
class ISyndicationLink(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationLink'
    _iid_ = Guid('{27553abd-a10e-41b5-86bd-9759086eb0c5}')
    @winrt_commethod(6)
    def get_Length(self: Windows.Web.Syndication.ISyndicationLink) -> UInt32: ...
    @winrt_commethod(7)
    def put_Length(self: Windows.Web.Syndication.ISyndicationLink, value: UInt32) -> Void: ...
    @winrt_commethod(8)
    def get_MediaType(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_MediaType(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_Relationship(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_commethod(11)
    def put_Relationship(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_commethod(12)
    def get_Title(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_commethod(13)
    def put_Title(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_commethod(14)
    def get_Uri(self: Windows.Web.Syndication.ISyndicationLink) -> Windows.Foundation.Uri: ...
    @winrt_commethod(15)
    def put_Uri(self: Windows.Web.Syndication.ISyndicationLink, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(16)
    def get_ResourceLanguage(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_commethod(17)
    def put_ResourceLanguage(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    Length = property(get_Length, put_Length)
    MediaType = property(get_MediaType, put_MediaType)
    Relationship = property(get_Relationship, put_Relationship)
    Title = property(get_Title, put_Title)
    Uri = property(get_Uri, put_Uri)
    ResourceLanguage = property(get_ResourceLanguage, put_ResourceLanguage)
class ISyndicationLinkFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationLinkFactory'
    _iid_ = Guid('{5ed863d4-5535-48ac-98d4-c190995080b3}')
    @winrt_commethod(6)
    def CreateSyndicationLink(self: Windows.Web.Syndication.ISyndicationLinkFactory, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationLink: ...
    @winrt_commethod(7)
    def CreateSyndicationLinkEx(self: Windows.Web.Syndication.ISyndicationLinkFactory, uri: Windows.Foundation.Uri, relationship: WinRT_String, title: WinRT_String, mediaType: WinRT_String, length: UInt32) -> Windows.Web.Syndication.SyndicationLink: ...
class ISyndicationNode(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationNode'
    _iid_ = Guid('{753cef78-51f8-45c0-a9f5-f1719dec3fb2}')
    @winrt_commethod(6)
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_commethod(11)
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_commethod(12)
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_commethod(13)
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_commethod(14)
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_commethod(15)
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_commethod(16)
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_commethod(17)
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_commethod(18)
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class ISyndicationNodeFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationNodeFactory'
    _iid_ = Guid('{12902188-4acb-49a8-b777-a5eb92e18a79}')
    @winrt_commethod(6)
    def CreateSyndicationNode(self: Windows.Web.Syndication.ISyndicationNodeFactory, nodeName: WinRT_String, nodeNamespace: WinRT_String, nodeValue: WinRT_String) -> Windows.Web.Syndication.SyndicationNode: ...
class ISyndicationPerson(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationPerson'
    _iid_ = Guid('{fa1ee5da-a7c6-4517-a096-0143faf29327}')
    @winrt_commethod(6)
    def get_Email(self: Windows.Web.Syndication.ISyndicationPerson) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Email(self: Windows.Web.Syndication.ISyndicationPerson, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Name(self: Windows.Web.Syndication.ISyndicationPerson) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_Name(self: Windows.Web.Syndication.ISyndicationPerson, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_Uri(self: Windows.Web.Syndication.ISyndicationPerson) -> Windows.Foundation.Uri: ...
    @winrt_commethod(11)
    def put_Uri(self: Windows.Web.Syndication.ISyndicationPerson, value: Windows.Foundation.Uri) -> Void: ...
    Email = property(get_Email, put_Email)
    Name = property(get_Name, put_Name)
    Uri = property(get_Uri, put_Uri)
class ISyndicationPersonFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationPersonFactory'
    _iid_ = Guid('{dcf4886d-229d-4b58-a49b-f3d2f0f5c99f}')
    @winrt_commethod(6)
    def CreateSyndicationPerson(self: Windows.Web.Syndication.ISyndicationPersonFactory, name: WinRT_String) -> Windows.Web.Syndication.SyndicationPerson: ...
    @winrt_commethod(7)
    def CreateSyndicationPersonEx(self: Windows.Web.Syndication.ISyndicationPersonFactory, name: WinRT_String, email: WinRT_String, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationPerson: ...
class ISyndicationText(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationText'
    _iid_ = Guid('{b9cc5e80-313a-4091-a2a6-243e0ee923f9}')
    @winrt_commethod(6)
    def get_Text(self: Windows.Web.Syndication.ISyndicationText) -> WinRT_String: ...
    @winrt_commethod(7)
    def put_Text(self: Windows.Web.Syndication.ISyndicationText, value: WinRT_String) -> Void: ...
    @winrt_commethod(8)
    def get_Type(self: Windows.Web.Syndication.ISyndicationText) -> WinRT_String: ...
    @winrt_commethod(9)
    def put_Type(self: Windows.Web.Syndication.ISyndicationText, value: WinRT_String) -> Void: ...
    @winrt_commethod(10)
    def get_Xml(self: Windows.Web.Syndication.ISyndicationText) -> Windows.Data.Xml.Dom.XmlDocument: ...
    @winrt_commethod(11)
    def put_Xml(self: Windows.Web.Syndication.ISyndicationText, value: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    Text = property(get_Text, put_Text)
    Type = property(get_Type, put_Type)
    Xml = property(get_Xml, put_Xml)
class ISyndicationTextFactory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.ISyndicationTextFactory'
    _iid_ = Guid('{ee7342f7-11c6-4b25-ab62-e596bd162946}')
    @winrt_commethod(6)
    def CreateSyndicationText(self: Windows.Web.Syndication.ISyndicationTextFactory, text: WinRT_String) -> Windows.Web.Syndication.SyndicationText: ...
    @winrt_commethod(7)
    def CreateSyndicationTextEx(self: Windows.Web.Syndication.ISyndicationTextFactory, text: WinRT_String, type: Windows.Web.Syndication.SyndicationTextType) -> Windows.Web.Syndication.SyndicationText: ...
class RetrievalProgress(EasyCastStructure):
    BytesRetrieved: UInt32
    TotalBytesToRetrieve: UInt32
class SyndicationAttribute(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationAttribute
    _classid_ = 'Windows.Web.Syndication.SyndicationAttribute'
    @winrt_factorymethod
    def CreateSyndicationAttribute(cls: Windows.Web.Syndication.ISyndicationAttributeFactory, attributeName: WinRT_String, attributeNamespace: WinRT_String, attributeValue: WinRT_String) -> Windows.Web.Syndication.SyndicationAttribute: ...
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationAttribute: ...
    @winrt_mixinmethod
    def get_Name(self: Windows.Web.Syndication.ISyndicationAttribute) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Name(self: Windows.Web.Syndication.ISyndicationAttribute, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Namespace(self: Windows.Web.Syndication.ISyndicationAttribute) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Namespace(self: Windows.Web.Syndication.ISyndicationAttribute, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Value(self: Windows.Web.Syndication.ISyndicationAttribute) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Value(self: Windows.Web.Syndication.ISyndicationAttribute, value: WinRT_String) -> Void: ...
    Name = property(get_Name, put_Name)
    Namespace = property(get_Namespace, put_Namespace)
    Value = property(get_Value, put_Value)
class SyndicationCategory(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationCategory
    _classid_ = 'Windows.Web.Syndication.SyndicationCategory'
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationCategory: ...
    @winrt_factorymethod
    def CreateSyndicationCategory(cls: Windows.Web.Syndication.ISyndicationCategoryFactory, term: WinRT_String) -> Windows.Web.Syndication.SyndicationCategory: ...
    @winrt_factorymethod
    def CreateSyndicationCategoryEx(cls: Windows.Web.Syndication.ISyndicationCategoryFactory, term: WinRT_String, scheme: WinRT_String, label: WinRT_String) -> Windows.Web.Syndication.SyndicationCategory: ...
    @winrt_mixinmethod
    def get_Label(self: Windows.Web.Syndication.ISyndicationCategory) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Label(self: Windows.Web.Syndication.ISyndicationCategory, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Scheme(self: Windows.Web.Syndication.ISyndicationCategory) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Scheme(self: Windows.Web.Syndication.ISyndicationCategory, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Term(self: Windows.Web.Syndication.ISyndicationCategory) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Term(self: Windows.Web.Syndication.ISyndicationCategory, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Label = property(get_Label, put_Label)
    Scheme = property(get_Scheme, put_Scheme)
    Term = property(get_Term, put_Term)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class SyndicationClient(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationClient
    _classid_ = 'Windows.Web.Syndication.SyndicationClient'
    @winrt_factorymethod
    def CreateSyndicationClient(cls: Windows.Web.Syndication.ISyndicationClientFactory, serverCredential: Windows.Security.Credentials.PasswordCredential) -> Windows.Web.Syndication.SyndicationClient: ...
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationClient: ...
    @winrt_mixinmethod
    def get_ServerCredential(self: Windows.Web.Syndication.ISyndicationClient) -> Windows.Security.Credentials.PasswordCredential: ...
    @winrt_mixinmethod
    def put_ServerCredential(self: Windows.Web.Syndication.ISyndicationClient, value: Windows.Security.Credentials.PasswordCredential) -> Void: ...
    @winrt_mixinmethod
    def get_ProxyCredential(self: Windows.Web.Syndication.ISyndicationClient) -> Windows.Security.Credentials.PasswordCredential: ...
    @winrt_mixinmethod
    def put_ProxyCredential(self: Windows.Web.Syndication.ISyndicationClient, value: Windows.Security.Credentials.PasswordCredential) -> Void: ...
    @winrt_mixinmethod
    def get_MaxResponseBufferSize(self: Windows.Web.Syndication.ISyndicationClient) -> UInt32: ...
    @winrt_mixinmethod
    def put_MaxResponseBufferSize(self: Windows.Web.Syndication.ISyndicationClient, value: UInt32) -> Void: ...
    @winrt_mixinmethod
    def get_Timeout(self: Windows.Web.Syndication.ISyndicationClient) -> UInt32: ...
    @winrt_mixinmethod
    def put_Timeout(self: Windows.Web.Syndication.ISyndicationClient, value: UInt32) -> Void: ...
    @winrt_mixinmethod
    def get_BypassCacheOnRetrieve(self: Windows.Web.Syndication.ISyndicationClient) -> Boolean: ...
    @winrt_mixinmethod
    def put_BypassCacheOnRetrieve(self: Windows.Web.Syndication.ISyndicationClient, value: Boolean) -> Void: ...
    @winrt_mixinmethod
    def SetRequestHeader(self: Windows.Web.Syndication.ISyndicationClient, name: WinRT_String, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def RetrieveFeedAsync(self: Windows.Web.Syndication.ISyndicationClient, uri: Windows.Foundation.Uri) -> Windows.Foundation.IAsyncOperationWithProgress[Windows.Web.Syndication.SyndicationFeed, Windows.Web.Syndication.RetrievalProgress]: ...
    ServerCredential = property(get_ServerCredential, put_ServerCredential)
    ProxyCredential = property(get_ProxyCredential, put_ProxyCredential)
    MaxResponseBufferSize = property(get_MaxResponseBufferSize, put_MaxResponseBufferSize)
    Timeout = property(get_Timeout, put_Timeout)
    BypassCacheOnRetrieve = property(get_BypassCacheOnRetrieve, put_BypassCacheOnRetrieve)
class SyndicationContent(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationContent
    _classid_ = 'Windows.Web.Syndication.SyndicationContent'
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationContent: ...
    @winrt_factorymethod
    def CreateSyndicationContent(cls: Windows.Web.Syndication.ISyndicationContentFactory, text: WinRT_String, type: Windows.Web.Syndication.SyndicationTextType) -> Windows.Web.Syndication.SyndicationContent: ...
    @winrt_factorymethod
    def CreateSyndicationContentWithSourceUri(cls: Windows.Web.Syndication.ISyndicationContentFactory, sourceUri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationContent: ...
    @winrt_mixinmethod
    def get_Text(self: Windows.Web.Syndication.ISyndicationText) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Text(self: Windows.Web.Syndication.ISyndicationText, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Type(self: Windows.Web.Syndication.ISyndicationText) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Type(self: Windows.Web.Syndication.ISyndicationText, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Xml(self: Windows.Web.Syndication.ISyndicationText) -> Windows.Data.Xml.Dom.XmlDocument: ...
    @winrt_mixinmethod
    def put_Xml(self: Windows.Web.Syndication.ISyndicationText, value: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    @winrt_mixinmethod
    def get_SourceUri(self: Windows.Web.Syndication.ISyndicationContent) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_SourceUri(self: Windows.Web.Syndication.ISyndicationContent, value: Windows.Foundation.Uri) -> Void: ...
    Text = property(get_Text, put_Text)
    Type = property(get_Type, put_Type)
    Xml = property(get_Xml, put_Xml)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
    SourceUri = property(get_SourceUri, put_SourceUri)
class SyndicationError(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    _classid_ = 'Windows.Web.Syndication.SyndicationError'
    @winrt_classmethod
    def GetStatus(cls: Windows.Web.Syndication.ISyndicationErrorStatics, hresult: Int32) -> Windows.Web.Syndication.SyndicationErrorStatus: ...
SyndicationErrorStatus = Int32
SyndicationErrorStatus_Unknown: SyndicationErrorStatus = 0
SyndicationErrorStatus_MissingRequiredElement: SyndicationErrorStatus = 1
SyndicationErrorStatus_MissingRequiredAttribute: SyndicationErrorStatus = 2
SyndicationErrorStatus_InvalidXml: SyndicationErrorStatus = 3
SyndicationErrorStatus_UnexpectedContent: SyndicationErrorStatus = 4
SyndicationErrorStatus_UnsupportedFormat: SyndicationErrorStatus = 5
class SyndicationFeed(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationFeed
    _classid_ = 'Windows.Web.Syndication.SyndicationFeed'
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationFeed: ...
    @winrt_factorymethod
    def CreateSyndicationFeed(cls: Windows.Web.Syndication.ISyndicationFeedFactory, title: WinRT_String, subtitle: WinRT_String, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationFeed: ...
    @winrt_mixinmethod
    def get_Authors(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_mixinmethod
    def get_Categories(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationCategory]: ...
    @winrt_mixinmethod
    def get_Contributors(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_mixinmethod
    def get_Generator(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.SyndicationGenerator: ...
    @winrt_mixinmethod
    def put_Generator(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.SyndicationGenerator) -> Void: ...
    @winrt_mixinmethod
    def get_IconUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_IconUri(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_Id(self: Windows.Web.Syndication.ISyndicationFeed) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Id(self: Windows.Web.Syndication.ISyndicationFeed, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Items(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationItem]: ...
    @winrt_mixinmethod
    def get_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.DateTime: ...
    @winrt_mixinmethod
    def put_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Foundation.DateTime) -> Void: ...
    @winrt_mixinmethod
    def get_Links(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationLink]: ...
    @winrt_mixinmethod
    def get_ImageUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_ImageUri(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_Rights(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_mixinmethod
    def put_Rights(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_mixinmethod
    def get_Subtitle(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_mixinmethod
    def put_Subtitle(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_mixinmethod
    def get_Title(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_mixinmethod
    def put_Title(self: Windows.Web.Syndication.ISyndicationFeed, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_mixinmethod
    def get_FirstUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def get_LastUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def get_NextUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def get_PreviousUri(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def get_SourceFormat(self: Windows.Web.Syndication.ISyndicationFeed) -> Windows.Web.Syndication.SyndicationFormat: ...
    @winrt_mixinmethod
    def Load(self: Windows.Web.Syndication.ISyndicationFeed, feed: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def LoadFromXml(self: Windows.Web.Syndication.ISyndicationFeed, feedDocument: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Authors = property(get_Authors, None)
    Categories = property(get_Categories, None)
    Contributors = property(get_Contributors, None)
    Generator = property(get_Generator, put_Generator)
    IconUri = property(get_IconUri, put_IconUri)
    Id = property(get_Id, put_Id)
    Items = property(get_Items, None)
    LastUpdatedTime = property(get_LastUpdatedTime, put_LastUpdatedTime)
    Links = property(get_Links, None)
    ImageUri = property(get_ImageUri, put_ImageUri)
    Rights = property(get_Rights, put_Rights)
    Subtitle = property(get_Subtitle, put_Subtitle)
    Title = property(get_Title, put_Title)
    FirstUri = property(get_FirstUri, None)
    LastUri = property(get_LastUri, None)
    NextUri = property(get_NextUri, None)
    PreviousUri = property(get_PreviousUri, None)
    SourceFormat = property(get_SourceFormat, None)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
SyndicationFormat = Int32
SyndicationFormat_Atom10: SyndicationFormat = 0
SyndicationFormat_Rss20: SyndicationFormat = 1
SyndicationFormat_Rss10: SyndicationFormat = 2
SyndicationFormat_Rss092: SyndicationFormat = 3
SyndicationFormat_Rss091: SyndicationFormat = 4
SyndicationFormat_Atom03: SyndicationFormat = 5
class SyndicationGenerator(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationGenerator
    _classid_ = 'Windows.Web.Syndication.SyndicationGenerator'
    @winrt_factorymethod
    def CreateSyndicationGenerator(cls: Windows.Web.Syndication.ISyndicationGeneratorFactory, text: WinRT_String) -> Windows.Web.Syndication.SyndicationGenerator: ...
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationGenerator: ...
    @winrt_mixinmethod
    def get_Text(self: Windows.Web.Syndication.ISyndicationGenerator) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Text(self: Windows.Web.Syndication.ISyndicationGenerator, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Uri(self: Windows.Web.Syndication.ISyndicationGenerator) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_Uri(self: Windows.Web.Syndication.ISyndicationGenerator, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_Version(self: Windows.Web.Syndication.ISyndicationGenerator) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Version(self: Windows.Web.Syndication.ISyndicationGenerator, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Text = property(get_Text, put_Text)
    Uri = property(get_Uri, put_Uri)
    Version = property(get_Version, put_Version)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class SyndicationItem(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationItem
    _classid_ = 'Windows.Web.Syndication.SyndicationItem'
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationItem: ...
    @winrt_factorymethod
    def CreateSyndicationItem(cls: Windows.Web.Syndication.ISyndicationItemFactory, title: WinRT_String, content: Windows.Web.Syndication.SyndicationContent, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationItem: ...
    @winrt_mixinmethod
    def get_Authors(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_mixinmethod
    def get_Categories(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationCategory]: ...
    @winrt_mixinmethod
    def get_Contributors(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationPerson]: ...
    @winrt_mixinmethod
    def get_Content(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.SyndicationContent: ...
    @winrt_mixinmethod
    def put_Content(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.SyndicationContent) -> Void: ...
    @winrt_mixinmethod
    def get_Id(self: Windows.Web.Syndication.ISyndicationItem) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Id(self: Windows.Web.Syndication.ISyndicationItem, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.DateTime: ...
    @winrt_mixinmethod
    def put_LastUpdatedTime(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Foundation.DateTime) -> Void: ...
    @winrt_mixinmethod
    def get_Links(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationLink]: ...
    @winrt_mixinmethod
    def get_PublishedDate(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.DateTime: ...
    @winrt_mixinmethod
    def put_PublishedDate(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Foundation.DateTime) -> Void: ...
    @winrt_mixinmethod
    def get_Rights(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_mixinmethod
    def put_Rights(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_mixinmethod
    def get_Source(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.SyndicationFeed: ...
    @winrt_mixinmethod
    def put_Source(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.SyndicationFeed) -> Void: ...
    @winrt_mixinmethod
    def get_Summary(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_mixinmethod
    def put_Summary(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_mixinmethod
    def get_Title(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Web.Syndication.ISyndicationText: ...
    @winrt_mixinmethod
    def put_Title(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Web.Syndication.ISyndicationText) -> Void: ...
    @winrt_mixinmethod
    def get_CommentsUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_CommentsUri(self: Windows.Web.Syndication.ISyndicationItem, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_EditUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def get_EditMediaUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def get_ETag(self: Windows.Web.Syndication.ISyndicationItem) -> WinRT_String: ...
    @winrt_mixinmethod
    def get_ItemUri(self: Windows.Web.Syndication.ISyndicationItem) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def Load(self: Windows.Web.Syndication.ISyndicationItem, item: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def LoadFromXml(self: Windows.Web.Syndication.ISyndicationItem, itemDocument: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Authors = property(get_Authors, None)
    Categories = property(get_Categories, None)
    Contributors = property(get_Contributors, None)
    Content = property(get_Content, put_Content)
    Id = property(get_Id, put_Id)
    LastUpdatedTime = property(get_LastUpdatedTime, put_LastUpdatedTime)
    Links = property(get_Links, None)
    PublishedDate = property(get_PublishedDate, put_PublishedDate)
    Rights = property(get_Rights, put_Rights)
    Source = property(get_Source, put_Source)
    Summary = property(get_Summary, put_Summary)
    Title = property(get_Title, put_Title)
    CommentsUri = property(get_CommentsUri, put_CommentsUri)
    EditUri = property(get_EditUri, None)
    EditMediaUri = property(get_EditMediaUri, None)
    ETag = property(get_ETag, None)
    ItemUri = property(get_ItemUri, None)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class SyndicationLink(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationLink
    _classid_ = 'Windows.Web.Syndication.SyndicationLink'
    @winrt_factorymethod
    def CreateSyndicationLink(cls: Windows.Web.Syndication.ISyndicationLinkFactory, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationLink: ...
    @winrt_factorymethod
    def CreateSyndicationLinkEx(cls: Windows.Web.Syndication.ISyndicationLinkFactory, uri: Windows.Foundation.Uri, relationship: WinRT_String, title: WinRT_String, mediaType: WinRT_String, length: UInt32) -> Windows.Web.Syndication.SyndicationLink: ...
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationLink: ...
    @winrt_mixinmethod
    def get_Length(self: Windows.Web.Syndication.ISyndicationLink) -> UInt32: ...
    @winrt_mixinmethod
    def put_Length(self: Windows.Web.Syndication.ISyndicationLink, value: UInt32) -> Void: ...
    @winrt_mixinmethod
    def get_MediaType(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_MediaType(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Relationship(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Relationship(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Title(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Title(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Uri(self: Windows.Web.Syndication.ISyndicationLink) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_Uri(self: Windows.Web.Syndication.ISyndicationLink, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_ResourceLanguage(self: Windows.Web.Syndication.ISyndicationLink) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_ResourceLanguage(self: Windows.Web.Syndication.ISyndicationLink, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Length = property(get_Length, put_Length)
    MediaType = property(get_MediaType, put_MediaType)
    Relationship = property(get_Relationship, put_Relationship)
    Title = property(get_Title, put_Title)
    Uri = property(get_Uri, put_Uri)
    ResourceLanguage = property(get_ResourceLanguage, put_ResourceLanguage)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class SyndicationNode(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationNode
    _classid_ = 'Windows.Web.Syndication.SyndicationNode'
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationNode: ...
    @winrt_factorymethod
    def CreateSyndicationNode(cls: Windows.Web.Syndication.ISyndicationNodeFactory, nodeName: WinRT_String, nodeNamespace: WinRT_String, nodeValue: WinRT_String) -> Windows.Web.Syndication.SyndicationNode: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class SyndicationPerson(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationPerson
    _classid_ = 'Windows.Web.Syndication.SyndicationPerson'
    @winrt_factorymethod
    def CreateSyndicationPerson(cls: Windows.Web.Syndication.ISyndicationPersonFactory, name: WinRT_String) -> Windows.Web.Syndication.SyndicationPerson: ...
    @winrt_factorymethod
    def CreateSyndicationPersonEx(cls: Windows.Web.Syndication.ISyndicationPersonFactory, name: WinRT_String, email: WinRT_String, uri: Windows.Foundation.Uri) -> Windows.Web.Syndication.SyndicationPerson: ...
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationPerson: ...
    @winrt_mixinmethod
    def get_Email(self: Windows.Web.Syndication.ISyndicationPerson) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Email(self: Windows.Web.Syndication.ISyndicationPerson, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Name(self: Windows.Web.Syndication.ISyndicationPerson) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Name(self: Windows.Web.Syndication.ISyndicationPerson, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Uri(self: Windows.Web.Syndication.ISyndicationPerson) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_Uri(self: Windows.Web.Syndication.ISyndicationPerson, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Email = property(get_Email, put_Email)
    Name = property(get_Name, put_Name)
    Uri = property(get_Uri, put_Uri)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
class SyndicationText(ComPtr):
    extends: Windows.Win32.System.WinRT.IInspectable
    default_interface: Windows.Web.Syndication.ISyndicationText
    _classid_ = 'Windows.Web.Syndication.SyndicationText'
    @winrt_activatemethod
    def CreateInstance(cls) -> Windows.Web.Syndication.SyndicationText: ...
    @winrt_factorymethod
    def CreateSyndicationText(cls: Windows.Web.Syndication.ISyndicationTextFactory, text: WinRT_String) -> Windows.Web.Syndication.SyndicationText: ...
    @winrt_factorymethod
    def CreateSyndicationTextEx(cls: Windows.Web.Syndication.ISyndicationTextFactory, text: WinRT_String, type: Windows.Web.Syndication.SyndicationTextType) -> Windows.Web.Syndication.SyndicationText: ...
    @winrt_mixinmethod
    def get_Text(self: Windows.Web.Syndication.ISyndicationText) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Text(self: Windows.Web.Syndication.ISyndicationText, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Type(self: Windows.Web.Syndication.ISyndicationText) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Type(self: Windows.Web.Syndication.ISyndicationText, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Xml(self: Windows.Web.Syndication.ISyndicationText) -> Windows.Data.Xml.Dom.XmlDocument: ...
    @winrt_mixinmethod
    def put_Xml(self: Windows.Web.Syndication.ISyndicationText, value: Windows.Data.Xml.Dom.XmlDocument) -> Void: ...
    @winrt_mixinmethod
    def get_NodeName(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeName(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeNamespace(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_NodeValue(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_NodeValue(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_Language(self: Windows.Web.Syndication.ISyndicationNode) -> WinRT_String: ...
    @winrt_mixinmethod
    def put_Language(self: Windows.Web.Syndication.ISyndicationNode, value: WinRT_String) -> Void: ...
    @winrt_mixinmethod
    def get_BaseUri(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Uri: ...
    @winrt_mixinmethod
    def put_BaseUri(self: Windows.Web.Syndication.ISyndicationNode, value: Windows.Foundation.Uri) -> Void: ...
    @winrt_mixinmethod
    def get_AttributeExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.SyndicationAttribute]: ...
    @winrt_mixinmethod
    def get_ElementExtensions(self: Windows.Web.Syndication.ISyndicationNode) -> Windows.Foundation.Collections.IVector[Windows.Web.Syndication.ISyndicationNode]: ...
    @winrt_mixinmethod
    def GetXmlDocument(self: Windows.Web.Syndication.ISyndicationNode, format: Windows.Web.Syndication.SyndicationFormat) -> Windows.Data.Xml.Dom.XmlDocument: ...
    Text = property(get_Text, put_Text)
    Type = property(get_Type, put_Type)
    Xml = property(get_Xml, put_Xml)
    NodeName = property(get_NodeName, put_NodeName)
    NodeNamespace = property(get_NodeNamespace, put_NodeNamespace)
    NodeValue = property(get_NodeValue, put_NodeValue)
    Language = property(get_Language, put_Language)
    BaseUri = property(get_BaseUri, put_BaseUri)
    AttributeExtensions = property(get_AttributeExtensions, None)
    ElementExtensions = property(get_ElementExtensions, None)
SyndicationTextType = Int32
SyndicationTextType_Text: SyndicationTextType = 0
SyndicationTextType_Html: SyndicationTextType = 1
SyndicationTextType_Xhtml: SyndicationTextType = 2
class TransferProgress(EasyCastStructure):
    BytesSent: UInt32
    TotalBytesToSend: UInt32
    BytesRetrieved: UInt32
    TotalBytesToRetrieve: UInt32
make_head(_module, 'ISyndicationAttribute')
make_head(_module, 'ISyndicationAttributeFactory')
make_head(_module, 'ISyndicationCategory')
make_head(_module, 'ISyndicationCategoryFactory')
make_head(_module, 'ISyndicationClient')
make_head(_module, 'ISyndicationClientFactory')
make_head(_module, 'ISyndicationContent')
make_head(_module, 'ISyndicationContentFactory')
make_head(_module, 'ISyndicationErrorStatics')
make_head(_module, 'ISyndicationFeed')
make_head(_module, 'ISyndicationFeedFactory')
make_head(_module, 'ISyndicationGenerator')
make_head(_module, 'ISyndicationGeneratorFactory')
make_head(_module, 'ISyndicationItem')
make_head(_module, 'ISyndicationItemFactory')
make_head(_module, 'ISyndicationLink')
make_head(_module, 'ISyndicationLinkFactory')
make_head(_module, 'ISyndicationNode')
make_head(_module, 'ISyndicationNodeFactory')
make_head(_module, 'ISyndicationPerson')
make_head(_module, 'ISyndicationPersonFactory')
make_head(_module, 'ISyndicationText')
make_head(_module, 'ISyndicationTextFactory')
make_head(_module, 'RetrievalProgress')
make_head(_module, 'SyndicationAttribute')
make_head(_module, 'SyndicationCategory')
make_head(_module, 'SyndicationClient')
make_head(_module, 'SyndicationContent')
make_head(_module, 'SyndicationError')
make_head(_module, 'SyndicationFeed')
make_head(_module, 'SyndicationGenerator')
make_head(_module, 'SyndicationItem')
make_head(_module, 'SyndicationLink')
make_head(_module, 'SyndicationNode')
make_head(_module, 'SyndicationPerson')
make_head(_module, 'SyndicationText')
make_head(_module, 'TransferProgress')
