from __future__ import annotations
from ctypes import c_void_p, c_char_p, c_wchar_p, POINTER, CFUNCTYPE, WINFUNCTYPE, cdll, windll
from Windows import ARCH, MissingType, Byte, SByte, Char, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Single, Double, String, Boolean, Void, Guid, SUCCEEDED, FAILED, cfunctype, winfunctype, commethod, cfunctype_pointer, winfunctype_pointer, press, make_head, EasyCastStructure, EasyCastUnion, ComPtr
import Windows.Win32.Foundation
import Windows.Win32.Graphics.Direct2D.Common
import Windows.Win32.Graphics.Direct3D
import Windows.Win32.Graphics.DirectComposition
import Windows.Win32.Graphics.Dxgi
import Windows.Win32.Graphics.Dxgi.Common
import Windows.Win32.Security
import Windows.Win32.System.Com
import sys
_module = sys.modules[__name__]
def __getattr__(name):
    try:
        prototype = globals()[f'{name}_head']
    except KeyError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
    setattr(_module, name, press(prototype))
    return getattr(_module, name)
COMPOSITIONOBJECT_READ: Int32 = 1
COMPOSITIONOBJECT_WRITE: Int32 = 2
DCOMPOSITION_MAX_WAITFORCOMPOSITORCLOCK_OBJECTS: UInt32 = 32
COMPOSITION_STATS_MAX_TARGETS: UInt32 = 256
@winfunctype('dcomp.dll')
def DCompositionCreateDevice(dxgiDevice: Windows.Win32.Graphics.Dxgi.IDXGIDevice_head, iid: POINTER(Guid), dcompositionDevice: POINTER(c_void_p)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionCreateDevice2(renderingDevice: Windows.Win32.System.Com.IUnknown_head, iid: POINTER(Guid), dcompositionDevice: POINTER(c_void_p)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionCreateDevice3(renderingDevice: Windows.Win32.System.Com.IUnknown_head, iid: POINTER(Guid), dcompositionDevice: POINTER(c_void_p)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionCreateSurfaceHandle(desiredAccess: UInt32, securityAttributes: POINTER(Windows.Win32.Security.SECURITY_ATTRIBUTES_head), surfaceHandle: POINTER(Windows.Win32.Foundation.HANDLE)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionAttachMouseWheelToHwnd(visual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head, hwnd: Windows.Win32.Foundation.HWND, enable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionAttachMouseDragToHwnd(visual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head, hwnd: Windows.Win32.Foundation.HWND, enable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionGetFrameId(frameIdType: Windows.Win32.Graphics.DirectComposition.COMPOSITION_FRAME_ID_TYPE, frameId: POINTER(UInt64)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionGetStatistics(frameId: UInt64, frameStats: POINTER(Windows.Win32.Graphics.DirectComposition.COMPOSITION_FRAME_STATS_head), targetIdCount: UInt32, targetIds: POINTER(Windows.Win32.Graphics.DirectComposition.COMPOSITION_TARGET_ID_head), actualTargetIdCount: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionGetTargetStatistics(frameId: UInt64, targetId: POINTER(Windows.Win32.Graphics.DirectComposition.COMPOSITION_TARGET_ID_head), targetStats: POINTER(Windows.Win32.Graphics.DirectComposition.COMPOSITION_TARGET_STATS_head)) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionBoostCompositorClock(enable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
@winfunctype('dcomp.dll')
def DCompositionWaitForCompositorClock(count: UInt32, handles: POINTER(Windows.Win32.Foundation.HANDLE), timeoutInMs: UInt32) -> UInt32: ...
COMPOSITION_FRAME_ID_TYPE = Int32
COMPOSITION_FRAME_ID_CREATED: COMPOSITION_FRAME_ID_TYPE = 0
COMPOSITION_FRAME_ID_CONFIRMED: COMPOSITION_FRAME_ID_TYPE = 1
COMPOSITION_FRAME_ID_COMPLETED: COMPOSITION_FRAME_ID_TYPE = 2
class COMPOSITION_FRAME_STATS(EasyCastStructure):
    startTime: UInt64
    targetTime: UInt64
    framePeriod: UInt64
class COMPOSITION_STATS(EasyCastStructure):
    presentCount: UInt32
    refreshCount: UInt32
    virtualRefreshCount: UInt32
    time: UInt64
class COMPOSITION_TARGET_ID(EasyCastStructure):
    displayAdapterLuid: Windows.Win32.Foundation.LUID
    renderAdapterLuid: Windows.Win32.Foundation.LUID
    vidPnSourceId: UInt32
    vidPnTargetId: UInt32
    uniqueId: UInt32
class COMPOSITION_TARGET_STATS(EasyCastStructure):
    outstandingPresents: UInt32
    presentTime: UInt64
    vblankDuration: UInt64
    presentedStats: Windows.Win32.Graphics.DirectComposition.COMPOSITION_STATS
    completedStats: Windows.Win32.Graphics.DirectComposition.COMPOSITION_STATS
DCOMPOSITION_BACKFACE_VISIBILITY = Int32
DCOMPOSITION_BACKFACE_VISIBILITY_VISIBLE: DCOMPOSITION_BACKFACE_VISIBILITY = 0
DCOMPOSITION_BACKFACE_VISIBILITY_HIDDEN: DCOMPOSITION_BACKFACE_VISIBILITY = 1
DCOMPOSITION_BACKFACE_VISIBILITY_INHERIT: DCOMPOSITION_BACKFACE_VISIBILITY = -1
DCOMPOSITION_BITMAP_INTERPOLATION_MODE = Int32
DCOMPOSITION_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR: DCOMPOSITION_BITMAP_INTERPOLATION_MODE = 0
DCOMPOSITION_BITMAP_INTERPOLATION_MODE_LINEAR: DCOMPOSITION_BITMAP_INTERPOLATION_MODE = 1
DCOMPOSITION_BITMAP_INTERPOLATION_MODE_INHERIT: DCOMPOSITION_BITMAP_INTERPOLATION_MODE = -1
DCOMPOSITION_BORDER_MODE = Int32
DCOMPOSITION_BORDER_MODE_SOFT: DCOMPOSITION_BORDER_MODE = 0
DCOMPOSITION_BORDER_MODE_HARD: DCOMPOSITION_BORDER_MODE = 1
DCOMPOSITION_BORDER_MODE_INHERIT: DCOMPOSITION_BORDER_MODE = -1
DCOMPOSITION_COMPOSITE_MODE = Int32
DCOMPOSITION_COMPOSITE_MODE_SOURCE_OVER: DCOMPOSITION_COMPOSITE_MODE = 0
DCOMPOSITION_COMPOSITE_MODE_DESTINATION_INVERT: DCOMPOSITION_COMPOSITE_MODE = 1
DCOMPOSITION_COMPOSITE_MODE_MIN_BLEND: DCOMPOSITION_COMPOSITE_MODE = 2
DCOMPOSITION_COMPOSITE_MODE_INHERIT: DCOMPOSITION_COMPOSITE_MODE = -1
DCOMPOSITION_DEPTH_MODE = Int32
DCOMPOSITION_DEPTH_MODE_TREE: DCOMPOSITION_DEPTH_MODE = 0
DCOMPOSITION_DEPTH_MODE_SPATIAL: DCOMPOSITION_DEPTH_MODE = 1
DCOMPOSITION_DEPTH_MODE_SORTED: DCOMPOSITION_DEPTH_MODE = 3
DCOMPOSITION_DEPTH_MODE_INHERIT: DCOMPOSITION_DEPTH_MODE = -1
class DCOMPOSITION_FRAME_STATISTICS(EasyCastStructure):
    lastFrameTime: Int64
    currentCompositionRate: Windows.Win32.Graphics.Dxgi.Common.DXGI_RATIONAL
    currentTime: Int64
    timeFrequency: Int64
    nextEstimatedFrameTime: Int64
DCOMPOSITION_OPACITY_MODE = Int32
DCOMPOSITION_OPACITY_MODE_LAYER: DCOMPOSITION_OPACITY_MODE = 0
DCOMPOSITION_OPACITY_MODE_MULTIPLY: DCOMPOSITION_OPACITY_MODE = 1
DCOMPOSITION_OPACITY_MODE_INHERIT: DCOMPOSITION_OPACITY_MODE = -1
class DCompositionInkTrailPoint(EasyCastStructure):
    x: Single
    y: Single
    radius: Single
class IDCompositionAffineTransform2DEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{0b74b9e8-cdd6-492f-bbbc-5ed32157026d}')
    @commethod(4)
    def SetInterpolationMode(self, interpolationMode: Windows.Win32.Graphics.Direct2D.Common.D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetBorderMode(self, borderMode: Windows.Win32.Graphics.Direct2D.Common.D2D1_BORDER_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetTransformMatrix(self, transformMatrix: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_MATRIX_3X2_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetTransformMatrixElement(self, row: Int32, column: Int32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetTransformMatrixElement(self, row: Int32, column: Int32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetSharpness(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetSharpness(self, sharpness: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionAnimation(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{cbfd91d9-51b2-45e4-b3de-d19ccfb863c5}')
    @commethod(3)
    def Reset(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetAbsoluteBeginTime(self, beginTime: Int64) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def AddCubic(self, beginOffset: Double, constantCoefficient: Single, linearCoefficient: Single, quadraticCoefficient: Single, cubicCoefficient: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def AddSinusoidal(self, beginOffset: Double, bias: Single, amplitude: Single, frequency: Single, phase: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def AddRepeat(self, beginOffset: Double, durationToRepeat: Double) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def End(self, endOffset: Double, endValue: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionArithmeticCompositeEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{3b67dfa8-e3dd-4e61-b640-46c2f3d739dc}')
    @commethod(4)
    def SetCoefficients(self, coefficients: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_4F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetClampOutput(self, clampoutput: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetCoefficient1(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetCoefficient1(self, Coeffcient1: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetCoefficient2(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetCoefficient2(self, Coefficient2: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetCoefficient3(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetCoefficient3(self, Coefficient3: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetCoefficient4(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetCoefficient4(self, Coefficient4: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionBlendEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{33ecdc0a-578a-4a11-9c14-0cb90517f9c5}')
    @commethod(4)
    def SetMode(self, mode: Windows.Win32.Graphics.Direct2D.Common.D2D1_BLEND_MODE) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionBrightnessEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{6027496e-cb3a-49ab-934f-d798da4f7da6}')
    @commethod(4)
    def SetWhitePoint(self, whitePoint: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_2F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetBlackPoint(self, blackPoint: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_2F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetWhitePointX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetWhitePointX(self, whitePointX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetWhitePointY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetWhitePointY(self, whitePointY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetBlackPointX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetBlackPointX(self, blackPointX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetBlackPointY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetBlackPointY(self, blackPointY: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionClip(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{64ac3703-9d3f-45ec-a109-7cac0e7a13a7}')
class IDCompositionColorMatrixEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{c1170a22-3ce2-4966-90d4-55408bfc84c4}')
    @commethod(4)
    def SetMatrix(self, matrix: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_MATRIX_5X4_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetMatrixElement(self, row: Int32, column: Int32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetMatrixElement(self, row: Int32, column: Int32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetAlphaMode(self, mode: Windows.Win32.Graphics.Direct2D.Common.D2D1_COLORMATRIX_ALPHA_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetClampOutput(self, clamp: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionCompositeEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{576616c0-a231-494d-a38d-00fd5ec4db46}')
    @commethod(4)
    def SetMode(self, mode: Windows.Win32.Graphics.Direct2D.Common.D2D1_COMPOSITE_MODE) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionDelegatedInkTrail(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{c2448e9b-547d-4057-8cf5-8144ede1c2da}')
    @commethod(3)
    def AddTrailPoints(self, inkPoints: POINTER(Windows.Win32.Graphics.DirectComposition.DCompositionInkTrailPoint_head), inkPointsCount: UInt32, generationId: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def AddTrailPointsWithPrediction(self, inkPoints: POINTER(Windows.Win32.Graphics.DirectComposition.DCompositionInkTrailPoint_head), inkPointsCount: UInt32, predictedInkPoints: POINTER(Windows.Win32.Graphics.DirectComposition.DCompositionInkTrailPoint_head), predictedInkPointsCount: UInt32, generationId: POINTER(UInt32)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def RemoveTrailPoints(self, generationId: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def StartNewTrail(self, color: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D1_COLOR_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionDesktopDevice(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionDevice2
    _iid_ = Guid('{5f4633fe-1e08-4cb8-8c75-ce24333f5602}')
    @commethod(24)
    def CreateTargetForHwnd(self, hwnd: Windows.Win32.Foundation.HWND, topmost: Windows.Win32.Foundation.BOOL, target: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTarget_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def CreateSurfaceFromHandle(self, handle: Windows.Win32.Foundation.HANDLE, surface: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def CreateSurfaceFromHwnd(self, hwnd: Windows.Win32.Foundation.HWND, surface: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionDevice(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{c37ea93a-e7aa-450d-b16f-9746cb0407f3}')
    @commethod(3)
    def Commit(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def WaitForCommitCompletion(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def GetFrameStatistics(self, statistics: POINTER(Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_FRAME_STATISTICS_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def CreateTargetForHwnd(self, hwnd: Windows.Win32.Foundation.HWND, topmost: Windows.Win32.Foundation.BOOL, target: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTarget_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def CreateVisual(self, visual: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def CreateSurface(self, width: UInt32, height: UInt32, pixelFormat: Windows.Win32.Graphics.Dxgi.Common.DXGI_FORMAT, alphaMode: Windows.Win32.Graphics.Dxgi.Common.DXGI_ALPHA_MODE, surface: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSurface_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def CreateVirtualSurface(self, initialWidth: UInt32, initialHeight: UInt32, pixelFormat: Windows.Win32.Graphics.Dxgi.Common.DXGI_FORMAT, alphaMode: Windows.Win32.Graphics.Dxgi.Common.DXGI_ALPHA_MODE, virtualSurface: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionVirtualSurface_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def CreateSurfaceFromHandle(self, handle: Windows.Win32.Foundation.HANDLE, surface: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def CreateSurfaceFromHwnd(self, hwnd: Windows.Win32.Foundation.HWND, surface: POINTER(Windows.Win32.System.Com.IUnknown_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def CreateTranslateTransform(self, translateTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTranslateTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def CreateScaleTransform(self, scaleTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionScaleTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def CreateRotateTransform(self, rotateTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionRotateTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def CreateSkewTransform(self, skewTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSkewTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def CreateMatrixTransform(self, matrixTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionMatrixTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def CreateTransformGroup(self, transforms: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform_head), elements: UInt32, transformGroup: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def CreateTranslateTransform3D(self, translateTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTranslateTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def CreateScaleTransform3D(self, scaleTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionScaleTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def CreateRotateTransform3D(self, rotateTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionRotateTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def CreateMatrixTransform3D(self, matrixTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionMatrixTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def CreateTransform3DGroup(self, transforms3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D_head), elements: UInt32, transform3DGroup: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def CreateEffectGroup(self, effectGroup: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionEffectGroup_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def CreateRectangleClip(self, clip: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionRectangleClip_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def CreateAnimation(self, animation: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def CheckDeviceState(self, pfValid: POINTER(Windows.Win32.Foundation.BOOL)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionDevice2(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{75f6468d-1b8e-447c-9bc6-75fea80b5b25}')
    @commethod(3)
    def Commit(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def WaitForCommitCompletion(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def GetFrameStatistics(self, statistics: POINTER(Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_FRAME_STATISTICS_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def CreateVisual(self, visual: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionVisual2_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def CreateSurfaceFactory(self, renderingDevice: Windows.Win32.System.Com.IUnknown_head, surfaceFactory: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSurfaceFactory_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def CreateSurface(self, width: UInt32, height: UInt32, pixelFormat: Windows.Win32.Graphics.Dxgi.Common.DXGI_FORMAT, alphaMode: Windows.Win32.Graphics.Dxgi.Common.DXGI_ALPHA_MODE, surface: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSurface_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def CreateVirtualSurface(self, initialWidth: UInt32, initialHeight: UInt32, pixelFormat: Windows.Win32.Graphics.Dxgi.Common.DXGI_FORMAT, alphaMode: Windows.Win32.Graphics.Dxgi.Common.DXGI_ALPHA_MODE, virtualSurface: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionVirtualSurface_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def CreateTranslateTransform(self, translateTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTranslateTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def CreateScaleTransform(self, scaleTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionScaleTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def CreateRotateTransform(self, rotateTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionRotateTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def CreateSkewTransform(self, skewTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSkewTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def CreateMatrixTransform(self, matrixTransform: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionMatrixTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def CreateTransformGroup(self, transforms: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform_head), elements: UInt32, transformGroup: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def CreateTranslateTransform3D(self, translateTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTranslateTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def CreateScaleTransform3D(self, scaleTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionScaleTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def CreateRotateTransform3D(self, rotateTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionRotateTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def CreateMatrixTransform3D(self, matrixTransform3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionMatrixTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def CreateTransform3DGroup(self, transforms3D: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D_head), elements: UInt32, transform3DGroup: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def CreateEffectGroup(self, effectGroup: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionEffectGroup_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def CreateRectangleClip(self, clip: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionRectangleClip_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def CreateAnimation(self, animation: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionDevice3(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionDevice2
    _iid_ = Guid('{0987cb06-f916-48bf-8d35-ce7641781bd9}')
    @commethod(24)
    def CreateGaussianBlurEffect(self, gaussianBlurEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionGaussianBlurEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def CreateBrightnessEffect(self, brightnessEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionBrightnessEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def CreateColorMatrixEffect(self, colorMatrixEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionColorMatrixEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def CreateShadowEffect(self, shadowEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionShadowEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(28)
    def CreateHueRotationEffect(self, hueRotationEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionHueRotationEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(29)
    def CreateSaturationEffect(self, saturationEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSaturationEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(30)
    def CreateTurbulenceEffect(self, turbulenceEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTurbulenceEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(31)
    def CreateLinearTransferEffect(self, linearTransferEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionLinearTransferEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(32)
    def CreateTableTransferEffect(self, tableTransferEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionTableTransferEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(33)
    def CreateCompositeEffect(self, compositeEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionCompositeEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(34)
    def CreateBlendEffect(self, blendEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionBlendEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(35)
    def CreateArithmeticCompositeEffect(self, arithmeticCompositeEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionArithmeticCompositeEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(36)
    def CreateAffineTransform2DEffect(self, affineTransform2dEffect: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionAffineTransform2DEffect_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionDeviceDebug(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{a1a3c64a-224f-4a81-9773-4f03a89d3c6c}')
    @commethod(3)
    def EnableDebugCounters(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def DisableDebugCounters(self) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionEffect(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{ec81b08f-bfcb-4e8d-b193-a915587999e8}')
class IDCompositionEffectGroup(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionEffect
    _iid_ = Guid('{a7929a74-e6b2-4bd6-8b95-4040119ca34d}')
    @commethod(3)
    def SetOpacity(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetOpacity(self, opacity: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetTransform3D(self, transform3D: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D_head) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionFilterEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionEffect
    _iid_ = Guid('{30c421d5-8cb2-4e9f-b133-37be270d4ac2}')
    @commethod(3)
    def SetInput(self, index: UInt32, input: Windows.Win32.System.Com.IUnknown_head, flags: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionGaussianBlurEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{45d4d0b7-1bd4-454e-8894-2bfa68443033}')
    @commethod(4)
    def SetStandardDeviation(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetStandardDeviation(self, amount: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetBorderMode(self, mode: Windows.Win32.Graphics.Direct2D.Common.D2D1_BORDER_MODE) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionHueRotationEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{6db9f920-0770-4781-b0c6-381912f9d167}')
    @commethod(4)
    def SetAngle(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetAngle(self, amountDegrees: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionInkTrailDevice(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{df0c7cec-cdeb-4d4a-b91c-721bf22f4e6c}')
    @commethod(3)
    def CreateDelegatedInkTrail(self, inkTrail: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionDelegatedInkTrail_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def CreateDelegatedInkTrailForSwapChain(self, swapChain: Windows.Win32.System.Com.IUnknown_head, inkTrail: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionDelegatedInkTrail_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionLinearTransferEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{4305ee5b-c4a0-4c88-9385-67124e017683}')
    @commethod(4)
    def SetRedYIntercept(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetRedYIntercept(self, redYIntercept: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetRedSlope(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetRedSlope(self, redSlope: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetRedDisable(self, redDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetGreenYIntercept(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetGreenYIntercept(self, greenYIntercept: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetGreenSlope(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetGreenSlope(self, greenSlope: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetGreenDisable(self, greenDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetBlueYIntercept(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def SetBlueYIntercept(self, blueYIntercept: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def SetBlueSlope(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def SetBlueSlope(self, blueSlope: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def SetBlueDisable(self, blueDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def SetAlphaYIntercept(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def SetAlphaYIntercept(self, alphaYIntercept: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def SetAlphaSlope(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def SetAlphaSlope(self, alphaSlope: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def SetAlphaDisable(self, alphaDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def SetClampOutput(self, clampOutput: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionMatrixTransform(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform
    _iid_ = Guid('{16cdff07-c503-419c-83f2-0965c7af1fa6}')
    @commethod(3)
    def SetMatrix(self, matrix: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_MATRIX_3X2_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetMatrixElement(self, row: Int32, column: Int32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetMatrixElement(self, row: Int32, column: Int32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionMatrixTransform3D(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D
    _iid_ = Guid('{4b3363f0-643b-41b7-b6e0-ccf22d34467c}')
    @commethod(3)
    def SetMatrix(self, matrix: POINTER(Windows.Win32.Graphics.Direct3D.D3DMATRIX_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetMatrixElement(self, row: Int32, column: Int32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetMatrixElement(self, row: Int32, column: Int32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionRectangleClip(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionClip
    _iid_ = Guid('{9842ad7d-d9cf-4908-aed7-48b51da5e7c2}')
    @commethod(3)
    def SetLeft(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetLeft(self, left: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetTop(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetTop(self, top: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetRight(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetRight(self, right: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetBottom(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetBottom(self, bottom: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetTopLeftRadiusX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetTopLeftRadiusX(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetTopLeftRadiusY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetTopLeftRadiusY(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def SetTopRightRadiusX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def SetTopRightRadiusX(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def SetTopRightRadiusY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def SetTopRightRadiusY(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def SetBottomLeftRadiusX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def SetBottomLeftRadiusX(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def SetBottomLeftRadiusY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(22)
    def SetBottomLeftRadiusY(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def SetBottomRightRadiusX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def SetBottomRightRadiusX(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def SetBottomRightRadiusY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(26)
    def SetBottomRightRadiusY(self, radius: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionRotateTransform(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform
    _iid_ = Guid('{641ed83c-ae96-46c5-90dc-32774cc5c6d5}')
    @commethod(3)
    def SetAngle(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetAngle(self, angle: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetCenterX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetCenterX(self, centerX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetCenterY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetCenterY(self, centerY: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionRotateTransform3D(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D
    _iid_ = Guid('{d8f5b23f-d429-4a91-b55a-d2f45fd75b18}')
    @commethod(3)
    def SetAngle(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetAngle(self, angle: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetAxisX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetAxisX(self, axisX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetAxisY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetAxisY(self, axisY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetAxisZ(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetAxisZ(self, axisZ: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetCenterX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetCenterX(self, centerX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetCenterY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetCenterY(self, centerY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def SetCenterZ(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def SetCenterZ(self, centerZ: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionSaturationEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{a08debda-3258-4fa4-9f16-9174d3fe93b1}')
    @commethod(4)
    def SetSaturation(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetSaturation(self, ratio: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionScaleTransform(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform
    _iid_ = Guid('{71fde914-40ef-45ef-bd51-68b037c339f9}')
    @commethod(3)
    def SetScaleX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetScaleX(self, scaleX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetScaleY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetScaleY(self, scaleY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetCenterX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetCenterX(self, centerX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetCenterY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetCenterY(self, centerY: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionScaleTransform3D(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D
    _iid_ = Guid('{2a9e9ead-364b-4b15-a7c4-a1997f78b389}')
    @commethod(3)
    def SetScaleX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetScaleX(self, scaleX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetScaleY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetScaleY(self, scaleY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetScaleZ(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetScaleZ(self, scaleZ: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetCenterX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetCenterX(self, centerX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetCenterY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetCenterY(self, centerY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetCenterZ(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetCenterZ(self, centerZ: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionShadowEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{4ad18ac0-cfd2-4c2f-bb62-96e54fdb6879}')
    @commethod(4)
    def SetStandardDeviation(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetStandardDeviation(self, amount: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetColor(self, color: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_4F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetRed(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetRed(self, amount: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetGreen(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetGreen(self, amount: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetBlue(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetBlue(self, amount: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetAlpha(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetAlpha(self, amount: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionSkewTransform(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform
    _iid_ = Guid('{e57aa735-dcdb-4c72-9c61-0591f58889ee}')
    @commethod(3)
    def SetAngleX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetAngleX(self, angleX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetAngleY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetAngleY(self, angleY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetCenterX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetCenterX(self, centerX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetCenterY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetCenterY(self, centerY: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionSurface(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{bb8a4953-2c99-4f5a-96f5-4819027fa3ac}')
    @commethod(3)
    def BeginDraw(self, updateRect: POINTER(Windows.Win32.Foundation.RECT_head), iid: POINTER(Guid), updateObject: POINTER(c_void_p), updateOffset: POINTER(Windows.Win32.Foundation.POINT_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def EndDraw(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SuspendDraw(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def ResumeDraw(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def Scroll(self, scrollRect: POINTER(Windows.Win32.Foundation.RECT_head), clipRect: POINTER(Windows.Win32.Foundation.RECT_head), offsetX: Int32, offsetY: Int32) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionSurfaceFactory(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{e334bc12-3937-4e02-85eb-fcf4eb30d2c8}')
    @commethod(3)
    def CreateSurface(self, width: UInt32, height: UInt32, pixelFormat: Windows.Win32.Graphics.Dxgi.Common.DXGI_FORMAT, alphaMode: Windows.Win32.Graphics.Dxgi.Common.DXGI_ALPHA_MODE, surface: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionSurface_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def CreateVirtualSurface(self, initialWidth: UInt32, initialHeight: UInt32, pixelFormat: Windows.Win32.Graphics.Dxgi.Common.DXGI_FORMAT, alphaMode: Windows.Win32.Graphics.Dxgi.Common.DXGI_ALPHA_MODE, virtualSurface: POINTER(Windows.Win32.Graphics.DirectComposition.IDCompositionVirtualSurface_head)) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionTableTransferEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{9b7e82e2-69c5-4eb4-a5f5-a7033f5132cd}')
    @commethod(4)
    def SetRedTable(self, tableValues: POINTER(Single), count: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetGreenTable(self, tableValues: POINTER(Single), count: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetBlueTable(self, tableValues: POINTER(Single), count: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetAlphaTable(self, tableValues: POINTER(Single), count: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetRedDisable(self, redDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetGreenDisable(self, greenDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetBlueDisable(self, blueDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetAlphaDisable(self, alphaDisable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetClampOutput(self, clampOutput: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetRedTableValue(self, index: UInt32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetRedTableValue(self, index: UInt32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def SetGreenTableValue(self, index: UInt32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def SetGreenTableValue(self, index: UInt32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def SetBlueTableValue(self, index: UInt32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def SetBlueTableValue(self, index: UInt32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def SetAlphaTableValue(self, index: UInt32, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(20)
    def SetAlphaTableValue(self, index: UInt32, value: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionTarget(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{eacdd04c-117e-4e17-88f4-d1b12b0e3d89}')
    @commethod(3)
    def SetRoot(self, visual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionTransform(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D
    _iid_ = Guid('{fd55faa7-37e0-4c20-95d2-9be45bc33f55}')
class IDCompositionTransform3D(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionEffect
    _iid_ = Guid('{71185722-246b-41f2-aad1-0443f7f4bfc2}')
class IDCompositionTranslateTransform(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform
    _iid_ = Guid('{06791122-c6f0-417d-8323-269e987f5954}')
    @commethod(3)
    def SetOffsetX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetOffsetX(self, offsetX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetOffsetY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetOffsetY(self, offsetY: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionTranslateTransform3D(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D
    _iid_ = Guid('{91636d4b-9ba1-4532-aaf7-e3344994d788}')
    @commethod(3)
    def SetOffsetX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetOffsetX(self, offsetX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetOffsetY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetOffsetY(self, offsetY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetOffsetZ(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetOffsetZ(self, offsetZ: Single) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionTurbulenceEffect(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionFilterEffect
    _iid_ = Guid('{a6a55bda-c09c-49f3-9193-a41922c89715}')
    @commethod(4)
    def SetOffset(self, offset: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_2F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetBaseFrequency(self, frequency: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_2F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetSize(self, size: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_VECTOR_2F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetNumOctaves(self, numOctaves: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetSeed(self, seed: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetNoise(self, noise: Windows.Win32.Graphics.Direct2D.Common.D2D1_TURBULENCE_NOISE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetStitchable(self, stitchable: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionVirtualSurface(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionSurface
    _iid_ = Guid('{ae471c51-5f53-4a24-8d3e-d0c39c30b3f0}')
    @commethod(8)
    def Resize(self, width: UInt32, height: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def Trim(self, rectangles: POINTER(Windows.Win32.Foundation.RECT_head), count: UInt32) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionVisual(ComPtr):
    extends: Windows.Win32.System.Com.IUnknown
    _iid_ = Guid('{4d93059d-097b-4651-9a60-f0f25116e2f3}')
    @commethod(3)
    def SetOffsetX(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(4)
    def SetOffsetX(self, offsetX: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(5)
    def SetOffsetY(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(6)
    def SetOffsetY(self, offsetY: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(7)
    def SetTransform(self, transform: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(8)
    def SetTransform(self, matrix: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_MATRIX_3X2_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(9)
    def SetTransformParent(self, visual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(10)
    def SetEffect(self, effect: Windows.Win32.Graphics.DirectComposition.IDCompositionEffect_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(11)
    def SetBitmapInterpolationMode(self, interpolationMode: Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_BITMAP_INTERPOLATION_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(12)
    def SetBorderMode(self, borderMode: Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_BORDER_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(13)
    def SetClip(self, clip: Windows.Win32.Graphics.DirectComposition.IDCompositionClip_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(14)
    def SetClip(self, rect: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_RECT_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(15)
    def SetContent(self, content: Windows.Win32.System.Com.IUnknown_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(16)
    def AddVisual(self, visual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head, insertAbove: Windows.Win32.Foundation.BOOL, referenceVisual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(17)
    def RemoveVisual(self, visual: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(18)
    def RemoveAllVisuals(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(19)
    def SetCompositeMode(self, compositeMode: Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_COMPOSITE_MODE) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionVisual2(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual
    _iid_ = Guid('{e8de1639-4331-4b26-bc5f-6a321d347a85}')
    @commethod(20)
    def SetOpacityMode(self, mode: Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_OPACITY_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(21)
    def SetBackFaceVisibility(self, visibility: Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_BACKFACE_VISIBILITY) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionVisual3(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionVisualDebug
    _iid_ = Guid('{2775f462-b6c1-4015-b0be-b3e7d6a4976d}')
    @commethod(26)
    def SetDepthMode(self, mode: Windows.Win32.Graphics.DirectComposition.DCOMPOSITION_DEPTH_MODE) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(27)
    def SetOffsetZ(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(28)
    def SetOffsetZ(self, offsetZ: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(29)
    def SetOpacity(self, animation: Windows.Win32.Graphics.DirectComposition.IDCompositionAnimation_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(30)
    def SetOpacity(self, opacity: Single) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(31)
    def SetTransform(self, transform: Windows.Win32.Graphics.DirectComposition.IDCompositionTransform3D_head) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(32)
    def SetTransform(self, matrix: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D_MATRIX_4X4_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(33)
    def SetVisible(self, visible: Windows.Win32.Foundation.BOOL) -> Windows.Win32.Foundation.HRESULT: ...
class IDCompositionVisualDebug(ComPtr):
    extends: Windows.Win32.Graphics.DirectComposition.IDCompositionVisual2
    _iid_ = Guid('{fed2b808-5eb4-43a0-aea3-35f65280f91b}')
    @commethod(22)
    def EnableHeatMap(self, color: POINTER(Windows.Win32.Graphics.Direct2D.Common.D2D1_COLOR_F_head)) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(23)
    def DisableHeatMap(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(24)
    def EnableRedrawRegions(self) -> Windows.Win32.Foundation.HRESULT: ...
    @commethod(25)
    def DisableRedrawRegions(self) -> Windows.Win32.Foundation.HRESULT: ...
make_head(_module, 'COMPOSITION_FRAME_STATS')
make_head(_module, 'COMPOSITION_STATS')
make_head(_module, 'COMPOSITION_TARGET_ID')
make_head(_module, 'COMPOSITION_TARGET_STATS')
make_head(_module, 'DCOMPOSITION_FRAME_STATISTICS')
make_head(_module, 'DCompositionInkTrailPoint')
make_head(_module, 'IDCompositionAffineTransform2DEffect')
make_head(_module, 'IDCompositionAnimation')
make_head(_module, 'IDCompositionArithmeticCompositeEffect')
make_head(_module, 'IDCompositionBlendEffect')
make_head(_module, 'IDCompositionBrightnessEffect')
make_head(_module, 'IDCompositionClip')
make_head(_module, 'IDCompositionColorMatrixEffect')
make_head(_module, 'IDCompositionCompositeEffect')
make_head(_module, 'IDCompositionDelegatedInkTrail')
make_head(_module, 'IDCompositionDesktopDevice')
make_head(_module, 'IDCompositionDevice')
make_head(_module, 'IDCompositionDevice2')
make_head(_module, 'IDCompositionDevice3')
make_head(_module, 'IDCompositionDeviceDebug')
make_head(_module, 'IDCompositionEffect')
make_head(_module, 'IDCompositionEffectGroup')
make_head(_module, 'IDCompositionFilterEffect')
make_head(_module, 'IDCompositionGaussianBlurEffect')
make_head(_module, 'IDCompositionHueRotationEffect')
make_head(_module, 'IDCompositionInkTrailDevice')
make_head(_module, 'IDCompositionLinearTransferEffect')
make_head(_module, 'IDCompositionMatrixTransform')
make_head(_module, 'IDCompositionMatrixTransform3D')
make_head(_module, 'IDCompositionRectangleClip')
make_head(_module, 'IDCompositionRotateTransform')
make_head(_module, 'IDCompositionRotateTransform3D')
make_head(_module, 'IDCompositionSaturationEffect')
make_head(_module, 'IDCompositionScaleTransform')
make_head(_module, 'IDCompositionScaleTransform3D')
make_head(_module, 'IDCompositionShadowEffect')
make_head(_module, 'IDCompositionSkewTransform')
make_head(_module, 'IDCompositionSurface')
make_head(_module, 'IDCompositionSurfaceFactory')
make_head(_module, 'IDCompositionTableTransferEffect')
make_head(_module, 'IDCompositionTarget')
make_head(_module, 'IDCompositionTransform')
make_head(_module, 'IDCompositionTransform3D')
make_head(_module, 'IDCompositionTranslateTransform')
make_head(_module, 'IDCompositionTranslateTransform3D')
make_head(_module, 'IDCompositionTurbulenceEffect')
make_head(_module, 'IDCompositionVirtualSurface')
make_head(_module, 'IDCompositionVisual')
make_head(_module, 'IDCompositionVisual2')
make_head(_module, 'IDCompositionVisual3')
make_head(_module, 'IDCompositionVisualDebug')
