name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run-tests:
    name: "Test (Python ${{ matrix.python-version }} ${{ matrix.architecture }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "windows-11-arm"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        architecture: ["x64", "x86", "arm64"]
        exclude:
          - os: "windows-latest"
            architecture: "arm64"
          - os: "windows-11-arm"
            architecture: "x64"
          - os: "windows-11-arm"
            architecture: "x86"
          - os: "windows-11-arm"
            architecture: "arm64"
            python-version: "3.9"
          - os: "windows-11-arm"
            architecture: "arm64"
            python-version: "3.10"

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install Python requirements
      run: pip install -r test_requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests

  run-tests-cygwin:
    name: "Test Cygwin"
    runs-on: windows-latest

    defaults:
      run:
        shell: D:\cygwin\bin\bash.exe -o igncr '{0}'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Cygwin
      uses: cygwin/cygwin-install-action@v6
      with:
        packages: python3

    - name: Install Python requirements
      run: pip3 install -r test_requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests
