name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run-tests:
    name: "Test (Python ${{ matrix.python-version }} ${{ matrix.architecture }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "windows-11-arm"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14-dev"]
        architecture: ["x64", "x86", "arm64"]
        exclude:
          - os: "windows-latest"
            architecture: "arm64"
          - os: "windows-11-arm"
            architecture: "x64"
          - os: "windows-11-arm"
            architecture: "x86"
          - os: "windows-11-arm"
            architecture: "arm64"
            python-version: "3.9"
          - os: "windows-11-arm"
            architecture: "arm64"
            python-version: "3.10"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install Python requirements
      run: pip install --upgrade --upgrade-strategy eager .

    - name: Run tests
      run: python -m unittest discover -s tests

  run-tests-cygwin:
    name: "Test Cygwin"
    runs-on: windows-latest

    # Use cygwin bash
    # From: https://github.com/marketplace/actions/install-cygwin#line-terminators
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: python3

    - name: Install Python requirements
      run: pip3 install --upgrade --upgrade-strategy eager $(cygpath --absolute $GITHUB_WORKSPACE)

    - name: Run tests
      run: python -m unittest discover -s $(cygpath --absolute "${GITHUB_WORKSPACE}/tests")
